apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - longhorn.yaml
  - storageclass-longhorn-1.yaml
  - democratic-csi
  - ingress.yaml
  - nfs-storageclass.yaml
  - pv-nfs.yaml