apiVersion: v1
kind: Secret
metadata:
    name: agentgateway-forgejo
    namespace: agentgateway
type: Opaque
stringData:
    FORGEJO_TOKEN: ENC[AES256_GCM,data:6evVGJoVUSRk,iv:170Vmv/rAgnUj0i7dbn/T9tODwPoVzwIPQtX463B44Q=,tag:23dbsuBTJ43SkWPkogEwZA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOZEVqOEd6YVlMYW5zbjRI
            OHBDQlVLc290b1d2NUgxMlhJdEJ1WmFTZ1ZvCnBNSUFySnpidldLbXBTeTAwVXZ5
            SkJNWHloMk1WNzgzQ1Z3RWx3bW9rTlEKLS0tIFJuOWMzWWhnQ3RnbnJKUUo3TWQ1
            WnNLSXl6ekFybFFwOEV3SXJmb3JmNFUKnYHK89s7JeXTMRS0hbPEOajfuuJ3N5b1
            yU+BvP23ZH+Yc8g6ZIBHJyP4d7O8+5U5Iraq+hq5dP8Au4BSqo3bbw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-10T14:40:02Z"
    mac: ENC[AES256_GCM,data:b9+rWHAA/IHuQ8z9TDMzTNRedPPaAEzA+i4NvwJ1LWW7LNzDXAi3qAf4NQg9KtVn0fAPiTtl8xgaTuSv9CkdOULxQJRx3EfK6XRFKJo88W1320dJlaTDUIg6vkBt51TvR078iI9gZyiDnoNs17KNowGtbxVesVmTI3D0RSdCxSQ=,iv:uLvIj5ONsvEzivRJuPFwY24zTmx0ChRQbqL5H/Tr2UM=,tag:ZLMTcojvNg2uzZUdKhMLSg==,type:str]
    version: 3.13.1
