apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero
    config:
      region: home
      s3Url: http://192.168.10.94:30186
      insecureSkipTLSVerify: "true"
      s3ForcePathStyle: "true"