apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    ---
    title: "Homelab Dashboard"
    language: "de"
    header:
      left:
        - search:
            provider: custom
            url: https://search.f4mily.net/search?q=
            focus: true
      right:
        - clock:
            format: "HH:mm"
            dateFormat: "DD.MM.YYYY"
        - kubernetes:
            clusterName: homelab
            showCluster: true
    kubernetes:
      mode: cluster
      refreshInterval: 30000
  services.yaml: |
    ---
    - Infrastructure:
        - VictoriaMetrics:
            icon: https://raw.githubusercontent.com/VictoriaMetrics/VictoriaMetrics/master/docs/assets/vm_logo.webp
            href: "https://metrics.cluster.f4mily.net"
            external: true
            description: Monitoring & Metrics
            ping: https://metrics.cluster.f4mily.net

        - Kite:
            icon: https://raw.githubusercontent.com/kite-project/kite/master/logo.png
            href: "https://kite.f4mily.net"
            external: true
            description: Kubernetes Dashboard
            ping: https://kite.f4mily.net

        - Longhorn:
            icon: https://raw.githubusercontent.com/longhorn/longhorn/master/assets/longhorn-logo.svg
            href: "https://longhorn.cluster.f4mily.net"
            external: true
            description: Distributed Storage
            ping: https://longhorn.cluster.f4mily.net

    - Office:
        - Sterling PDF:
            icon: https://raw.githubusercontent.com/Stirling-Tools/Stirling-PDF/main/images/stirling.png
            href: "https://sterling-pdf.f4mily.net"
            external: true
            description: PDF Tools
            ping: https://sterling-pdf.f4mily.net
  widgets.yaml: |
    ---
    - resources:
        cpu: true
        memory: true
        disk: 
          - /
  bookmarks.yaml: |
    ---
