apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:v1.11.0
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: HOMEPAGE_ALLOWED_HOSTS
          value: "home.cluster.f4mily.net"
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        - name: TZ
          value: "Europe/Berlin"
        volumeMounts:
        - name: config
          mountPath: /app/config
        securityContext:
          capabilities:
            drop: ["ALL"]
        resources:
          limits:
            cpu: 100m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
      volumes:
      - name: config
        configMap:
          name: homepage-config
      priorityClassName: homelab-infrastructure
