apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: homelab-postgres-authentik
  namespace: cnpg-system
spec:
  name: authentik
  owner: authentik
  cluster:
    name: homelab-postgres
