apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: homelab-postgres-linkwarden
  namespace: cnpg-system
spec:
  name: linkwarden
  owner: linkwarden
  cluster:
    name: homelab-postgres
