apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: homelab-postgres-paperless
  namespace: paperless-ngx
spec:
  name: paperless
  owner: paperless
  cluster:
    name: homelab-postgres
    namespace: cnpg-system
