apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: homelab-postgres-paperless
  namespace: cnpg-system
spec:
  name: paperless
  owner: paperless
  cluster:
    name: homelab-postgres
