apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: homelab-postgres-sparkyfitness
  namespace: cnpg-system
spec:
  name: sparkyfitness
  owner: sparkyfitness
  cluster:
    name: homelab-postgres
  extensions:
    - name: uuid-ossp
      ensure: present
    - name: pgcrypto
      ensure: present
    - name: pg_stat_statements
      ensure: present
