apiVersion: v1
data:
    secret-key: ENC[AES256_GCM,data:OLAhm1sKIEUvgMsGXs27+QlaS8f/oxqvuJcr/7S+gVPwtupCsBUxQLci7mOLPEx6ENRLi+PMPL8FmHXwXYul5pe4Ct88cWALv5WkCVhtBIhmZfpUDS5VEvPPNchTu2NTY3jt1aSgMtHd6P0N,iv:5JjDYGpdXO8UM5v8Vwe01hFHoU49+WFYbjfy+fnCzG8=,tag:Q0NJsWn8W0vHXOjvgLV0dQ==,type:str]
kind: Secret
metadata:
    name: authentik-secret-key
    namespace: authentik
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSVNJa0ZDbURtd2diK05j
            elY4TW5EblpDQmcydVR6ZlB3L0dxamQ2REVFCjAzRHRHaW96anJMMUthTEhZS3VI
            eW9OSHloOFVEcGNkRmRlOUpHZ2h6UlkKLS0tIExJWWJPdzJ3QzF2LzUxTThvZXRh
            NFdCVmRJclhTek5NMmxIQ3FjQ0FrM0UKs6VONzC7gasDfN5P4+kKV3jd/z98IJTy
            /oThFxNWTNBBOa453riExUtCqMMNaC6BZMV8H2jdApCXRYwOgJSqRQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T22:32:50Z"
    mac: ENC[AES256_GCM,data:AyCnd2IuZjqgU6NpFpPfTPl65VELzFC2p1UGSznTsjKycD9LGdtoMSmjuP4nB6WT/edIi+Y9uGrzFC67bUXhmG37+yvZLmAKOxhgF+LCf6W+Uy7K/e+wNu0GNMaYGGNOpU3M1fqbZUoOtOr+bX92rlr1JvOubuq/q67QFoJIp5A=,iv:J8Awk0AA4oPzZr9DAnW81Q6I0GTR/B7AIYXGabr/Gzw=,tag:1QF7WZzmpfyDLmOm6sb06g==,type:str]
    version: 3.13.0
