apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  interval: 1h
  targetNamespace: monitoring
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: "0.45.0"
      sourceRef:
        kind: HelmRepository
        name: victoriametrics-repo
        namespace: flux-system
  values:
    global:
      priorityClassName: "homelab-infrastructure"
    
    victoria-metrics-operator:
      enabled: false
    
    prometheus:
      enabled: false
    
    vmsingle:
      enabled: true
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
      resources:
        requests:
          cpu: 50m
          memory: 256Mi
        limits:
          cpu: 250m
          memory: 512Mi
