apiVersion: v1
kind: Secret
metadata:
    name: mcp-basic-auth
    namespace: mcp-system
type: nginx.org/htpasswd
stringData:
    htpasswd: ENC[AES256_GCM,data:yk8vjfnGpxSEe/LJdjosfY1nFojlT2dxLEgzl3lphm/d2KElJhQ/2A5m9qSFKfxZ6DPjzmSSEsUPhncZtagl8DAoXizl/w==,iv:P5BOjICpVxJ6sgVygUU0SrUjb24a8+CGIQ/nMkHmSuA=,tag:CoW6qg6/P3jDEiF/TLXxIg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKZUZCbUtINm1vNmVmamkr
            aitnSTBKd1ppV0RXNnhEckllZXVZLzYxNlhzCjhoRVppRTFrL21JTy96QVRSS2pu
            dW4wLzlMbnpHM3ZLTFFPaDdHbWptVnMKLS0tIEhmUlhTT2tiWm1qTGhjSTRXcndz
            blRYVFdROEpSRmc0cFRhTVJqdXhEbmMK77KezvWB65X4HJEiRwM0pA5Wu+8Mi8s2
            ddKDMJ2y8MpyflL4bUQf5MuF5oGVfP1YrHj9e+aP4B70d2XZEk7Qlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T09:13:00Z"
    mac: ENC[AES256_GCM,data:USxE3R/PimIvgXspknw6CxibxpNXwXGEPGup1+IJQmhENwnvEZ4S3M06A7sxEqiFA4Z1N71TsXIcu4TZ81+mYbDHCjOe3NgbIekQxAk9LNrgjzqoAvwkbu7yt4/hiGkeg3j35LffZzHvJnBUPtkTSeX/65nl7IQkDe87Dak1aTI=,iv:Jvw+7pK7yKi8kYcudhP/Nu3k7IQMo6wqKjuFPsdGJZ4=,tag:bFoLpkbSpEj9YZewougI4A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
