apiVersion: v1
kind: Secret
metadata:
    name: mcp-basic-auth
    namespace: mcp-system
type: nginx.org/htpasswd
stringData:
    htpasswd: ENC[AES256_GCM,data:kpbyFD6oG0ffwUdhItH1fULJMhB+610N8Hf4Z3+n5dq3Q0m14Q9quKICpuEq4oFWwcYg7BIRqkI6rA0Z9UIbTM+PudfRsQ==,iv:6RHqT3KaPENdqbwCFZ5op35OHX3OPaW2rQZAxPq2Rk4=,tag:Ri4rCH7pZGtlKneqGd1IBw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY01qcGR0L2YycitTcG1U
            TVFiWjZYZFlpT2RvMGYyWFJKeFV2L1dZdmgwCnpKbGFCeE9mcnJsS1dETmgwcWlN
            RUViTmJ4bE5leDdWemRaaEFtVU9jZjQKLS0tIHRXNDFrYmRoMFliSG5icFkxaERr
            L3N2Wkd1MmhKdC9Wc1lEbCtGSEpSczQKhDU3ALZo2xF2k24A+mj85HlGtR6i8kZB
            7l5qg3QS4S5hz2UADgFTD01BX99tjmR+CsTgq6dAAdpQybMBiyHGkA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T16:00:22Z"
    mac: ENC[AES256_GCM,data:NNxrQzUotSezysIx7EZwgrCrNEhGxUh2VzHd0er6QTd/4D4d+W4N8yQtdgK46VAwHj8H7znMmyJ6uwBa0CYxPUL7ekrVoggBwciqdNVOTA9aX6ymDEdFohrv/eQpUFl/5+g0rDqn9LzPjsUAUA8GF7nbrujjpPtaUWMRiHKIhcs=,iv:nWSnBi+unBWYPbh1RTpLutWiwb7b59hO4dVjpBAAaw0=,tag:q9nuv+i/uNJzkFyFvGn6ug==,type:str]
    version: 3.13.3
