apiVersion: v1
kind: Secret
metadata:
    name: mcp-basic-auth
    namespace: mcp-system
type: nginx.org/htpasswd
stringData:
    htpasswd: ENC[AES256_GCM,data:gla8ejG7noqVuMdYcq9iqt3wvjI4Lost8LbsPh5A6HZ/YPXcP2XYeHlDQPfoPGbQKqRfpTeh3jmaCU1iNvo1bIg8fsYCGw==,iv:+bHCJ3XLhfGA1RMIHuTtezfeXYNvN3LBwRRNbYZpS08=,tag:yRZr3WFOYgAug5Z6y2CTUA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqdlN4UzJlNDlNYnJUOFp3
            OXdyUHRnOTJFK2tzbTFaT1NVeWxSWWF6N1VrCm9ISEcxQkc0WkZJQ09wRHpXeGJ3
            dkYxcUFlU090RDl1cldRbW13WGp1OWcKLS0tIGx4QWhDQnVLN1NkWWdONmRSYm1a
            ME0yZFN0dkkrOTZ1Qnk3TzU4U1dEYUkKNyKDTTkUk+jOspKjAs5dqGUPvJ8n6mFn
            WRRLM4xfWRx2wsseo2BMdqjNRmdr0H/9z0wv8K4pgEdI2sWyuEF9Jw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-01T16:32:12Z"
    mac: ENC[AES256_GCM,data:wPrTr97qEqt0FTNxUncksuBaOmR0q3pozVBzM7cy89WbDVGfe9oCUDsrPx3VPPMPCgeGpXIyv99p8OWPgrMDXP4ZzjNhpfxD+UM9EgiRibjqTvKmFFRETmQLEayDEru44kmPOfZhdQIDNsW1WU3IAVFAkohX6BIoAPbfs9Bm1pc=,iv:FSodB/UjyEqmcAApIxZzfQy111qCcd4f3EWMdg46EU8=,tag:x4cDoOCohXibYMg3BfRNfA==,type:str]
    version: 3.13.3
