apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sparkyfitness-data
  namespace: sparkyfitness
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi
