apiVersion: v1
data:
    BETTER_AUTH_SECRET: ENC[AES256_GCM,data:BUkXXTV62rhRgOhpg/KFmcUzjr1gC3FsvYufWcWb8GVuV/GK++BnFHlPAHQXn+PZYGsKHTc5d1YtyL6DLWG2JISxOUQDaHXcfEG7mZaYfgLkIaaMwl8Kew==,iv:Q5wgZ7Low6bXsUbnfr9PgeNrk7QMDuKvNH8I4++HbKE=,tag:p3S8u9SBkBM6jIUQwOoVvg==,type:str]
    SPARKY_FITNESS_API_ENCRYPTION_KEY: ENC[AES256_GCM,data:bScdP4ihKQu9YNzGDw+zFR8tW6GD1SS/OZQLkq3JxaXVmn4k3kdvXH/xIYmbSNr9B4l+a4bNwg5MqECrBUFVgpWdQGLwDzna9o9OzuthCn8OGXOa1Z1qMg==,iv:01fHG+iZLv18ViKq+2sYJxdv2Jd0A13qgIws3tsjbKY=,tag:KUI9plU/6LFTXYbZi5NDjw==,type:str]
    SPARKY_FITNESS_APP_DB_PASSWORD: ENC[AES256_GCM,data:WbCxYxQwCMGB2EK9DH+jVA6qSUCt4n9f,iv:JD8AirrpwSxntRuAjGhFxci+6Vr5r6OcyZuyACZg9MM=,tag:Xs47AkQXB+EZsgdW972vIw==,type:str]
    SPARKY_FITNESS_DB_PASSWORD: ENC[AES256_GCM,data:F3a9Gr7DaKSx5kDVVoxPfxDTTi3RhhbLHQiLtw==,iv:gP+smNCN1qaNv/QmDsIVX+s9TpmcIvtCBaZJj1w4pYw=,tag:DLU855vj2DAIs456v/tBGQ==,type:str]
    SPARKY_FITNESS_OIDC_AUTH_ENABLED: ENC[AES256_GCM,data:D0TdSLItQL0=,iv:5A8davd8BhwQ+xzcIlM0TeY/m3zyX9MPYomFVGbQVM4=,tag:vzH6LBkC6D2sWfFd4n5e3w==,type:str]
    SPARKY_FITNESS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:F9VsfOxEEDm0BpMGtveSd31UUDNjmakyP90AfG+WP+YRd81v7gtVj3ckzvmZSeC7kninfN9S/9E=,iv:sO1XUoJ9ns4w27EOqvc16uGMlaatNGNoGJc78BkSo8Y=,tag:ue/xtaKMtjLux2GUrEJmyg==,type:str]
    SPARKY_FITNESS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:MeIy+4VJg5YaBMEjjoU6n+UAGMz+EDDwPiZmSlqKAvmat90YuSmKMnIJIFemcOzCppaYiEvmikGbdyowRDJyLmXPwmQ7joOT3aMflv33hY1WzRxwIKF5nW5UVVVCKULGBUU9mZo/L6DUAZogsnnOTykIJRU4EaO0w3rku9tqcE8ya5yj1Pf8qTTyzRfTCHnai8lQe4a3IZNWky2jc4HHXCQnuc8zZ1deSU5Bzg==,iv:TKCDmE6w1iktt5Jiw2XxZ0Wk0pjp5rnxGPxX/twm5/8=,tag:5Kp5Q53QgyyFIRebyYyAbQ==,type:str]
    SPARKY_FITNESS_OIDC_ISSUER_URL: ENC[AES256_GCM,data:gwOBmtWXcL9P3T88i3gANZEONWRhkGpNl45mHReYzL6YBvV+djYvb8Q72Ak8lhnaCIRBa04Y5rpddyFcs2DV9KpV/eEUQkpQ,iv:LmjV9uEQN6KBIoWBay8DarKmU7kViJyDF0NcZ6w1UWE=,tag:gvxJ+kar48bOfP/0E8dFFA==,type:str]
kind: Secret
metadata:
    name: sparkyfitness-app-values
    namespace: sparkyfitness
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETG9wRk4yRUQ5U1hrd0xw
            M1E2SENDYWNRMFBkdFF5Zlp5S0p1dkhnU1ZVCm0vNyt3ZzhLbG9EdzRPaEVEb0hN
            WGt2dERDNy9hT0FzMGR2SGMvQlZvajAKLS0tIG05Wk1nMUR3UDRxWUpqUHJQUXBt
            SFNlb1QwTkxHa3pia0RJRGl4Sm01V1kKWSdgBV7w4MMBCGzLRiM/vYplf2PXfo3p
            o7htiO4b0vjmpYy6Rk5whGmkp86+i4i9SnZqsMfdDTIA5nvJxR6ztg==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T18:37:51Z"
    mac: ENC[AES256_GCM,data:rjAE4FQS4VZuC4LsiUKVstfbLqqIxl2bJXS4uZSK3qt+MUR9PlhKuTdGGMBQruDjcHw+cmgyPy3i4Ny14kNG+W79JLHEoUtO1q9R6L3hPkrRksjPKZOENPXpvnW1ToZMhpuoN9sUyckO6XfOYpxNP79jK4jXUqMVgGpj56Dohs0=,iv:yJIlSFXZ/5xcFOqRSMSVRGRDxfE1WWe68sJDW49/kRI=,tag:gYwF2DTUL/EcALJ36lb5Gg==,type:str]
    version: 3.13.1
