apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-f4mily-net
  namespace: cert-manager
spec:
  secretName: wildcard-f4mily-net-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "*.f4mily.net"
    - "f4mily.net"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
