apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
  annotations:
    kustomize.toolkit.fluxcd.io/depends-on: postgresql.cnpg.io/Database/cnpg-system/homelab-postgres-paperless
spec:
  interval: 1h
  timeout: 15m
  chart:
    spec:
      chart: paperless-ngx
      version: "0.0.3"
      sourceRef:
        kind: HelmRepository
        name: breuerfelix-repo
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: homelab-postgres-paperless
      valuesKey: password
      targetPath: paperless.env[4].value
  values:
    paperless:
      env:
        - name: PAPERLESS_DBHOST
          value: homelab-postgres-rw.cnpg-system.svc.cluster.local
        - name: PAPERLESS_DBPORT
          value: "5432"
        - name: PAPERLESS_DBNAME
          value: paperless
        - name: PAPERLESS_DBUSER
          value: paperless
        - name: PAPERLESS_DBPASS
          value: ""
        - name: PAPERLESS_REDIS
          value: redis://redis:80
        - name: PAPERLESS_TIME_ZONE
          value: Europe/Berlin
        - name: PAPERLESS_OCR_LANGUAGE
          value: eng
      ingress:
        enabled: false
      volumes:
        - name: data
          path: /usr/src/paperless/data
          size: 5Gi
          storageClassName: longhorn-1
        - name: media
          path: /usr/src/paperless/media
          size: 15Gi
          storageClassName: longhorn-1
        - name: export
          path: /usr/src/paperless/export
          size: 20Gi
          storageClassName: longhorn-1
      secretRefs:
        - key: PAPERLESS_SECRET_KEY
          name: paperless-ngx
        - key: PAPERLESS_URL
          name: paperless-ngx
    redis:
      volumes:
        - name: data
          path: /data
          size: 5Gi
          storageClassName: longhorn-1
