apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - consume-pvc.yaml
  - paperless-pvcs.yaml
  - redis-deployment.yaml
  - document-services-deployment.yaml
  - helmrelease.yaml
  - ingress.yaml
  - scanner-smb-deployment.yaml
