apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrepository.yaml
  - n8n-encryption-key.secret.yaml
  - n8n-integration-credentials.secret.yaml
  - helmrelease.yaml
  - ingress.yaml
  - rbac.yaml
