apiVersion: v1
data:
    github-token: ENC[AES256_GCM,data:ONnRlda4415BhtLJmC4ybHH1Ayc7y78Ujsg4k0uAzQBVPcE/ce7IfsPnBfUuEl4ssc7XItYBkd+uy8hrbxi7lWh75NOYbBWfmv86oPWTSGfjcwJtr+m15ZAKTGAUplVYsBhLjCI40spzm/8fIM6nM5iT226xMp1q1MuYsw==,iv:VPDqQFOwAW8h3AbRHnc5WNij0q9dDsxy/v2NPvLYC88=,tag:B6kz2mKRP0e+jgPwXYlspQ==,type:str]
    llm-api-key: ENC[AES256_GCM,data:MTy/GdLCvLho+s56DlRFkct6oOJ8r+SYyUlAnk2u9ljmKBwa/m7ZSAjMDqq7QiCOsPP2iI/FsLkg5Z1kJzdAyAA/5tMyetvfwFk+lWDk43RpKaBnA00UWu9bm7ensbSCFU1yPbqXcPmJnx1cAOApKyKzPwH8XHbSxOZvFQOoRv1cZoA8aAf/7SEVY2d1MAtzQ1PhshyhU39sWFiQp5Rk9UiqVWrDEDTnc4YL2TeCEckgdPu8z97XEXfT0gv51/MkHWbvytLaO1xMAj+P+0YVlRZkXrrbZqPg1Zstmg==,iv:OXD4fmXlbRx4PXlo2E7Wzh/tViJl4XMm25q9x9QULA8=,tag:xpSN6byf3Q/6c5jstKGkLQ==,type:str]
    llm-base-url: ENC[AES256_GCM,data:hPUTVDwg4BlEqCeLh/Us4foqUKSUQGKkLSUcmgUHN0HaonSd,iv:EguF9e4oqCvt8M5ZvdFxvOAwInerBoOJheidk9d35ts=,tag:PWj2VdDUT1GbZzpYMAxJ9w==,type:str]
kind: Secret
metadata:
    name: n8n-integration-credentials
    namespace: ai-ops
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVVZOcUc0aTY2SHZlcm9s
            UGQzM1VBaTFnN1N3U0llN1JLdEs4M252Z1JzCk5XdVkxcyttT3l5eXJhdGtDdUk5
            NHp3anlvSHl6T3hqNWt1a01iY3FCaEkKLS0tIHdhQW1sbnYzMTFmYUtLSDh6VUFE
            Zkh4R0kyOVJiYWgrNnE0WnBQbUx4N28KUkrvdKAUOEGeHzylPOKUsO7cZxRYeUqx
            t8RmRw/aCIPJjotCGViQ/FFmcY44dmK64V47tsQY8eUY8PpSFnUIvQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T13:51:00Z"
    mac: ENC[AES256_GCM,data:pDWRkAiZlJ5KyftOOajJxwG9GGgkHtPsLgRiOsVSQp+AdW9+FE1iBYbjbZFCIkbQjb0bmAC0yVyovSbapY3wr8HAKp9RARcEzNe8ByC1bAuF/0zvCn4BbJuY49oWJQkLE6gCgg5xr4+NMw7jvQCPMRrjzhFxkx0nNLRzBUROmx8=,iv:lrafxSD3tn6p7CKfItm50ewDU4yK17meW+kbz9hkeyo=,tag:PBeB6dBENzd6uFO98YoFpA==,type:str]
    version: 3.13.0
