apiVersion: v1
data:
    github-token: ENC[AES256_GCM,data:EBeNzAKmWveLeceVEnAPrRBQdJ+RMu32B7hDd1odwH9ecgpNFiaXmiNtdbNG6COnwbdUfiAQORTTbwA9llZCTifOz9o2LhpdbKXUF1JXo6zeVtPi70fVB6dFMK3LW6aDqsZK+W2H8PwEo9EJVcm7WQ88nWZ7+Bhpyxqi9A==,iv:SiF9XoZv5eUcFOwCZNOOJ3kbPeoagYqZ9McnKCa0mIQ=,tag:62LaEurg4Du9w1+a1q7xyQ==,type:str]
    llm-api-key: ENC[AES256_GCM,data:Rte+HZGyPH+UFzv+6rzBhqPIStsQ9OpIoknGKnqW4xW+iQZUhtbERDO8AaDvdqv6hoDwK0xKbuHek1KpNhSGbSR5YXC7onMEHvd3gI+1uUVmgTKihsXigSDZdaPWtYBIH4oxEMxyBbgwJPAwEZeq+JJ30zObAZDEZKZ5fWm8dTgwKn6EwneVYdSQj2n12CvLl/QMux4nv8PtONjr5TSZI03Nb1+1WPd06ONh0oYahtTq1cDzqd0s8U+nu+4IuYGWDCvoGLjbxorI+17hu63OSYTi6yzOoTCWC8IBPw==,iv:NLHgJwHTwJcdRlW1n8t2Iu9aEYU+hdKL2S9yR3wvUpk=,tag:ioeD/QgmdiEVPHXRqbNjaA==,type:str]
    llm-base-url: ENC[AES256_GCM,data:3jVpelmkTaITXxzige2WOnMknxhD7+7Jn9lLf1gYkqIyy96z,iv:cXxgCu3uA07NwP8b7088qm2jz2ySqM/Mt285dt947VA=,tag:a0q2NXCRiper7VhWQvmvMQ==,type:str]
kind: Secret
metadata:
    name: n8n-integration-credentials
    namespace: ai-ops
stringData:
    telegram-chat-id: ENC[AES256_GCM,data:bOMaghMyzApV,iv:ptUzYrayPUIdCwBC/1lk6t0F4gMIm7gmC5H11szrdB4=,tag:YNOoZzVRYHXGxYHibFpZNw==,type:str]
    webhook-secret: ENC[AES256_GCM,data:xGXFOQs96CkQZLMVMzXTJPu43/2HSYB360n15qBqR54=,iv:LiCQ13UMHPDuUOS8U4Fan7LoWGE4ReuLZkSoRCJEZnQ=,tag:rnZFeSIhMII4ylFqdP3TjQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMEdvYXgvRWgzdUIyZEt1
            TUtYUGlBa0FPRXIrak9RVzJYbnhyUXp1SnhzClpEZ1FZRFN6V0lFVXRuWU9xNXZF
            TXVmQ2VkQ3hvQjZSZHdMdXBVV0FDemsKLS0tIDdwRUFMSVNYemdRYXF0L25ScVdL
            Y1VISzNpZ2t1d2sxcEF6azZhWXorZGsKRO73EuBmDSraW+YQnZ0HwEnQoM9SXAHt
            zsGEdWPdOdH5BmNK4VuMjiwoThsB2Y38dIvEWAdahjsf+nAOwmM39g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T17:53:05Z"
    mac: ENC[AES256_GCM,data:08gqLZ4w82WMiKKPDGBEx6KQFIf+/wiWivbIo0icpVMKZPyIBYlPTywbiyNQWeS4zsyHJ0QmJ+cF3ptKkdg8CtOscoNpxn/s1k/wTScij50cfzN/HmYr528CYy03gkz4HLVzsPvUmmojUPmnmLi4ZTPS0nOrI1Csyjf2mgq5HbY=,iv:t5Bfydig0TV2uKX7se+I6hSusvVr1aGmls+tMVu6U88=,tag:jdbiBnqkgWk3J4jYaI7dyA==,type:str]
    version: 3.13.1
