apiVersion: v1
data:
    hmac-secret: ENC[AES256_GCM,data:RmsG+Jp2DgkBlwCaK6hMaiYC/udUNyv9zCo7TaKh9eXN7whRTyLq0za4ztK5NjwgCu0ZGkDWHkL7ArRFODS5FkFUts9PnWURvzBUVLvR19c69WEz2EfenQ==,iv:Yve/9dyTkBlCC3m2AMszMe8RpNKY1K6lf5pw0iYbPoo=,tag:q0EAOIxq3PuQfPuon7hwxQ==,type:str]
kind: Secret
metadata:
    name: remediation-api-secret
    namespace: ai-ops
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5WStKRGlkY1RzMktpTlVE
            dWM1UkJmZk1uQ1p6NUdTZTlYd1VubzBqODJJCnFEQXVwS0d3TW1NMFEvMGpUUGlx
            TXdZY0p4MWdkdmxNbmNsSVN4eWYvK2MKLS0tIHg0d2NzZ0xKYmV4WWxtMTQyemxt
            V3A1KzExVXk5RWROTzNHYjJsK0t4T1kKqqZ83l2nLoe4G03tPr3AYQX2As6Dhla6
            p+domeb2PXSP2rhZboUV8kaMUBj7SUUN0DtGhNWPCwugE6h6Re9PKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-31T09:37:34Z"
    mac: ENC[AES256_GCM,data:mGKkAKaecjCjCR0XWBM58cd7ETXz8sheHVLZeINMC1ksUwQ69PMii+9RXEkw9R5LbO6xh1f4Z3gBX+f5RFRllTEBeKFd7HywfFEp9PYHZ5wLb40vS2QJDGhevyyqfPHHlujZdCojTOY9CbtIkZ8Mu4ECKNUxCNYYHOqu5seKfQU=,iv:a84Sr8V0e1gCWIgIrbZ9pCJHg+aDN10qVgx+w1WSiog=,tag:TyuNQrGY3b7Y6V8ebqZNAg==,type:str]
    version: 3.13.1
