apiVersion: v1
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:V22UXRZOHrZDHURtfS4+,iv:7CFHTwG9lxzrDK1XF5+rlQ67VKLcm6PArGTPCL2P0sI=,tag:W1ZVrreOV/bBU6LwjP1twg==,type:str]
    client-secret: ENC[AES256_GCM,data:BXxux/zmPMXfPHjAh6XDI2k/5ocovtHaD8BJLvjhN7ykKv1wuzzc9BcSzyU=,iv:aqUxYEc1100PP1NMPHhDibJOSaNOQVXou+ZSWVovxUo=,tag:FhAyl9jOPKIuDt6qhG8K+Q==,type:str]
    jwt-secret: ENC[AES256_GCM,data:TmXxuHVe3yy1w7gEOcIK4ChwJKp/OUlVzu54ZzJ16c1pdD9w93Mnw0roW5HS1iPa4eGUBmnqLi+g12Jm5oL4qw==,iv:iJwWaDDQQBiIz7VPQ/YoFqhZOKpv9koQOK0oGwv8TZg=,tag:kngGEaedUk8vvVUZ9Hg+Tw==,type:str]
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzV2VibXJwd21XWkx3cEo0
            SHVOeHVtWXVNY2tIejRMVU9HdHdIUUloYUVnCmR0S3Y0WVpzWEsxTHFUTG5vQzRV
            YjAzdzFVdkJ5Y2RGWmx6OG9zdXBSVVkKLS0tIGp1bFJCd2RTRC9zK2Z5aFlOK0pr
            NElndmFhRXplNnVxWVZMelA2MkRidlEKlLBGgyL44r2mD7dEKLos7lVQNRA/jAoE
            T8RaTn9IlrKcqVmzGs48RtGvsKF8of1kZo6rJvaOr/m3H6+kMWvjpg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T13:33:00Z"
    mac: ENC[AES256_GCM,data:7Y3mz5y37INfUQAMlWntm5Fe3v8n0La6ndnC/DjZLitdZ38v4NRit6/sAoR6hM9TrYGeE+qgrwU7jvzC3gMa0K46AWVbNUqI3a/a/impntxLv4Qp4JYyYdnNmbMP7M86ug315yvaKFw7tcg/k9KXh17PYdHmiacLBQrfKPBovWA=,iv:MM0fD4cdBWCNRaXcW3qt4yf4HG8tZreAAUdX2q1ejDI=,tag:GIgaw4Cbt76xLYw34q+TpQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
