apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:89X5Sy/saCzE1xdxOqvtAonEVNs=,iv:RfVPRTNmEcoWNlXZUdJvEz2Xt++v1EQd5PKhCYp+2dM=,tag:Jov0/yyTwKyDbDQ8NAmTKg==,type:str]
    client-secret: ENC[AES256_GCM,data:0cKxRctbIUyX6f1ootKwxV/GX5G3PjiC5dCj2+8ik2lu1WEyrsHXpKfW/KHIMqmoQAi7q7mXeLUq5Rso,iv:DVb1ZmHoYrxxeZwRUze6ZBVf5GkreMkQZU3iYgFEe9I=,tag:wBOEiZWQWQ242ZjXceB6JQ==,type:str]
    jwt-secret: ENC[AES256_GCM,data:Ug+V5OKn5hEy0netD693btwmeBLXsSRSAHP9k6NY4vf9Nnm7a4Mt373VZxCdIXVI6ZATFQ7kXpMnbfThKSw+MiTwhewYaRTVVn39Fvu+XRp3s4MkGZt+QA==,iv:CBryZlezkbe7o/exYw80aHHl3tDavA+4HOMev61ee6o=,tag:r0OkUTjViZ8jXmVsE13WSA==,type:str]
kind: Secret
metadata:
    name: vikunja-secret
    namespace: vikunja
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBidmg3Z3BjRVF0dTBnY0hP
            bEVPQzlFNnFFNy8xVy9SaVRIdVA5ODZld1N3ClZ6eGhsbUZzSlBUYXdWUDFoSDYw
            bXBDVllGZGZHNi9HWHhvaWVQeUw3ZG8KLS0tIFMwcXNwMTJKODg0VzRKSEJLNlM1
            UVFqSjlNTjJpemJUU0c1TkYrcHFSWHMK1QAly7qoBzRMVjfsYUrw3immFvgQb9iB
            UOs0MlVITT1U7eh+R5OdE65n5jGQ3EV/td+PMHIxHbbv5J56Grk/bg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T13:14:06Z"
    mac: ENC[AES256_GCM,data:aeIo8gpxmmP2jhyjonJ1epgpREZ3o4GMr8MNXeBfgy7sVg/Q5M6aXKdT2po4fQdwpZcAA/2nMmELOWdfwYWzoNJH2VMig4vjGQEnRUUm6hwHMYlE5O/1U+EWvyc6htjcwQAgftr3LyLjsWA36MDEre2ZnjutWUxkUNhpiSvoN/I=,iv:OdeYlGz82iNXwLWkNvhH8JKfWUpgA3hkL+FA0GeIIHI=,tag:GGX5X3t+2kSs4QGqhsNzAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
