apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-static
  namespace: tandoor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-tandoor-static
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tandoor-media
  namespace: tandoor
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-tandoor-media
  resources:
    requests:
      storage: 50Gi
