apiVersion: v1
data:
    SECRET_KEY: ENC[AES256_GCM,data:sX2FVrFgIlGUO8PC1WrpmlIeqRazOFapQHBy3Gz5M3nhghOl3nQxB7aPA08ItxR4xQsj8A4Icv61GxySrpi15qHifCEIYmCJon9ZfWqlwCn5FP1vxeX64w==,iv:FmTRGYNhOAixvDpCa3VBb81wPDVGiHn3fXbKiYNruPM=,tag:617+qxfoy/bn1/qUOKBwkQ==,type:str]
    SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:AobTk71lLS0fINGOVlUcZQdZA323+tmBytNK3aTUahg5ArJFuGcwqscxg/ORkJhAzJbk+9LXkiDLU1yzXz8SVAVWtYn984OkKKcQy36FcUudNeh1n0KvX9JtY6ZysMpGNUeE/sG28A2AFgZYTZ9b2IzUlhOsu4x/qgmYe1ssSu49mRhqSq4e6Am1Xw+gu2UT5OfqXWD/lwaUM3pcd+QDsg4ojO9fcEqRYcag1x8/K9SZGQ3YMQZCbGdewwsz72QouRDVBR94wFbpOyxd6ZYpPkyqL6Jo5U0T2q4T5ZgU6DHu0fShDlDzRg1qsKCa+5dJMcVrv9DO5HCJACGt5E6/L3uSLOS1hJkSJ2wOGfu3iHL7E4nw6gPwBWWQDa7YpYRyo2o8sBpNhUZdG9XcldK5g8rQPL6bu2YjBP6OlhdYkg0ZsZSP+bPL5bqkdfNS2SO5V6+nGLyg2FU=,iv:CkWeMuSXeEDf7YgG2qNngKHE7b8I4Grpqro0y8ruM+k=,tag:acDewTtWD7kH0ekg+FP3sw==,type:str]
kind: Secret
metadata:
    name: tandoor-app
    namespace: tandoor
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpeEdnU1ZDUlF5UDR5ejBr
            MXp5NnFMeDVRQndhb2E3SVcrSUNSMXMvWVF3CkFzV2ZRSG85bFBqNWJIdEJ3dVBw
            SmZZbW94V1NpV0pxN2dYWTVodUZVelkKLS0tIHBFUkxaY2tTZzUrZVQ3VFhmWFFP
            Wi9oQWlmYUZqWlZ2aW9vRFVHY0xUb1kK7q0TSg3MABXm3uN7O9ZfM05mPmZBqOuU
            L4PNG65YukbjA5Pv+tlRbbT4rE/+Khp0BpW09bBKbFzeHHNPxaHZpA==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T07:08:54Z"
    mac: ENC[AES256_GCM,data:xX7cfVbS2aMQL95Cw55UERVlygxgG0VfYvAu3d5jc/gBcLHrxIAWWWfAG2iqeUvWli3uYnDQA+FMr8s1F2n5Dn9hFRNp2II8lI0mtUlQ1s3hd0bDlthPr5bJLVuMOB3EWCEkooRPGT/cYTycOpLk8zgsNvUkgpaR3jIJ5fFf3xI=,iv:le4JsBBWBqQXvI7oa3RQPXArIXmcVEa05o6+HTrTRkg=,tag:pb3qnHXy53gX9NtDJfm2EQ==,type:str]
    version: 3.13.1
