apiVersion: v1
data:
    SECRET_KEY: ENC[AES256_GCM,data:b2MSiaRwZh7ZUfVPIeYxQnrZNQ1ByLhNfIs8S1MPxBDYjDFjud3IBwgKQwOwpwUA8uzOOdJ7rsvXoFis,iv:vP5HPVdl5DxENnST3ary2JsER3lE1M+sNWCJuaS5Knw=,tag:A4+DKXuWVm/cUqJRubeMYw==,type:str]
    SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:p6XzzFFVAUAFaf0hp7bAWguA60FGfp0Zmc43o9AEgPdC4z4TeKshg3aj9kIV4Gs6s7gLQmEQAeYdg2enYfQ5Vf1G40gTq7p14z/U3PkQsgyr4oSDO/k9rDsW1v9EKmINPq/LlXn/B2/SltAn2p/SEpOjo2Z7N3BQpXfz7rSbGD3vd10TtdlwCxhZmR4yxKaYPft6jAr3zubhrbFTtHxHus9triCksnIgDHro1iTfg1IAAveP+zMf2mo7WLY2yuipkSd2Ek6oQOFZStFLP6v/yfrbHEvdkS51aCtlzbS0B9oeiPW7lZMRRYeJ2S+x2W3ESDCcBo9GHcCO5J/LadOz9zZ/Ycv5m4NX4TutyajBG28HVzIEfb7eP5Fs9IDkkNKdrMq+Ty4YFgmMCOFAez0k2VSwqiLvBpN8qk8oOr3G3Y5Vk3hBzIhBf2FZLyIG/3ROBOSJRJmGQlU3W400LlTDMiYt5aIxI6WMlaeyjW0CLElBUxTPEIlXkjuy+cGHfLCe9p8ybmpwChI+JMcXzUAy+bm0++mOfUlBOVDpTYP+iJ8f3Mp0OX8WaUOOrtos8XUIGg9ZwXhQlYB5DoyOqE5jQ/6ncCO5f+5OJv1KRzWIKNb0lDDKNrnQQYKMoqNOZaOjNi3u1hUI5NM2qIltI9K2jTLUsdiR+S9aE2ql4sBaq8a5BRXJ4RSTCjvgb5I=,iv:V1NpbgSg+UlmgOyBRDjH10aUVMMXLvVSV6/fFxvGC/g=,tag:HvT3lTQCY4Md9NDrYg/mbQ==,type:str]
kind: Secret
metadata:
    name: tandoor-app
    namespace: tandoor
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTUFoNS83aFlUSnNEMlpi
            NDcwMnc4TkRDemswR25ZS0E1c3FhWXdTZnhNCkpzS0NNYlZxSHFLZnVvc043U0lS
            U2RlQXlyRkVzMVBzQVlLQzErWmVVa1UKLS0tIG83akhma2E4U28xejFpK3RKaE9i
            U1EzdVU0ZlpSSjFicmRwMmJLaDBUMWMKBLlh/5p3jNCYWIWPZU9P/VwVB66wcrE3
            8+CbS8QvNFNlLaAmAHxXmFOWrB2U7OXMWtYZPj0q9aM/OnN2q+pgrQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-25T06:18:10Z"
    mac: ENC[AES256_GCM,data:LON37yZxdu4lQHXQiQAFWXke6R27E4y6JTa8xNTmCrm5RGvGHhuRcK+jsS4LikE1Lv6Mn4yAL5FF322NERQc3iDv27rEER5FTLDpSoBA5cEbFcRUYY8cpcpDEUBBK4bwRfgvvRid/gqotRmTKEt2BEF80K/BaMxfjguRKwTiaj8=,iv:hMgXnm3csFLl/bfWCa3O6CGrKYmvdhNHsQHwFzJ7RYU=,tag:PNyRJHNVm+F6JB8yIo+BPw==,type:str]
    version: 3.13.0
