apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:ZDIWY+wui+CT9Hk=,iv:IpZf/ofNrD15TUppFqydgw2r0cXjXE1rHi+mi/3OVzs=,tag:uAiI1AsqB/sICIyGlfv1iA==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:e6woCIA+o2UwsD3NW/H7GR/nxj75BzeF7e8=,iv:Q7hmgDP91jjcl9DZWBJLsyIeYsrQv+DWiiHEDCD7XDM=,tag:intpvo1cTuK3KKProSmlQg==,type:str]
kind: Secret
metadata:
    name: cnpg-barman-s3-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: REMOVED_BY_HISTORY_REWRITE
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbDd0TnZLQklLQkpRd2hU
            MCtYZUpJUzJBSS9TbHIxMFVBR3crTkN6cEM0CnRQckRuY2FReEFDQURXVDJMNnd5
            VmUzT1lJOXdwdDNQck9oYy9KOFdXRXMKLS0tIEJHQVBvZXROa2xScER3cDEyVG0x
            MGd2TTFONGdCS3Q5b3IzZUVUZWJOUk0K47zT9uf+xPOVuxHCVmgW2ZUhxND/HLxs
            g87BKyOR05izaonBb9hufVErT5/NEwDmL38kp5WHhTFmaW7bkB4QDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T22:16:39Z"
    mac: ENC[AES256_GCM,data:ViTM5ltVq20JJgrgCdnYZcq63GxCGeMybRU75XiBavAfJQhWDtW5hn7cH7Rpn9xBt6QWOUlhKuw+fVM1UevYb3D5gforF0IHmZwfA277GN6OuCTahfezbP2sOGiqaCAUw7yen0grzXZcNB2p02+kwBdtMqUtcYv4w8uzF70rhxk=,iv:NWEZXANXF90Or5JJRTJ3Edhn+46lIPSe09GerXVUtJk=,tag:DJy9DDJHVTFLhzgylZoy0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
