apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:pBPQoQS6dEeyDmVi2tpTizvSvn6AcAnNpp8g3dTq098M+Pjj,iv:6i/TCCehKoxqfqQAVGPvrqb0OHmRYG98+sDRvJxg7+o=,tag:XhC+wNAJ7+MvvlsiBmBIAw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:64og+2cb9vOjQz7WdRv7wBq8xtZPZFpXGfu4yjtxEwF6L3KLxglKEXnZp2PvJXVsGhsCZBRr9rH28rRbkxXByd62CF7VUOGwyvM/hkpzIvvpx9FIMzobZw==,iv:keoB+pzthcQznheeV/YQk8T5sAvtD/eLYNIzkBxqkBU=,tag:GdSY47KVaKvBul1QrXLjlg==,type:str]
kind: Secret
metadata:
    name: cnpg-barman-s3-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4WmJ3V21pcklBT0RPdjBn
            VTBmbThtQjNSOGM4VEtuM2lvL1dxeW53T2dJClFuZExEdG4yeWEzKzRZeVMwTGZF
            OTRHRCtoTUZEOEU0ZFpNcFdDdWl5aE0KLS0tIGcvR2lRa1hzYWUxcnNMdHNuKy83
            cDhmbHNPbUpPaGFhZ0o0RmZSNHpGUHcKtMflHYSaneH56GuqwAkOU19X15qXys06
            4xCoWMStk4H+6dCo5xWeO4988K2rWWCE+EJQiIkAGMryhvHZPRz1UA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-18T20:47:21Z"
    mac: ENC[AES256_GCM,data:jWZDDEHI9N0CGTSLWPLrVDaygo6UQ3HDOB0xOV0Yo0u1OoBND6knabipI+5MEdVcaUK+l9dDplSDeZE37KIk44/HHJalZh8kXBbxY1Q8N/9g7IkS4vsUynZ1zfIShjXhYSrW2BheXbQnybkQf555KCFFoANB0HaWDrIPkV+hOmg=,iv:Y376RtbjoR6Yta/nbaThwo2NpzJ5flrkqpDiWXXFoqA=,tag:XQPPz7cd5leZsq4S0Xwr/g==,type:str]
    version: 3.13.0
