apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:/4xxernZF8+UySux,iv:a9shFgBTf2H64dRGvsahfP3foUbmOqgF4q/Nsn+CZa8=,tag:1el2S6cTVpGuUMYZahRyCw==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:nktDTBLoafVDPj0e,iv:wzQ2wnq6ZhV8wGNHq2MbDhANSrVKSVDKude+GdIxuJs=,tag:Lj1nUn7SZBnh6Os6VCqi0g==,type:str]
kind: Secret
metadata:
    name: cnpg-barman-s3-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbDd0TnZLQklLQkpRd2hU
            MCtYZUpJUzJBSS9TbHIxMFVBR3crTkN6cEM0CnRQckRuY2FReEFDQURXVDJMNnd5
            VmUzT1lJOXdwdDNQck9oYy9KOFdXRXMKLS0tIEJHQVBvZXROa2xScER3cDEyVG0x
            MGd2TTFONGdCS3Q5b3IzZUVUZWJOUk0K47zT9uf+xPOVuxHCVmgW2ZUhxND/HLxs
            g87BKyOR05izaonBb9hufVErT5/NEwDmL38kp5WHhTFmaW7bkB4QDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T21:54:29Z"
    mac: ENC[AES256_GCM,data:MHKnn1t35Bm9e5JVW1lbPKsYYhLgtvKFnFUeJMcRJvUM5QUjTTb4SOw7rJezd85ZuwW7p07mX6dCd2X9gi3e534VAoIeHT3wubgDSWs4veBtIiiD8UeraDFi0XYTtcrgsOGKZoDAZcEYenAFLHybMUNx+w79JYkXeaexhcYfVOc=,iv:+ordOlvIDNAp7BiEhWPve1GNUK5pZ5XtM7XBVrvVnGk=,tag:K+Qamclrp4hjtqU5nQidmQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
