apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:lj9nYqfUNNZW8EvnjQwI4u0Ch8nyQDM06A9kfKBkN87OIKxZ,iv:blEPik9LEApEWac9MwrGhELSgZch+ZI3NIwviZZJbJM=,tag:w8eeuDYeVR2qRExaxwX+5A==,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:/g2fO3P4JJjXx39IybvIhE6Y0B39o7UA+Cd9eaXCZhUWSs0TQPgMLZnSXsQ4mhN+4Os8LWKzKFWAOdE+piguDq/mDiViZn4dFWRIP8507R4cjQfQGDcpbg==,iv:Q3icIS0iwILPldb1q3f2zRSqqGVIOkFJgZPuAPFDevc=,tag:A3PS0HvICZgMQHWh2/xZsg==,type:str]
kind: Secret
metadata:
    name: cnpg-barman-s3-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZndoclFsZjlOVzFIRExl
            Z2N0MzM1b0NPNXFYbXZkQ2pjTk9vY0ZQd21nCk1RLytRMjNLTVhvaXkwcFZtekVY
            MGNaaEMxRnhOa2tiYWdHcVRYYmxaOTgKLS0tIE1LdnZlQS9QMW9ROFNkRGtiWDFp
            U2h6aEhaM1J2a3RWM2NXRFAyMkg2VDQKbH9BlG4ZGVM+3gYGxJdNs+kAYjOZTv2s
            YmNL5q9NorqQrsAZs7utcKNhUBj0+ziwA16jZWd2uiveoz1OF7Bpgg==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T23:13:38Z"
    mac: ENC[AES256_GCM,data:Y0ftQrVISv5L2mY94cpY2/6KIU4EBTdHq4iG+IbEruVP2U+KqDikWFOdKMq5kXer6ZqIu+Kpk98i+LKoQca+Wimom66XUSVVzBNSeHEyS1IDAopsYaXDlD+iuHKdXwj5A/IM3qQSXLFZoqD+yH7BUFsqc0FnfmPWvZl5eg8nsOw=,iv:iS4Djug1fUD+2PE995GU5FwafY2nXRblyLyGWNHpv1k=,tag:GacYf+uAC0XzRVOkVZ0Yyw==,type:str]
    version: 3.13.0
