apiVersion: apps/v1
kind: Deployment
metadata:
  name: reflector-system-reflector
  namespace: reflector-system
spec:
  template:
    spec:
      containers:
      - name: reflector
        resources:
          requests:
            memory: "256Mi"
          limits:
            memory: "512Mi"