apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - network/cert-manager
  - network/reflector
  - network/external-dns
  - network/ingress
  - metrics-server
  - system-upgrade-controller
  - backup
  - database
