apiVersion: v1
data:
    BOOTSTRAP_ADMIN_TOKEN: ENC[AES256_GCM,data:OAzYxMA2wvZwjuxqk3XUFOqGpC7EWrTJzdy8KvGs2UnZ5u/SRvCoShCkfBtJ+B3NCsPsB71urek=,iv:RxXery5p87R1HS2ARNisAsaSx7EHUuRo81uh290YF00=,tag:pqs9Ydu9y0u65ieuYzEVJw==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:pvfOjnkqnc+C/0Epeki95vQ8ourCA0fLqh+9A6zJtlBfzYnv8OgM/R12+J+cLE0oYL08zU3GACHtx/bxOPgrBASbFGEyfC/E1Co6jtmz7It83TPW1SSjUA==,iv:rVCKUKZLLt1XpXh8nJOzB2vXmO6YYSoe1ivpG2i9tL8=,tag:bFoJ/g5yshVjdb9AvRUC6Q==,type:str]
kind: Secret
metadata:
    name: goloom-app
    namespace: goloom
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSYnRqWW5CRlE1LzY5WHhm
            OXhKcVg1SEN5K0VFTlRHOTkxcGtsclJrd3k4ClhtYlBsWVgrZVlNWHZoZnpZWUlr
            WVBraFFZZ2N2M2ZhQ2hzbDJLREk3cGsKLS0tIHM2cDg2RnhIODdQWEJrK2UzWHJZ
            YitpNy9KRm5kWXM4NWdZTXlRQndtK00K9qQg5y8q2QG8xAPZ1PdMH40MT6dCjVZg
            a0vE1ge/IjWFx/fvAq7zfClWVMTTL28ELB+Pfezw8XnLk8k45MHmpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T23:27:34Z"
    mac: ENC[AES256_GCM,data:YYRrMVM+yh8Lk6+kmpp44azYDCPBe7qkxvGCSvZV2q+ieloAOyvqj3RDeCW+K7xJ/44ZyC2tKabrO6COPE/3i+23r3CTxy8/17AcmXiy4CEfgS0OlxWylCld0qA/EJAHlblOSHhYCuEZbzsABnerEziC53rm8nkTTnp+bKEm8Cc=,iv:HRE3oQcqTIBNruInDGHU1+uEPH+B5lGU+61NiBTomBI=,tag:RUIIZVhosiqgZUq86HpzoA==,type:str]
    version: 3.13.0
