apiVersion: v1
data:
    BOOTSTRAP_ADMIN_TOKEN: ENC[AES256_GCM,data:VZhErXEqhdkbpUdE3PQ2qMQMjmZrAQ6T,iv:0J2UM2WKbEZJW3b15B+sOYknugXtyh0YBAxPBND2iHg=,tag:29k0jyxpyU75FsBR1za6RQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:EJK5gl8oeEBrprLn6cl7LNBHy6K2qXgtQDYsoNC0lLvbnGM41tq8o5wgjfPHodORBhfWaUuKJu3y31ga8bH8/f6RTq7JKoc2GxbnRpQjbPgQoCR/2VBgSIu3x+3d4Ool048VxEv4XunhE4+MAlewljyWXwf87JVUtM4EmrOkeBKj0sr9T7vgxJxGkwKO6+w2pzpBAz8iKQP3U9d3a7NzpiTzf/O8OghjInUmXg==,iv:1aP7eaBFW+ZeLoVEZ7ny6ZhFZqjAWRGOWZ73p5w7CZs=,tag:xDFiyOTTxYYHTIg7i6+H/Q==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:nadwPfu5+O+EbX+MifFNPZhGfZHhJyQvbWY5I0dc17vGqgSRxs3E5xOxipDWKyJhkmXQarg1cuI=,iv:LCWn3dTZmjgXyYWxN8EtAYmo8Sg+AwVHuOHttRkK2hI=,tag:vLdInuRgDiBwJuiJN/HTIg==,type:str]
    GOLOOM_API_TOKEN: ENC[AES256_GCM,data:ciY4o2S/med62RRPt0w3nTq5UTkCcIruw56JATEfc9iP2slG2b6k1iFzIMoppXma,iv:3RUO4RxAWAwzFjl1kRl3i/Lhg1H5HloiZPvvUUOi6wE=,tag:x5RFRhJTz4I1P/2GuTfzEg==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:Q4olWbedjJEdnqEiKK7uS97ZDemPrj+hNLudHF3kN5ycHHyjGnROyy2ZKv6F39FJGQsQM3/gKeUp3Rf/BuuIfFm/nghIIVt6jLVcCG1z0ziZp3P2+cLqDIhfNY8vOPkRhQp7kazSFBoM7WDDx12eU8u/wEd7Qn6y0YlHUZi+cWCQj2x6C8u6xoVgQw02TmnFTzWNedwfVGPz1v9TI5237hFbW8uzpjWyA5DBvQ==,iv:ch2yZCMEqx0EI+VNfkPZfoN5XaW9R9OAgKGG5w8Ag6M=,tag:EN66jZs8bqDtzszLwK48Uw==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:NqltqWvezSgBhi4ukZRoi+w8byCz3DrP9Y/i/CA63JkO6k3A3+xelF2Iu7oiGJXhsaIotnyLa4L4SthLK5CdYRQVbcQpcWJ6tL8i+B3Lihxsa1LbDfMse79MR2rkBde+U9UQsxb5jToQsCm6ojOrmdbGbvxKpKF36D7P1NSDpAPO+gBd3slNdjPsOqLiMHMS8PnPXVht/VSFosGjxqlNHnes8j8X9YcaUvU+4sRgiLD9WhmYQRlyhxe/hSDoXuwwn0pKRe3ICNn1lSUIIqs+7/vi6gLNjGxoKDhNMw==,iv:di/58YPEjc6q604rCyBSu0OewZCjhVOqrybNwHbC3SQ=,tag:96ukPqRgSnupNvGI7VNgNA==,type:str]
kind: Secret
metadata:
    name: goloom-app
    namespace: goloom
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bWR0aHl1d1pzOTFsL2JS
            aitCLzRwakVaa1dGbml4d1dMR0tyVHlJZTFNCkxSdDQ2REE2dldmQ0N2SGQ2V1hp
            K3g4dUJ2TlZncHFhWWhXa1RnaDJlczgKLS0tIHdpNkxsd1haMks2V3hlQmlKYTZV
            T1NlMlgrMFp2UXVacUwwMUpieDA5d3cKb1vpbegEJmHw5o7ZgqdbIlv18d1iAzI6
            dlW66a65vWxtGtMw0EUS5LWVduZhRABrC4vex9itSnYqdXWb83kZQA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-27T08:22:39Z"
    mac: ENC[AES256_GCM,data:1GLxl/1eUa+sys4vcITF5F4waDfOtWFsH2WROU3k7h31s+okD2GxzKjFL0RBJ25Zt5An0/+PJ17aNOpmUSn3mxllSGu02JMFf585tOGMZziKPIcYNRQRKX/oYGj6eGJ+E+RRLlOeQ1jBRg81c9sqKProQbiN1o/yCC1ySN1zAqM=,iv:4iabtoq2oo5cKjP94mF/ns1VsZdmuq9faIpQvRgawfQ=,tag:d7yS4J8urg3MuwUAMUxrGg==,type:str]
    version: 3.13.1
