apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageUpdateAutomation
metadata:
  name: goloom
  namespace: goloom
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@f4mily.net
        name: fluxcdbot
      messageTemplate: 'chore(goloom): update image to {{range .Updated.Images}}{{router .}}{{end}}'
  update:
    path: ./apps/base/goloom
    strategy: Setters
