apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - goloom-app.secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - image-automation.yaml
  - image-update-automation.yaml
  - vmservicescrape.yaml
