apiVersion: v1
data:
    password: ENC[AES256_GCM,data:WzxjUaTUaEC6okwDhYZbGnLhQeubPxR8pgFIO4a1VTXUCN6u+vVmx/leRP0RfD5gzIVGxAldLsResFmuUqlqbYXIPaZNYEECzlINFZqUbP6PpFgQPtFYOg==,iv:o9xgXbExK/V6AnSxrBLT3SXyszSRGA03FfJnCepv7tA=,tag:3b3w3nGCBRyZ3W3Cz7Y+nA==,type:str]
    username: ENC[AES256_GCM,data:rIMHHojQGNJW6z1z,iv:v6vhHb6GyLOXaxblKjpM6QKfybUBEMjb8DZrx2We1BA=,tag:dFbJ1J+fqmcwo79lWyUVsQ==,type:str]
kind: Secret
metadata:
    name: dawarich-db-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAraXhrYzlWZUJLVmV6d1JU
            RXczdUF2cDFqRzBobWRXYlJuUFQ3WkVPMFhBCjg1YURGMldhVzBqWDRTR2VJajA0
            TEdzNmVwNWJOMTVGaDhLT0hGNHNCSnMKLS0tIDArSUNEZS84ODQ3eEZlYzlKTmda
            WkhMRWRpRDd0QnBMYmpoTDFjOHlKL0EKEO4nMeT//uRMf4rO0IXUvAAcW/gnL/Zs
            7mGrDr8OUQeM1U0YTRvIsRkxUfHexDuo36Fn9dRQOgnY+Bi794gkwg==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:44:39Z"
    mac: ENC[AES256_GCM,data:2Jc7EwSrbvUi5xkx0NLyBXsVn2XLPwL4sXR1cdEgTmUvrduegKphU0ah06cGD3qwaQY88umlKwuVRHso12MDmmC59DgZdrM/3J31NhkhvyNFcE0x2722fHeWdHaPCYhMRA7yaX1IuN/SZeJhwRODc3Nxz6NVnNXg4gj3Hj9XzRg=,iv:yJb201mhNgLmsBxRpnTRbBHb6OhCL4zIIUr6JxqhJ+4=,tag:fnhmUNhQiFHd3PmwSo5B0w==,type:str]
    version: 3.13.1
