apiVersion: v1
data:
    password: ENC[AES256_GCM,data:eEjvwwgc1YoptTRxkUSxWNDDxaewYyYz5Z43cepKXtLiQrmj/8YYv/sE1kY=,iv:vHTPlHixV5afrDSfm5q9OjBBWC7DvLkhqRqEAzMzSvM=,tag:5CI+Y8foxef5BEmXCvY4tw==,type:str]
    username: ENC[AES256_GCM,data:CzOhtvY0DI8=,iv:9zpYDo3vF1GWhXhHpmVb/Ahdy9IcOsN8AsxpLwavvs8=,tag:WWny1JNTNX71tXGJLxw2fw==,type:str]
kind: Secret
metadata:
    name: hister-db-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXelplRlNvZDVldGRIR1hn
            QnhHV2gyS1o1YU5CeDZTc3B5ODVZZy95K2g4CmRlTnZiQUFaZUFqZXNFWXNSN3ZV
            bkNkQ3ZQQW9yKzZJS0dLR0Q0eldWQ0UKLS0tIFNlSGJGZFpkdWJEZkpkRXNuZ21N
            Q3Y0R3p4cnI4K3BHTmltR25ZYW9sdzAKYbz2ci2w+lP5UoH4aOM+g3D5Yesk4+qp
            0wkcD73nIDOxbystVtOdkKw/ppODyoKjWCjNZID10LKUzsXjXrdSsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T10:42:47Z"
    mac: ENC[AES256_GCM,data:B9KoWj71FspYqTQa424WMLb+ym0EhlNcLPZbY5JM8WT8lgRK/JOHXhqKyBF4zYU9vqke1cF8LvhCnB/1MgUaIlEzTU5yLB2C/aQsMOTYzfyy43xDl2uip0WxXcfNnYnYS6W98MVbGXeuw5L5vtx+9pYq0c+Kt+gNDQ6Pd9F3IAI=,iv:oDrEjpST9YJEUnZdOU7JNQyXwoV+xQSNuMQXZbCjg3Q=,tag:1HCZjJZc+/eFufnhsg2v2w==,type:str]
    version: 3.13.3
