apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-db-credentials.secret.yaml
  - immich-db-credentials.secret.yaml
  - nextcloud-db-credentials.secret.yaml
  - paperless-db-credentials.secret.yaml
  - goloom-db-credentials.secret.yaml
  - teslamate-db-credentials.secret.yaml
  - linkwarden-db-credentials.secret.yaml
  - tandoor-db-credentials.secret.yaml
patches:
  - target:
      kind: Secret
      name: authentik-db-credentials
    patch: |
      - op: replace
        path: /metadata/name
        value: homelab-postgres-authentik
      - op: replace
        path: /metadata/namespace
        value: authentik
  - target:
      kind: Secret
      name: immich-db-credentials
    patch: |
      - op: replace
        path: /metadata/name
        value: homelab-postgres-immich
      - op: replace
        path: /metadata/namespace
        value: immich
  - target:
      kind: Secret
      name: nextcloud-db-credentials
    patch: |
      - op: replace
        path: /metadata/name
        value: homelab-postgres-nextcloud
      - op: replace
        path: /metadata/namespace
        value: nextcloud
  - target:
      kind: Secret
      name: paperless-db-credentials
    patch: |
      - op: replace
        path: /metadata/name
        value: homelab-postgres-paperless
      - op: replace
        path: /metadata/namespace
        value: paperless-ngx
  - target:
      kind: Secret
      name: goloom-db-credentials
    patch: |
      - op: replace
        path: /metadata/name
        value: homelab-postgres-goloom
      - op: replace
        path: /metadata/namespace
        value: goloom
  - target:
      kind: Secret
      name: teslamate-db-credentials
    patch: |
      - op: replace
        path: /metadata/name
        value: homelab-postgres-teslamate
      - op: replace
        path: /metadata/namespace
        value: teslamate
  - target:
      kind: Secret
      name: linkwarden-db-credentials
    patch: |
      - op: replace
        path: /metadata/name
        value: homelab-postgres-linkwarden
      - op: replace
        path: /metadata/namespace
        value: linkwarden
  - target:
      kind: Secret
      name: tandoor-db-credentials
    patch: |
      - op: replace
        path: /metadata/name
        value: homelab-postgres-tandoor
      - op: replace
        path: /metadata/namespace
        value: tandoor
