apiVersion: v1
data:
    password: ENC[AES256_GCM,data:zChoBG8FpZRRdV4prEzXRIUWuEqGipRGFacAHv1u2w8oHj9rN7g50D9g1xqzdw0crq+A1O/b841+Sl2b,iv:S9QXajzGc6T2+pIn92GNh4Alccx28xK4egJ7hMxL47k=,tag:26t1nengqmA+e5DhDxALOA==,type:str]
    username: ENC[AES256_GCM,data:Ro/MWHFWa3hkF6pH,iv:spXOfcOKwJ70kNTyEd76ss6Kz2aO8at9i8+yQ4p2sT0=,tag:/W1FIoi27GO82CtZcT8gzA==,type:str]
kind: Secret
metadata:
    name: outline-db-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkb0ppMXBKNVI4RVhSUFZx
            ZWhOQnJTek5GbFpCRmlWZWh2WlZ0SDY2L3dNCnczY2RHV0k3cldkQUF2QmtWeURr
            aWRwQ0owUnB2cjdnUU5BU1NyNk5Od2cKLS0tIGdpeHYzajRFN1Qwd1Z1bXh3OFdB
            MGwxaTBjbDlsV0ZaQ3k1UUxBQlVVNDQK7wAFG+9CtSta8O+bLsnnsL9qBFLlW1ZS
            ZEapBsvYZJGSMPBUyJu0lgpbTDyNa0RqBW8aOHIoh5+310tlDh115w==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-05T22:55:04Z"
    mac: ENC[AES256_GCM,data:dwx4iZf4EJa/AUW6SpKnKBvXtzYx6AeuTa41WMxPUfx/r2WVwtUdfvAcZHlFyP8OWaP1oqTIaA1wUgiGLGTxhneWo5/TUQslMbjIEByXQWgktyBXafN5ZdwDCgP7NcgTIxSGjppaSNHaNk07F996PWKA7kuuoIFhT1WKgEhhATQ=,iv:5XzHhnR4OceLLc/eIWzEkd2R18bBx2s6jQBJDSYVrEg=,tag:oxFEHEbZGaQU/MTMpIZq2A==,type:str]
    version: 3.13.1
