apiVersion: v1
data:
    password: ENC[AES256_GCM,data:KtMcZUlor7O/Jea4BheXSLp7TIdmpwU9LrEmEyugIDU=,iv:TZ0Ai+6CRjATkjXJS/7WszdltSEJQeN0fsa/QfvAHTE=,tag:GaG0BmXpyMKROVTs8O9QSA==,type:str]
    username: ENC[AES256_GCM,data:obPnwDbtFY6aUqS3,iv:DBjecbafC/Vv2PHiqF/VjQ7aNgIoCffnpNnAa6cv8H0=,tag:qnx+/RVB65Jv6IoUG5udWg==,type:str]
kind: Secret
metadata:
    name: outline-db-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVFR2bFJKQ1pNVEM4S0ts
            K3Y5aGVpTjZVMTNDNDE5d1I1SStXbHFTdHl3ClRFT01Ma2dLRXNLMHhubWM2elJ0
            NS9pQkY4aENXbXRvRm9NSVlPOHZBVVUKLS0tIGZlVlZVVXJqb1k4ZTVqUlFDelhz
            a3lZa20wQ0FISWx2WEhsS1B1MHU4c1kKzk5YT/pSqI2hH5Dlo0QISTBfzZP99KDc
            RKwspEpuk6ZgNyj+fa7Qq6zUmviItCMYgfXZiyKxl1VxrmDHQsA5zQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T06:44:46Z"
    mac: ENC[AES256_GCM,data:mQt1Ir1/91dF4CIuGq/B1UHTrBBiWIWLQVIYQwajAJ7NT+bjfF3mSShJMzQDaCpJuQYEfsedQRfCGeSXgRxC/1+jKOqn1CJH/iAbWKvX4d8Ppvb6Sj/V05Cl14NiyZ4MtbvDm39JYRvtGwBfN0Y9labTnJCnVRily8o9DLDioSA=,iv:oyrfSpFy0DzvbZG9A2dDBHq7WV9tjYATj/h1toOT+KA=,tag:VngktQBPuMWt0+/WrwMC7w==,type:str]
    version: 3.13.1
