apiVersion: v1
data:
    password: ENC[AES256_GCM,data:MbkvWBSETp3uZeXLCxGcEpFxbFdCKWnR,iv:d+mm2mD8XIHSyHSbO76TkB3JByTovNBqN9O9YE2XGCo=,tag:egvRqzrX1vzYjkdU8SGNKA==,type:str]
    username: ENC[AES256_GCM,data:e6F82mDNK3G0JPr4+Ew23/0U1IcpsjK+,iv:piaCIvQNRvdLDpyOQffRInARbY3prILZwnIo7VXBAA0=,tag:vbTktKOx7JIfs3fB8b9euw==,type:str]
kind: Secret
metadata:
    name: sparkyfitness-app-db-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTVi9GVjFrc3JkWnJsRVM5
            c1pBRWJsRUxpOHJHKzV0K0NMNDV6Vnh5ZGtjCkR1Vkdrd2NVQ0JjbTROVkNoSFVm
            bng1ZnZsZ01VK244K1MxL2hFaVd6aFkKLS0tIGlBNis1L2RvUnlUQmxaUVVSOVJ6
            WFB4NUJ5eUtXNmhPL2tMNWRyNktWbW8K2q8S36jG5k02whUcG9KOTYYoY21qUBSx
            6LsaJBTL3V56GTHrIJLR7pd60aSLWqcJp8RkdGVxr8xCOZ/KQuHEzw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T20:20:33Z"
    mac: ENC[AES256_GCM,data:phFkeQNnTU2Rt2t7STc96OHbrnywJlOjE4h71SvrXf/EEGVGOeyccYR0FOGkw6ytxx7Mm4I8hFDSNPrdse3eNhm1lIbgN4FfU1c/36THxkIFaJKs6GOi9mCLrAQ3mWlLgfnCayw3g/9rdD6QP2XtGBspItSNt0uFKc31dBHnowk=,iv:JvneKB2I+0HkUb4eum5n+q042c5M3cP8WHw4w4gK+K4=,tag:JnHhGUavd+vzbUI8TX0MsA==,type:str]
    version: 3.13.1
