apiVersion: v1
data:
    password: ENC[AES256_GCM,data:PfPrmUCF2jQRIz8vASve47no9Qyd/VeSqAeSQZ49wO3t7u/9DySCHCsvKvQ=,iv:yMUdZZ5rX66XuyLZcXjKal7Gc+NCPKUQd20QHjzhWxw=,tag:h/+dlYFE3qTrdsPdbCvQ5A==,type:str]
    username: ENC[AES256_GCM,data:d5Pj4iU4ngMXJ+Wm,iv:NOslLieaEVDFvnePnNhn0mSAb3ynSHHts9d/I+j9eSw=,tag:okmialDSkf/KB6iFOYmPBw==,type:str]
kind: Secret
metadata:
    name: tandoor-db-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzc2VHUXNWb1hwcFVRbHZE
            RnNMbzVYc0FBQ1BoUGJoMnA2QTBkcW8zZUhJCithSjVuOHdTcnU3aVltQmd3WVAw
            eEIwc2wrckVMM0V5amtqVlhhQmRPaDAKLS0tIERDVEtnSGd6R2IzbVRmcitCS1dG
            Z3FQbkk1ek9Gd3MxNndmOE5yQVZWUUUKBj/li9CXF2xw/GxHD9h3i5EewDKnENgh
            K0f2bsY42BQrZSwL/jaSanFexWBvVaBdH+cJjO7qEqPEvRPov9Ye8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:58:35Z"
    mac: ENC[AES256_GCM,data:uWy+jFof6XxF6Cp2rONlTG3m29aVP2HxdLXWbMwnBEZMbdirVyuLA3xcDGrIWKKB9GnBFdIu7tObmmTERUH5+NOALdrGnYP99E6WL2NIkpW+c5OlqZ79sOhFJQaQ8UyRo1iSSILee+7MO35wj49E7RSCHXWzCAmDnoIbgBjvl6M=,iv:qDDuiqldHbTHfySZgzyULXE78lG91ULIB4y5OzDQ3wk=,tag:RIaUFprXK2OkOPA+SN0yFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
