apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ytvtUbzSFCjktFIkVqcyZGzNPsYG7OlLc36nL2crpHEAa202Dtja6B9ZMSo=,iv:33/MpjS/K1aVH6/873LAWvmTcyYZqV/Y7rws+BETYbk=,tag:mdI78+JBSSDlX3cmiS5qUQ==,type:str]
    username: ENC[AES256_GCM,data:nQykuMBeLYiB1I7K,iv:VWB5T3w4nGz546wOsACn3Lhps+nWPEsQhrkle9bBG+M=,tag:u1TvcKgNenq5n3LzhNNjdg==,type:str]
kind: Secret
metadata:
    name: teslamate-db-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: REMOVED_BY_HISTORY_REWRITE
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMTV6cEdqZmhxOHJsU0Zo
            bmxPc0ZMUDYzM0xEcm5WWEY3WTRtYmdJdHlVCjF5YzFhVGpDdWhmVlRmWXNwNUNV
            NXhwbFYyMElodU1SNlJHbndlZWZxSzgKLS0tIGcvdkVsVVc4V2RrQnpJdDEvWldy
            RVhObmUySVh2eTQ4WVZnQTVNWkk0VEUKqBTcNsZCFg0ljFW2DctjZbKQTsaf62N+
            AVRE/kudTBkQuOmfVPh2t3Gzn9mB+V3vHFTBXHi19MWAzJdKZYcL0A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:58:35Z"
    mac: ENC[AES256_GCM,data:QBdMhG7Ox+hHZo/GGollQsULm3QvzSxLtUORrImv1+Ex3BVondUuYDA6/fVn3kvs8p+FhLX/moh0prtK4DRTiO5Uv7cp9/AG4Y2N6OXTi19XQCgDJPR35cpfmMQcoQIW7VlbKeRZUrHxRhyh4BQlGg4G3OgN2F5CBDbzLacqAvo=,iv:TQNZrBJ9y+z/GW70i244+ZHZ2bLXN6U+ZkMBzHKa8JE=,tag:2hoG+roC3498X36DHbFVHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
