apiVersion: v1
data:
    username: ENC[AES256_GCM,data:BOgMBzEJZ2TQeJKB,iv:9g5ZiMpB79Rm3W8WHV+yYtHSPNXlPhPSFKb2rp5g8GI=,tag:4Pfx+vpmSeHJOlRZO93vpg==,type:str]
    password: ENC[AES256_GCM,data:sh3hv30FfpwXz4kvIqrKvpdiU00fowMmErdg9TurajJz9mW2fs00F+h/Q+/4Tzcql4op85h0KwDxXuTK,iv:SLQzP3x1b+OSIQ3x+mFx3+KgX+7CcBmpYtWNR0FMmwQ=,tag:oA0Q2inQ16PDdQbcacUw5w==,type:str]
kind: Secret
metadata:
    name: vikunja-db-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2bWFyaGtmbjJJdTBkNktG
            UDNiaUd6N01ac2ZCL0tjOUY5OHEvcmR0S3owCjZKMlFtT1NxbE96ZXJWZ3daWmRT
            Tm1UbzVQT0lPL0Nia0wwL1A1MFFMbEEKLS0tIHN3eTQxUmdCYnpOQUFvUkNBMHJv
            andJMThrVFlKTHlXY0dQT1FoZklLZUkKbCBAcyebeRP1SHw5cAoJGXKZiLJ5usL/
            7aWJJIWOEEJnnj7RusrZdJLb99u5MzK3NNM7sg/3/WJgcqwOrbOfBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T13:14:06Z"
    mac: ENC[AES256_GCM,data:GAPa45Ja/Bjupo3+XFrmlXEf/8WtvjVt72NG7VJjacOgdW4hARD+CK2PS/CxeDEaYALEeHQWOF6Nf6CfuPM7gqjiCgMnevTzrvQ+XkyzcnmKoDMlvRW4Td5PlSj4UUFuewFHTfanDARiISCVPK+cOkgzY4o6ijt0Ys/Yp0PuteY=,iv:nW0cujSO2nm1qwo6s0gdap7SAJgjf0tffVjnvs6EpKI=,tag:u7AN8k48uUIav/FrrMX6/w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
