apiVersion: v1
data:
    password: ENC[AES256_GCM,data:/yCVO81Qv8z5ciz4wjww0jzL2nHh7A1p7pW74UV8n+VeEnRhQ7OZucJZBm8=,iv:St3sZv6PjtYKXL9CHsAaAYm1Qr1v/1GA9i3gS7brECQ=,tag:4zZ84fLcGYLdTtM/u72cGw==,type:str]
    username: ENC[AES256_GCM,data:AdcXwpIRSQzH3hhY,iv:X6Jv37nmrRH2+KAtjl/J7mNt3cmMQxVmn37+ksV+6yw=,tag:yY84w0R5+eIuZZ9tHdJY4g==,type:str]
kind: Secret
metadata:
    name: authentik-db-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNL0piYnYxMVdTUW5RcVpM
            Uk02WVgwUEZRaEI1Mk9RMWxuSUFWZ28wZGo0Cm92U2VveGlnWitKdWJlSUc3MHl4
            S3p4UzVUL1lZU2o3djArbHgyUjNhQ28KLS0tIDVZUTZkLzVFdkFIamp5V1l2YkpG
            Z1BCNWwwK0ZZaHl6U2M3NzhUZHlOUDAKqU5RdvLO3r7xaFGEENmKTUe5uSZXlac4
            posyR99ujss2UReDeWlAiLk+XpbXU7nMhnQx7K4FkSrzmyZKoTy0hg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:58:35Z"
    mac: ENC[AES256_GCM,data:vf+k1pu02qalk8Z/v9jHU+t6rPk/GjUCYfW5SosgmthzK4SCexVCW4CG8upNp1RerJNWshLeocbdUsWqdm4iww50InBsh2voxzQkvy8uve5oBkoadccU8h+sbLLUoL7dppZWWRrwYJSpdtVFWHFwl5qKYinsx6iDsjVIL0ZCxIE=,iv:ZRkTQ7HxrdYanMYD+IFDiabFQSHPPivuR/fiMi19W10=,tag:RoMPG5n3z1MZh9s4MPjUQg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
