apiVersion: v1
data:
    password: ENC[AES256_GCM,data:wEko6cnRTbn05VeoAq/QJDojr1d6ONZssoujy3/H4fiEa1Vh/8kodF48nDY=,iv:AY6Z09I3++O8NTLPKsllL5ZopBJzSdi+8KsH4pnXFa0=,tag:nYQkeMqAygEKODeg8MOkHg==,type:str]
    username: ENC[AES256_GCM,data:HTj/+KKlWqU=,iv:Ex/q01j38O73XhMzotTYb4bPiZcBDJDBGMsFUnXcfIg=,tag:4gMzf6Gyt7H2E3kkqNTArA==,type:str]
kind: Secret
metadata:
    name: goloom-db-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUklTeWF5UGJqWFJWdEo4
            TXJwaDhCZlM3emRPTmZteVNVbDlET240M2hNCkx5MjIxbjVMV0NrSlF2WVpqRFYw
            a0l3NmhjellxWFFrZjZZcmcvcXc1ZFUKLS0tIFB6NEp3L2ljQjQ3YlhZNmNIQmdQ
            RWI0WWxyVTRQUTNqMlAzQm4vK2R4d3MKDX8E7QfXE9PIhFTOLQN8cwIiK6Twa4jU
            30y7nOCyYA7erCJ0ru9wsAHKYeLnxyUtthJN7KB9/HKKY1DCCGu9+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T23:34:53Z"
    mac: ENC[AES256_GCM,data:qJFIZncVIpCP3wI9WIoww/AH28yUcvPl8juA1dcjYk/abkRTtaabyCfP0+vqCSUrwE2MQFiwenKcXCc3jSqHCXsbvEWmHLg4vcNbl4+OT6h16QHncQvk3AAPbPkMrLuvmTtnzePYGbU/a5Zx0XSRwqZ6sfw639I3N5tJmmN3WMo=,iv:Hs/r9Stkx0Tp892rNb33C+Sm39sXtQoz4VFm3OVTePM=,tag:FNls4QjEbs0tl+1sOuE+6w==,type:str]
    version: 3.13.0
