apiVersion: v1
data:
    password: ENC[AES256_GCM,data:LAUsUyzhmTfUGKyaBhCS0/1qeiMFUyyBLIoIcQ+6LuYqsTbyN2hJRJ99UsI=,iv:CCY/uUr6CJdTGVPmjCoMRwiG4KtcblDVdjbSo+lwE+E=,tag:7uF/Mfg6HB27uwsbG8n9fw==,type:str]
    username: ENC[AES256_GCM,data:0i/FELfSnWg=,iv:pCm3uRUMjeYZm2TyQ0kwkITO/oWUD/6utGmsxms3MAo=,tag:oIc7Ayv+y7bzOlkpIJxKzQ==,type:str]
kind: Secret
metadata:
    name: hister-db-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArS1Y1SHh0dmZZTEpMYm9O
            bVROMHBXYzNNaGtuRWFRcjl5TVBKOWxBMUJJCmFZSHBoZ3Y1d0NZS2Y2alVkWnd6
            VURHb3EyS01MNjlwbytveUQwSWNxaHcKLS0tIDFHLys2MVM5N2d3T2d3b2d2TXF0
            NHdZNVFEZ0pweVJKeHBpaUVHWjdLNU0KzSYQX0bFCRm8m8lNekIwxf/FD27uhPIi
            y1EL/SUvQHTK2lwBJad/sMxEoYRSlsYTW4iNW82K29IMib2uSXJPTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-26T10:41:43Z"
    mac: ENC[AES256_GCM,data:Ez43mkqr+HM/pTHuKR9GuCy6vMB/KxH8iEWC4XdCTZwDJ+kp4haBFhso1NtFPW4wTLMLHoPqLixvnQaTdOD9Ndh64lUa8Gh0l3ojuFpsiyGSK3B7BMeR3cGdjXWTyDxA6a+i1hIsPXPmFVIsr8TyG7w571/jjYx6+/aeOwspqUw=,iv:ga+zCIQ8LVlS3ePidqGlJIqCA1t2wY0fg8S9zQn4z4o=,tag:lwjaQicaz6a5wLb5UorvOw==,type:str]
    version: 3.13.3
