apiVersion: v1
data:
    password: ENC[AES256_GCM,data:ubemn/vqK5BdYKfj6OF8Oi0m0P3WGivUgyPSwBXd8lDSiShzUGo+EdkB6wk=,iv:BGHPmIPWGSvydgM9sIz08FERsbCgp14Ik5eFQz/3M10=,tag:cQqDYKeo9c4MAIFzHZA9YQ==,type:str]
    username: ENC[AES256_GCM,data:OW+HNq97gA0=,iv:vuWTpAK5YP2GdGfVrUqNx2JiivuLnJFAqVJGBgq9Q3o=,tag:MuB4hzWI4Cg9IRRuWK37Rw==,type:str]
kind: Secret
metadata:
    name: immich-db-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHaXFFbFpzS3huYWxsc3gx
            eFFYSGIzSUVkUCtGZjdNS3FRWFE5NFMwdUNNCkhMUVJ3Zis2bHZQMGdSNDVqT2t4
            K2JUbGtQMUZ0enVEZTdFNVk2dzhFOU0KLS0tIE9PQjU1TWZodGVuMjVnQ0REZUU4
            OEhwK0hBVm5hbmY1Z2paOW0zUFVXNE0KgFsG89bahsHMsRF1aiNlDYYnSsu7U2rX
            i8pBkfeoFC4aXV5QZdcyB/wW0DLGHSObn4b+YEYbEwXYqz5gWxelTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:58:35Z"
    mac: ENC[AES256_GCM,data:QANZgTDeNJ8EXbSDaJ4rghYA4bEi1sOu7QQfJRui9k0pn2doH5N5nZ919nMGYJNy480C+aMN89DE6fJN3Tb5TFTOlATPLmz6+HLtn6zAiB27iUrKEb/Bzs+W3cuqjbf2PtWb5uAApsyG64BzMgYRvOcWquesrCmJ/r0C6Bpy+DA=,iv:P+QZwZ81+hbtkYkI+w6GfmlfnBer9i18M2VDkZ04vwk=,tag:9LKXgCTByBO4EH4HwSmDrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
