apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-db-credentials.secret.yaml
  - immich-db-credentials.secret.yaml
  - paperless-db-credentials.secret.yaml
  - tandoor-db-credentials.secret.yaml
  - nextcloud-db-credentials.secret.yaml
  - linkwarden-db-credentials.secret.yaml
  - teslamate-db-credentials.secret.yaml
