apiVersion: v1
data:
    password: ENC[AES256_GCM,data:DgMpwEfXVGCaJNSCx48eYgJQghT2TrVakjxbLDBfZ2kiJ+XdjI6jeYihBMA=,iv:eaKscs3rn2rhHIB77tpddvmwhal/gx5Lvlz3e/eIuq4=,tag:ZsxvcAZ/Ob/ziik4Dpkt9Q==,type:str]
    username: ENC[AES256_GCM,data:UngS4qOpFJQVf3LkOdUlOg==,iv:+AlD0JAy+nhXy0jzVWJnrcIHpFFDG9zyAdOqzlfzfxA=,tag:HtIs5ok7DXATSLvPKRcPZw==,type:str]
kind: Secret
metadata:
    name: linkwarden-db-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: REMOVED_BY_HISTORY_REWRITE
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1azROMXo2WXZVUTBWbUdn
            MWo3ckpybWlLWTlMM3Y4M3VKamc1bFlDekhJCm9Ed0l1aE15NktBemZHTE9Ed0Ru
            M0FRT2JLT2hOd3N6akg3Nlo1RjcvT1kKLS0tIEVaemV0aGduK3V2dFczOFR6TzdV
            NmM4RWxtS2crWFZBOWpST2ltNjBRanMKTaowUsksAObl0ZnrL3kBv91QXd8jOlz7
            TxIsl8se8+fSFIQ9CcaEvyfTGpmeyL4l2UKA06qkGFDFmFyqn7kcJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:58:35Z"
    mac: ENC[AES256_GCM,data:URDs091jF/EQw+LnRmK1i9CiUPH3fVBOL1YkTwhMmHDPCq2G/y768ufo8EYctLT0Gsi2gbe9cv+9cz+HVm5yhpRoEDwtV1LxAmQGDrEKYh7nlKpmBTuR85jP3+X1URI62vd6SFCnAGYaLNlhVrdlec84D/YZfK3Ntd98F4MVOUg=,iv:NwuKUfe0EbfOJuWlx1lGLVj2mvwUfkAm3lSELLW0tCE=,tag:XhQfuR5J1JoTu4IJP7rvCQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
