apiVersion: v1
data:
    password: ENC[AES256_GCM,data:8t9j1e3qh5td/thJa7g/FmzS35RbB8OWlMz4Gq+DPu17S/iMuLt410RX05E=,iv:VRbtbvC51xenjeTqHKcixHTY1DZaHoHurAFiNblMebo=,tag:A7lQFo52HRY6YYSlVb0b7A==,type:str]
    username: ENC[AES256_GCM,data:tKpUIFTz+XlW3mHd,iv:ezieS66HLq2hhKdOtWQltuJLowM8fYFf0L2O783Rykg=,tag:JycQSZg5QwxoTsvMYIICqA==,type:str]
kind: Secret
metadata:
    name: nextcloud-db-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: REMOVED_BY_HISTORY_REWRITE
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUlJ5bUpHa1l3M3JKWHR3
            WTVuM1F2c3djQXpsQjhhckphWnpzTE1MdlFvCk1jYlV4YUxzNXpZV2RqV090QkJL
            WUtJUXVkdlV1TDljVU9tVDFWNGVpTHcKLS0tIEFMazBaZCtJN1RJYkswTFY5SXpI
            akhXZnNuWHpZMnZJY29ZdVNiSTA0am8K84ONaAbQQSFBoJYaDKzYA4Gfo/fa2QEF
            78Oa6CI4q/JbWWkSY2anjztI4H5IoZ3nbeEhx84oPlpH9TrkApbPYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T19:58:35Z"
    mac: ENC[AES256_GCM,data:g/F+Wnu9F2JpXNseu4lrvyYTJmk9tMAGiRnwngZgMdqDFiIa/iOm4J+l2r0/dkESyVCIk2hSHYOIrgGLcP3LbWECNF/2ko0sONNEZdmnKx8vLLAx41a+ahu6Pp0IL8iFZfyAe9UuEaGLSbJyQV3dC4rCAZq70kjo0q3fEsJMWxs=,iv:RNSuObJ+jdvZj9j5M7K9afeZKhAGwHIpLpDhQL7UMxY=,tag:wGhUlQ2Y8wuro57N/LNMdg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
