apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Xi3DaW68lbAM0dp/PCUY9CM1g823Rk++3zXrGImb8gI=,iv:0FsGvvxxR/qdTHi3sO8gqeeUPGTAMtteOxThCtLRYYo=,tag:xv5ouzyWN8WwVoGljHzNTg==,type:str]
    username: ENC[AES256_GCM,data:KktY+RiET0CoWRy/,iv:4u7IkU2JabuGZ0sq2Pc0WGbpEXPceKjv1nCk0lH2aI0=,tag:DOqtHr84kFcqxKjfWkTbTQ==,type:str]
kind: Secret
metadata:
    name: outline-db-credentials
    namespace: cnpg-system
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRis0OTdZVTBuV1EwNGdt
            ZkQ2R0ViUHdpTTNXUEZDWDMrZkxtdlZ5Sm4wCnBZcVVBTk5tbmh3ZlVUZDhteGZO
            SmJrNjM1VkNqRzdidHRDSzVmcXMxOFUKLS0tICswR21jTkRXRCs5RnlSYzQ5NWoy
            dG5xZkFOQVZTWTFNS29QNExMekk2WjgKv6BzOkEcombJrHmnKPMv2B500pdG9VqP
            UCAK+jIoEkFpvfE17hC1Vded/ZELxqZkHRyL6Dk1diATR6OwcF3wFg==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T06:43:07Z"
    mac: ENC[AES256_GCM,data:WAwhuf9ACtZoZ+mznBgel5OQHJtZqbdbLhUQiIFpN+A9XWGAn2Y69MPy6gkKs/Jml92Y2bY655ysM3K07x5ZjIT+aFr2GUpV0zUIiryU4qV+8QUj23zOUBLQKpFExlH6MJI7ISIqlg1/J+3IpQ62NkCYIu4pjJ75myObhNkU/fU=,iv:TJrOVOHhMSazQzVI6SlfYRhHM8KqdJ7OT4+iiKTgrZg=,tag:dmFLztJbZDVVxDiBSmOIUw==,type:str]
    version: 3.13.1
