apiVersion: v1
data:
    username: ENC[AES256_GCM,data:QZWxfDcwcpPPhBob,iv:CyYQTq8i7LyH2T+dYU37X12y84i8+Iiy5of80iu1lQU=,tag:JycCh8mxQqrkakl5yuzX/w==,type:str]
    password: ENC[AES256_GCM,data:9I08eteuliIduA26fwHzsZ1KZbSdt3DyaMb7B/hELHv11HGx823wQdXLSSXCqMXJDQHFDzWyXDKZ+56O,iv:ydhdcCUnOywkCYt3EOst9U+g5EGYfsLO0x9VpswOotk=,tag:dEyKdoZyY7g77SrQ6zvuCQ==,type:str]
kind: Secret
metadata:
    name: vikunja-db-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bnRON0xFNFhZdHlMTVUy
            OFVTZU9VbktQeWt1RW1mTnpQYndOQ3kxbXd3Ck5iVWNLc09waDFVaTNCMU9ocElL
            UlhhUHBhcmp1WlREVEZqNVczWnBMZjAKLS0tIGpVTG5iK1NnN3VZSEhOOUlCcVZK
            YS9IYW9YbUxiRi90Y2RGYlZHWHI2NlkKt+/6YVbxw/zQj5+jsXxTsexMAk0wVWNZ
            IxTmKdUAQJf6MMj6yOd8Qjo0M0GzIEO2XSXDRqy/1PAM9fRudfMH9w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-10-01T13:14:06Z"
    mac: ENC[AES256_GCM,data:RBT1NDy5PR68AaOmtLnLJr3md8nXUBwiuOUx+LqbU3ViZzuHivPueveDejMWzU9qkNzlEzT6nwz8OjEldQ8KWGEdIO7pRqoB963Q4gNSg+WkVJ374adLPl6PwKjm6LJJQibrJ/oMwbreV0KlRMVRPh+weRmaJbAxNuECiAjTHqM=,iv:AR4Gk+39TeZIhwKW0ZAyXKBzUlQcuD+mgDW+MJ17e0k=,tag:YUYhCu74Uj7RW0XYalMkLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
