apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-audiobookshelf-config
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-audiobookshelf-metadata
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-audiobooks
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-audiobookshelf-audiobooks
  resources:
    requests:
      storage: 2Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-podcasts
  namespace: audiobookshelf
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-audiobookshelf-podcasts
  resources:
    requests:
      storage: 2Ti
