apiVersion: v1
kind: Namespace
metadata:
  name: unifi-controller
  labels:
    app.kubernetes.io/name: unifi-controller
    app.kubernetes.io/part-of: homelab-apps
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
