apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-config
  namespace: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-mongo-data
  namespace: unifi-controller
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 20Gi
