apiVersion: v1
data:
    MONGO_INITDB_ROOT_PASSWORD: ENC[AES256_GCM,data:KEIFSIbc1tBqlDuJmquPRxWtAZfAA5PT2TDe4mEikQ0e6enGpO9Kia1ptuY=,iv:xxP0WzrM2fvw3H5SJx3CUiIlsGVe51YmWD0CbLOw/Fk=,tag:wip/IGhVfB+aTK2CbBZE1w==,type:str]
    MONGO_PASS: ENC[AES256_GCM,data:wGBoNrJM8B3YdufpaBsh5J5TSXQXkZPFGS+fDw6Z/sjjCfMgc+8GaEPvusM=,iv:Mdi1v1pjsUG90q/sf4raow6Xu3xW2RtbnroGACYpCKg=,tag:dYZCt9PUrgyJnV2xpstPDA==,type:str]
    MONGO_USER: ENC[AES256_GCM,data:BxVB+X1B4qE=,iv:CdWNqz9rSplkVktAZ0kip4hj1c27KTpgAHcsKQxeKw4=,tag:0gXISFKzCqKDm0wsG8/sqg==,type:str]
kind: Secret
metadata:
    name: unifi-app
    namespace: unifi-controller
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBER1dYMDVHczh5a0NqaTd2
            ZDhsaW1vY3VUb21FYU9WVkcrRzV0NENRS2pvCi9WcTJjZzVnMy8yM3YyRzBLZXhG
            L1hzSFIwTlhQbUZCa2ZRbkRISmxmZmcKLS0tIFhmUnMwQlhUOVExRUlCa01IK1pl
            VkVub1BaRjZtbjgxRUdWM0pvakN4WlkKw9dXn7m+bgqAVvWYUznDVJ07PRjJSqcG
            hjmcDdXelFKl5TzBu2/Dq1ismDhIYKVgFETF1mVopAsTnUeotZ5Szg==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T07:08:54Z"
    mac: ENC[AES256_GCM,data:dEgg/4c7XedM6gwkYnXEVYp23nF7F1wcGMDTZqrSP6a9oREaInE34WEPY6Het+4dhatlP/HB8oxU4yB79jXFGmlJeZpxTobPwaG72F+Y97PKdnYz4/ZJVEOTdoSwxPgaN3DAfjiAklCF7e6o/sKtLhyUWt6FvyTqmZUcUAgIe2Q=,iv:FEnRQb+Js79MHDGrwhZUg4R0yLAPa0PM99P8cu9/VWc=,tag:oxdmZRaGDWsk6pWR1TVLew==,type:str]
    version: 3.13.1
