apiVersion: v1
data:
    setup-key: ENC[AES256_GCM,data:eMTMLO3LkqTZ2iMs9b6Hh0TAPUqObDWGU0Ip7dbLeXkqlY2vyMXHlk2igpfHqC4j,iv:buoX8Mvj7x5HNBIacBfEqujcugHiwdiNAlaTa6rW1tw=,tag:wRUTH8lu+uw75mIur/JO1w==,type:str]
kind: Secret
metadata:
    name: netbird-setup
    namespace: netbird
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaV280dW0wRHhXRVRQUDlW
            NEV4VU1HQ3U2MUkrb1hVRlpqeTdudmxMaEFnCjBwUytoTWlNMXl6TEozOGpnWEcz
            cWFjN3BzbC9Jbjkyc0FEYU9NTkQ2MjgKLS0tIHNLeW5jMElEOHJmVithSkd4WUNx
            bWpmNk4vZXFza3RXdUNwd0NtN2MwZ28KslJvQH/ca1xgS+ouk6WoZpeOeslxKI4J
            O80DV0sC1XC5CrXSGrQ1GTC8isE3d8WQf+SsdKNXowmfjnPJ0C5w5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T08:49:41Z"
    mac: ENC[AES256_GCM,data:0Cx4Op90ms7X2jAWWkieEXD17p/SqY+XRNZ3PguOiETH1lSf0X5YCOhYcFevNwnroFIXLXquSl8QKnrcticmtH7TO7jfcji8aXEjnALqmSPv+PRXIWCrfkfWmlB88tMS4f/gVqFaXEJSlExFBp+n3+/kbPPLQSu71Z6fS8+1Qpw=,iv:nJl/BrRajnFXtxWK8Y5ubeMe+Yl+vtv8HHWtRPcYHOI=,tag:d7x6bv/2xG3u9w0Sv15SGg==,type:str]
    version: 3.13.0
