apiVersion: v1
data:
    setup-key: ENC[AES256_GCM,data:M4Adjz1HpilV27/wdF4SMj34QqQ1ULszg6gSRyfsiTe3eDdkvo6ybyDLTSu0FArL,iv:s4laMVtfqEetiXioBWYWBKpr36IZ5PsezpNI241r/gI=,tag:3wfX9AjC73usLzPMNvUCNw==,type:str]
kind: Secret
metadata:
    name: netbird-setup
    namespace: netbird
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3QVZnN1Zib05KMmd6K1BN
            L1ZpbWFoM2krSWUxM1RQeWFOREJuUDN2eVZZCnRvOFVFYm1pNFhUR2I2L1JVaWxV
            SHpCaHMzWEZuczE3a1ZlUmhXai9zZHMKLS0tIDVSMThHS01BR0x1a3lLWll1Sytv
            Q1g5cE9JUUhuUERSRU1hV2Q4MTRBTUUKUy3uFWnuKqaybwdXVdp/0GYWOSH7FJxo
            RGo9DyHJpOxXOov2KKjMml9EcFv26vYA6MOBSwWXGTKOJgB3oQRAiw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T08:29:00Z"
    mac: ENC[AES256_GCM,data:x0nqR0J6b0GVBoa4MF1hDvtoFsi2f7iopVj3uokaJP/oCbUp+L22yme9P/EStm/NjykaVTrEoUkXjWNjoNgXYh9UerEFJtPADzYLUBj7nB5xx6eWTXeIHJ/eJjCs8zugW6hlO3tEabCfgo1iOB+swaZN6TDF9aCSaFkZedBBZf0=,iv:K6Rb1JoYyJxA5it3TiH+mj293E2p8ADVUZe9Yamr0hU=,tag:QBpm4rtgVUlai7HVi/UZfg==,type:str]
    version: 3.13.0
