apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - teslamate-app.secret.yaml
  - mosquitto.yaml
  - deployment.yaml
  - deployment-grafana.yaml
  - service.yaml
  - service-grafana.yaml
  - ingress.yaml
  - ingress-grafana.yaml
