apiVersion: v1
data:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:U5k6hstleOtfXjh61/YeJGPkL4JmrSbloSQlJGZkckkoui1Y/RJVoygPyDAeC8B8v5bj/2bACMmqRuGL8iUKnKFSMwikGlWjr/xm4xvuOaTVxGPO4qBBZA==,iv:4rTqtSXXFM9MCw8GYS9RXDRrtz32Iqnj5HZT1KsgNi4=,tag:EtUhPIdWXzW23m2FUa7CuA==,type:str]
kind: Secret
metadata:
    name: teslamate-app
    namespace: teslamate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMk5pUVdVNmhLQVZ1M0dm
            YncrckxtRDlyZ0Mxdm9RTHBMeWRNNzVuTGhrCmcwSU5Mc0xsVU5DV2E1SnlQa3pF
            UlBCam5XNlBpeDF0RVJ4OUk4b3lrS1EKLS0tIEo3NFpWejc1cmJsUGRWY3I3VGNl
            WEpLc20yaFZvYnRhcHdTUnQrZEo2UTgKjFhgF5kofshzgWt9Fl5rs+DPxErPDQtR
            5n0F3KnddhVCDpUoK+5L3OTniHhQcHMYmoDODRRzmU+ZIeHCULDhtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T08:14:47Z"
    mac: ENC[AES256_GCM,data:WG4wcDc26Kwrrv2JD2HLY2kSK1mUX+4IZ9V8K1Wf/uwIlmrE5Zjixn9ShfwgBmZkCgA8GtTe5fd3g250g956TDpSOfOSGrlLbkeIQ3kkP5dlczlKlj8VdHw++t6Cu0RJLFgwnGaUV61+Vytw6AenWeZHWuCM0GiAkItD6KA2GdA=,iv:f3eHRiqWVAl7JluypwDDv0WiLVvdUuGArkChKDFYq1A=,tag:XcvvwMLDBArzT1lOns1+Aw==,type:str]
    version: 3.13.1
