apiVersion: v1
data:
    ENCRYPTION_KEY: ENC[AES256_GCM,data:FAPQEb+HaAEiiXWgXfxVvZyfyuB6zWEkztWwbrTaW/mB1C+ROGHPDb3F+kT0hkoDzdqt2YATK2ZCBjf2horc7p+9pF/Xw8d/Nugox/eB1lkR6Vmv/fnr3Q==,iv:18oP6KLVrw+j17aw4ynvbu9x8KLbR2RUMeIlKL6YDYs=,tag:FiQgNQOGl1xwB5Kx8CTaCQ==,type:str]
kind: Secret
metadata:
    name: teslamate-app
    namespace: teslamate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbEtVQnh6N1R5OHV0OUM0
            TmM0ZWhMNC9rNUgwTlNscTQ5S2dtRFlYZ1NjCjRpNzJwUmN4dWdFRlRGaFNIb0tm
            K2ZEb2pucDhQRnFDMDQ3RVNTRERpWG8KLS0tIHFvQjRnMGtEM2xtTTVCMjVoSUZR
            dFpQL0lPM3lXZGNLTHBmOW9OQlVGNmcKMEUXuMaW61CqAuBSvW5n7mtmF4RX0Dxs
            EFIbVCVVjggv+FZ7SQBP22lBZ+zogmcPkYPxRpMT5qmrfiHWBgmsXw==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T07:03:10Z"
    mac: ENC[AES256_GCM,data:GWbviaOUGGHMiz6oGfq0odGW1dYU/oBW1z20EHJeT6gsGFYw151qTRPCf/3tHTB/WjdSfRZHQPBkSON8oY8Z+QqN2DTmkIy1gN90jipatCRe7hi/tDmNLSCeQbZKeA8q+9h1LDRnXPi79C04me6BihIPEE5g5Cho88IX1LRYbfY=,iv:NngbIUnDY6dNsAMMvEzAKd4398DefLzAlWJ2z+C4h5Y=,tag:e871QdXYGeCr+HYxIZKVUg==,type:str]
    version: 3.13.0
