apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:FiEcQge+oSXu8kzJZP6L7G1t4KuyDPZShMyNLrvmHSp+IL8e5DX/IPXF4okNSSiPBvW3qRTtc3c=,iv:AbHnu7dVMh6yif9vXBv6kVnTNi9o93pA/Qo28DcINs4=,tag:QcjbnpJoCk7syRVc+lyJ6w==,type:str]
    client-secret: ENC[AES256_GCM,data:7D+xYCUinfsGrivLqiQ+3+cpi5wc3hK083Oj9xfFMqFY5+60xRZ0UwYlNBvkF6AkyFbpOPtsyV5Msqk+9RfALhJ/FCDf4T3U0pBJM2+3JnVfbcMyk+wS37loG8Ro41ky77fUHn4RuG3R7XiV37vx9MCPMaabgSYPmZZQk3ltB4KVkamq2AMhsIv6o8dJwm2T+1y0p8ULHQVquB9IDm3bzaTChPmofriZCcVhAA==,iv:hxYD+KNKpvU40kPEAReDshzyewmlaha/oHbNx/QqtLI=,tag:6lI1w/1N6ETm5YRRky0cDQ==,type:str]
kind: Secret
metadata:
    name: teslamate-grafana-oauth
    namespace: teslamate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMVkwNWNPb2R1d0ZUamJ5
            WDBOVzI3Y1BUK0loRmNzNWdNbERKbFhmNGlRCmNvaTlZenhwZkdCdmtVNG1lQktF
            Q2tVV2k0QzFTZVVpR1dOZzk0VGJxUTAKLS0tIDJGYjh3L0pST1EzOUV2MjZtcDFP
            cjViREprUVo2VUR3VHJTZzlxY3ZnSVkKfj1JZGxG8z84Jz3Fjxd6EQjq3AYBU/LR
            nZOLThqddABTy5urhCgrRnrsgeOu2v3uHd/08JjA0r35k6yxT09Row==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-23T08:14:16Z"
    mac: ENC[AES256_GCM,data:PMsWarSYianTYXbjpwz0HmU5DpSvRyN3dBjTlFBkAknNUhDMklK/x2AZT5F0h30/zBWsEyKw7bDs553hWbmFX6EdXPaVBeMzY6e5QkkZQvVwf3tsxfOP3VTjxJDlT4kBgWzBpdheJi58g6BlLk8myaj1YhoF4LtjhyiS3D6Za1o=,iv:SyTmx1CMdmjfzRCo5KgG/cmTMf0aWbkrrRCesDZ064c=,tag:6zv27LkLuGgg/rEx+GLb+w==,type:str]
    version: 3.13.1
