apiVersion: v1
data:
    url: ENC[AES256_GCM,data:Pg1TNEyW5WUpqHDycVKzx6fu02/C+l8IR2OAApg/ABsFd/i/hDbUWgOPjzmTNQnmSQh66BGWDTv15CZva7G9xTdgVq9t1u3Cy2ACI/bxcYXEDjZwE6RL0nuCT5IZeif1Bkz+rHEto3Xu6R47rS1/xuHPalkJtNJXa3vvQXa6YXM+06az,iv:IWzbKhQquqiu9EQbFwUBIiI3UkRJ+vgxXQPy+u/ULvQ=,tag:wLhs+8uYkUbIqkjlke7Epw==,type:str]
kind: Secret
metadata:
    name: alertmanager-n8n-webhook
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6SlZqUm1zcVdYeEQyQUdZ
            aUdnQkJNcnJDSDY1Y0plOVE2VnNxeVVRQ0JnCkI5NEpIUEFDL0lGM1NNd0RhaVBS
            V3BGRTVLS2I1QnpFc3Z0L0QxdzNMcEUKLS0tIGNyR0JXSENlYW9wVG5lSUFHT0p1
            VDNWb2p1eFo5aGdYbmppWU84QnYwNm8K5rYZJFcCNFfw05BQkD76jeATN/CUe0wN
            Fo/6S+9TA5A1RyNExNdKhIoTrIfWlPSXywu9CJwihJGqs7Ws+IB2uQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T17:53:15Z"
    mac: ENC[AES256_GCM,data:sqjJoaZlVqWgxWeapuANSmR2aSdmqxH/qHvcjh8FmhmDEY0Hu4DX9P4/JYr53H+37JlA5smwI2XWHqzTWkYOpRVMseVPUeFIY4mmQqpf/ydjT6V1ysrUKAUxvWYrNvMCNL7eMkGtxULA7zmShhoUIX3VPyFyEMdtWZ+XIwA11WI=,iv:068wIce1q1FfzPjGSQ+7kN+FocVM76arSW8uS2RZp3M=,tag:BiPd7Xvzb1JajouVhz1mvg==,type:str]
    version: 3.13.1
