apiVersion: v1
data:
    url: ENC[AES256_GCM,data:wMu357cNZSEnLXb4ngXEF3JdyPxOV4S1nlYqho+1TFtdOlH1CZ+YF++FHrMCGu8PD8MMwDGjykWVsEed4aquyb908QBX2eenhi0JFMyL7aOMuTijwC12aPPDVNjs/DYOXB4I5AZvqD6wYcdutVY4X363c2BqaL1077L420O2kJn6UcRPe7Ix39vH+zqgL9QzELkbXmbOlSc=,iv:7uXfUILB9fPB5+oAPl6vjEJnF3mU1pEINNFEaN/Pfls=,tag:pNckCveYH/9ObsFxv3STrA==,type:str]
kind: Secret
metadata:
    name: alertmanager-n8n-webhook
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhdUZIdmlzcWlEcFI3NmFq
            dk03ZVNXN09vOXlnTDF6OFRlZC9YRGFUeUg0CnV0eHdnbFZNdjdOdHNBTHh0QzJF
            UURWcVBBUEF5QzhaU25LRURTTVdxY0kKLS0tIEo5VEkwZVp6cnc2MVplbWJEbW1L
            enZhTE1YSFpuazF2MFNCSmJkZlpoUkkKLKF+VnTMPOFA0Fh8EjUUyr4tc6nRWT+l
            gQb0g2dMRqRxYVKAz7m+IJpUNaURlhL3OxERQxmCwl8qiaEwQhch+w==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T16:28:41Z"
    mac: ENC[AES256_GCM,data:jT0TQwBDGJqwrISj7SzeGR3t5sv3kO84CJEEyD0K3TySvklEmDFylYfgbK1qgBigHbC5aGF9zQvkUZw1kQlumAhvDRNOoOWTGT5pYcKBd2dn5u2Mwb/CzzBeKSGhfYcdN4tcmiCPLBS2kgdAcr8bpL29iE1NllKzP0joUpJoFkA=,iv:W1RitCcJp2mqdBk+M5RVbB4JcUJScbdxrU0jktHWaP0=,tag:JBwW/uZQWV5YwwioVyfHvg==,type:str]
    version: 3.13.1
