apiVersion: v1
data:
    token: ENC[AES256_GCM,data:LSrjsRV8Lme6q7nbFdvqRgLw7aNPdRd+mY0OjgnZcUbgMsOwFuYQN7X0KQw=,iv:KMxSgqVuQhNI0Be4D8Fb27cJsOaOd6wiiq++nFig/+E=,tag:2zUYCj+3TgBqSMGAvaeS3w==,type:str]
kind: Secret
metadata:
    name: alertmanager-ntfy-credentials
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJZXh0aHIxUkhLeE5vSGJD
            aGFSRWdHVXFxTkR2T1B1VWJwV1h4dVpYVzJFCnNmVXFHY2FjV1YvRFdEN2NUamFo
            OHpsNDhmaWhvb0JkcldrTmx5eGJ4ZXMKLS0tIDdBYnU3RTRxeGRUTWRVbGFqNGRx
            emJwa3BtUHQ4dWFvQmFoVllwc3QxYjAK+S09rMvTGZPL73K4nK9GnCJLTdCFCaoW
            ayU0DISvzQxog4nUYgAsg6CsbWEkM8BZjjZHtO0nQmnSswyXjVpTMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T07:29:59Z"
    mac: ENC[AES256_GCM,data:HbHEZlrpR/TVUynIE7ZMTqMUBAlfT2U50hFghkQb5wkVMEbnqas9kWKJusM7FoET8HLDkmN8yY37ovsTNUA9u3W2P/Qd4FKRO2zun2QPDP/Rz9vqG/d5XcLX9SUTbfewjjwcqB0kE6u4XJkWANtzewFzwSC9EtOlLBsjh96I9HA=,iv:LdlKb92+sIQchIDUYYuDFfkOpRHzDQnWMNLB5ecqsJ4=,tag:ZHNdijhzxN6s0hEAGvrPCA==,type:str]
    version: 3.13.0
