apiVersion: v1
data:
    url: ENC[AES256_GCM,data:t2DGbLaQqKDTX2PTZicodgSPETp2bRd9aJiq8FqTohzsObDR9WzRXWOLxPoDb/4jGX1dj1/YptCEnJtAtN8/8arYMKjGFuTaDYdTbvRHO1BaqUfvtdCYx5UANu8XETBm,iv:O3YnOf5+46z36CGUrVP5P5AunvBCEtuyy5tZ31O8ptE=,tag:ZI3Y9F2yThFn+9utuvtnxQ==,type:str]
kind: Secret
metadata:
    name: alertmanager-homeassistant-webhook
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2eVQ0cEtJL1haemlxb1ht
            NWFGSUttSEhoWEdvZ045RWduY240bGVGVnhNCm01RmUvZE9lMnJHcTg3TFluaUFy
            eXFxWlhmQVVMZHJCaFdkTWtKczh6SVUKLS0tIG1wd0NPbzQ0NnZWMGFpb3FnTEtF
            M0w3cms3UmE3aFdQN3lHdVRaU2dWSWcKLYiRRL1LXm6XgQ9Fl06QKdm4Yzh2IE6h
            R1Nlh/ZLRyM1ugIJUvmfephK7FTzn/vOU+V9RA96TU9xhRDGsJOWMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T17:47:26Z"
    mac: ENC[AES256_GCM,data:JySsa942jrABB5CHvrMfERjrxyLUljrCuTuFTzq6V2PZ4vPaC0cprv/23KwrGXe3dFtr2CxKxOmQR5RTNxUt6KgOI9yqDJKJMBBCd2vpbpLqheftedROLxASawpD51i43CddM5sE7rwm7FLiuOWJ2gShMSq3hxB3fiNwIqHSmEg=,iv:2xa/amAYq2AIk7vbnjoMY2Y8550mEmdFTLkoxCWsfj4=,tag:P5msqxNNt8bPP2xYZghpzg==,type:str]
    version: 3.13.3
