apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:geojYZgWQJ2RTVJbJvgvB7ZiZHA=,iv:k+IxsifEbZ74naHouhH+6efpt6d62+wQjmUqU9fpkAg=,tag:c7b6TPYKM5AhG2DBySLrrg==,type:str]
    client-secret: ENC[AES256_GCM,data:OCtR0KzOTu7K/0xfSFzCgfDcqBwX5/9G9Qxj/8KvSPWhSHVzIDRcZovxi34TA5or5IbUQB8Gpy0OI1n4,iv:Qekv3slrc7LyYHZr1A7/nVihlv0j1MwiAtPFkSpulOU=,tag:wkPRtjp7JzhXaFqHk9bg7w==,type:str]
kind: Secret
metadata:
    name: grafana-authentik-oauth
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRzd5ay9nMDhIeVFOazRZ
            RUp6QmFtUE9jLzl6R0VQeXhXbEFVQXF1dXowCkZBdUZNZnNPbXgxdk5OTjZmVVVt
            S3EyN0xBUW1Qbk05QTFzbEx2NXJqMlEKLS0tIEZyamdvUEZiNEFtSXd1cE1jdXNE
            KytSVGhyR3E4L2NzR1JSaTlMRXZZKzgKyz8yLQMVHVR1xA4GZwoCl4THQdT4cRHW
            g7WGp27s5yMEcZkLdRbPYkkJ9FZzpjPlrGw5QdIiMt1+f6WnyOk3pQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-21T07:58:24Z"
    mac: ENC[AES256_GCM,data:05WA2bNhQy0K1Gsoj+RSMPTTYjw21TbVIPtUuPpUWMbWBELIT88U5OQzJByRB+uCjSgBUoFfP2cC3BsXpnRJepbgBBwn1x60FZP876WrhlyWIWP0kGmhGSOyPNHf3DqX4AZMl/qvIvpmLrqH8SOhA/QwJ2r39YxQAv0g07c2Xmg=,iv:IcRs5/hMpEQc8bqFQt9a/4Owxq1xw9mTR4w1u8jZLBE=,tag:KN5GHOWZJYpmBofBYJQBRw==,type:str]
    version: 3.13.0
