apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: readeck-data
  namespace: readeck
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 5Gi
