apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:41KiC2V9TDIh9rk+kczL0uTCjuaNuMCZYDgaLBtyWbY9xK9A6+axkGT/BEkuZa6VnRf0JIal+yU=,iv:70b2O8svhdCEGo6YdymrpKOIDRXUAWZnZh4bJD7nRu8=,tag:zUdWNep6+vr30BrviPpSTQ==,type:str]
    client-secret: ENC[AES256_GCM,data:5KUlAvODxhDkRl61MuwBklBc402YKJ+M+ocvI0HWG+uk+tnAoW4pEA5b8g57khvE9RxjBGyaFSuPKZjzcdz1DSeYEX8C5KtX5aagJb5JGOF/2kW9BNitJ6ReMVJ1B/+1jRVHWOOQ0gevf3Al4Aa8CLEcB0tzd8+d2w96VjbnrLAJfHcICSzTycYgBqRcZiJlHI6+lHYyWmhqTevfxp8wL7Q4Kl3zgNCsV2N2xg==,iv:DO1Psbqq4lQsAbq1/DeMPm17Z28JHYfi26n/iQWcmqU=,tag:G6BhcPBhqoLeFRyHhq9OBw==,type:str]
kind: Secret
metadata:
    name: gatus-authentik-oauth
    namespace: gatus
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReWlMdnQrd2owc29BRjhG
            NTdZdE5ORzd1VWpMb2RWcU5PQUNRVC9oVm1zCnNHV2NxSUJ0Q2NQNmJBWTkvWWxu
            Y2UrYlNLenhMSFJERFB6UVgvU293NVEKLS0tIENjQTNlNG1YMCtrNW5yWTJ2dkRC
            Y3gwTlYxQURqaW1mMTdjc3RzT2xXK28Ky6eK6Fd5yuME1cAm7iPzpQoy0crEUEa1
            ToqAOOeDi+hvsODgH2J+H8MlXmLbpYSpMLlB3KvyElpRTkQORt/gfA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T14:00:52Z"
    mac: ENC[AES256_GCM,data:V1r0Efd9aDlwcT5p0E+pljAqwUXv3KuI1ztpNUYcjB3EsDH0CLARUGFFvPznXpM4P5bRICoGk+nL9wQsEc+BhueVNEc0i+KuQjbo+1ZcPcyOiJckfZpLP2cDFgCTuIChRmvDXYNidmqXitNcQdHj2sAS+Iz11E7Agkrbp3mAnAk=,iv:g6Ao51bbM2HVXlxoLeS9u+OljGXl5STO4A419CLNyzU=,tag:XLVnDD6gCpIpZLwicRc50A==,type:str]
    version: 3.13.1
