apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gatus
  namespace: gatus
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Gatus
    gethomepage.dev/description: Uptime monitoring and alerting tool for HTTP(s) endpoints.
    gethomepage.dev/group: Cluster Management
    gethomepage.dev/icon: gatus.png
    gethomepage.dev/pod-selector: app=gatus
    gethomepage.dev/app: gatus
    nginx.org/ssl-redirect: "false"
    nginx.org/redirect-to-https: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - status.cluster.f4mily.net
      secretName: wildcard-cluster-f4mily-net-tls
  rules:
    - host: status.cluster.f4mily.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gatus
                port:
                  number: 80
