apiVersion: v1
kind: Namespace
metadata:
  name: gatus
  labels:
    app.kubernetes.io/name: gatus
    app.kubernetes.io/part-of: homelab-monitoring
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
