apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-offsite-staging
  namespace: backup-offsite
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 250Gi
