apiVersion: v1
kind: Secret
metadata:
    name: storagebox-credentials
    namespace: backup-offsite
type: Opaque
stringData:
    STORAGEBOX_HOST: ENC[AES256_GCM,data:psW+1K0cQUmhtqvLVp9CEpyMCwP4EDKZr0o=,iv:/AN8I8dnbGJHoQKDJuQu4M9aPj5lgZHItbDpEd1s624=,tag:IHskTOtC8+AufMfoIY0daw==,type:str]
    STORAGEBOX_USERNAME: ENC[AES256_GCM,data:RH9OLvi9gHy/BT9z,iv:dxqU9HGwXKNPeRN22mvG5xFmYm4yrz1gBAyGqnybAwY=,tag:6t0HSHDgt+OYy1K/jLgShA==,type:str]
    STORAGEBOX_PASSWORD: ENC[AES256_GCM,data:JmwgW9XoAaT2/tH30Qj0,iv:s3BcN6XN3I1q3vCaB3l+Um2Khpb4X1H9fYesEXB9dBg=,tag:YMQVW8sddy2i/+gkjxncig==,type:str]
    restic-password: ENC[AES256_GCM,data:oBtA2Y5hUVKEjqYuqeyStwKyMii//bV73vxpX8ScMX3yHP5Q5QL/cjntfATvns4Y0WziRcHZ3EX7E8LPMfk1Dg==,iv:3VMQka/YDaGNBJ3HjG+h9b6ztQrgw/7bAGClWOg1m/w=,tag:wA2ak4bvQJzAXAoRjKJn2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMjFSckxjV09hVDNHVitR
            RnJMNVpyTVhaZzQ0QzUydXRzbXo5SnFxZm53Ck9QNFRNOWMrcGVGS0cyc1k4SWxR
            alRXWTZhemdkM05WVXVkTDc4d04rODQKLS0tIG54bHoySi90SVVNdVBzN0xZcDA0
            ZkN5STVRRnhUR2Nic25CanRxcHpUelkKEKzax9wvspmmP2/BNjyDcerDn0ti7wyO
            Ai3urd6RcMhduAgBHfJxkZpT3CpOk2pggndVou0dkRCXlN5qcmZFyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-14T08:33:17Z"
    mac: ENC[AES256_GCM,data:qwYSXDA0Z5TEvq14o9HWs/vcCp7BzZ8f4QhQW+7hfjktUcKcpCdjhNYzfZAnUZdFzSWMdy+KkxY80xfqufIVI0DATQoRos8WrXtGpelpdrxxImo18zglKd4Cjhu+a6yOBxjjJYcpspHcgifVjeAzky/yhhuRQ5mYqQoW38IsUr8=,iv:09pHRKecuWCQxczyxCu5SCnpzmOHTCy5CWF++qTPCxE=,tag:NXHumJ9+eZ9iFQOsCnc2XA==,type:str]
    version: 3.13.3
