apiVersion: v1
data:
    RENOVATE_GITHUB_COM_TOKEN: ENC[AES256_GCM,data:yKgHCNi6DGO18Hg8HQtiIPfG2haBSV4BOaMg5+vGoiw3pcFSGfu9uA2HSdD+c/t5HL4cRn+sizkwA9jPITfYPAkE3FkQ5GBgHwa9Q2CT0xm7JK8dcc9oKNwJ7Ex6y+3EwIPErpR6bonFOyqijlPZE5sH/KUTgwdChEIldQ==,iv:AlGjUtEZgqei6QeBu4whHNl+UlsyHVQ4ykxHGx3wggg=,tag:3anASVFM0+AK/r7ZBERrFQ==,type:str]
    RENOVATE_TOKEN: ENC[AES256_GCM,data:DHiCVpssSkRrmYt3SZePp6ucnq6veinPmwHFIWTTFgKtyQLVbvwS8JJOt0zVPUg8veOJULIZU/M=,iv:npYR8MUwkY6O1/jmCCjJso/zdZ/gd/q06WCgh2Wdt8I=,tag:0uKE5N/Qiw5A4DS40eu/ow==,type:str]
kind: Secret
metadata:
    name: renovate-credentials
    namespace: renovate
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVUNKM3ZKZmtIcVFxbXFm
            dDA4NTB3T05CVDFKVm15TWYyditUT2xhS0FJClZGa0lTTXhadXFBcVdtUk1OK0Zt
            SDk4T3FwQ0dLMi9POFppcGVPWTlnZlUKLS0tIHVidW45NmFsZ1Q2TXQyZU14aFZ4
            WWhSZ0V4b1lIRUZJV2pUMVMvQTlOZ2sKeg5XtGghOOwBE+lCKXrx/oj5kStmhAZd
            FYwMexl3Vy/vU5gFixouTCYvW182On3hPPgFB/sQeo347u9RnUz3Hw==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-26T12:17:52Z"
    mac: ENC[AES256_GCM,data:kvfRVud0IY83L/puxj1KC60LyDR18OpgYJNoslyqPYpsXPM+UaBz8ntcYHI2hGBM2pr1bg4dJnen+2aGaMTslb4nd468vee9KHZRoRuAFgX620IBpI+C1jttvIV+Ms9ymMfh1TEitMxUk2slqW+Wa4ZqEESao+zS9c2k3ZelMB4=,iv:wcuJj1my1/KTCzpfVFw0CUXDRjvlK3Y7jv8Fv2w7Niw=,tag:180rWWL2hP2KoAOmmoxdMQ==,type:str]
    version: 3.13.1
