apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Cluster-spezifische Ressourcen (Zertifikate, Issuer, zentraler PostgreSQL-Cluster)
resources:
  - ../../base/network/cert-manager-issuer
  - ../../base/network/certificates
  - database-clusters
