apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:RwCLW+oONKfmI9QgzsAUyVRWDvogeHuq,iv:qMqpUm4DuI7H+/VRAm3O3S9Y6AbVtFSklJP+kzIliPA=,tag:Grx4qj5yXzsL2/s0P0WEbw==,type:str]
    client-secret: ENC[AES256_GCM,data:Vt04kCMB5haAH8tff1UzQOfRgplRvPdZ6O84cxm4/rh+EHyIapblgbpHy91Xm5oEnm4Iv/3TuyIWh7Fs,iv:QiYiqUSb4PsAtetJi2JD2pBQxTZ6C60DJniIeCz6yL0=,tag:Q8isy4O2qFcxomfrqyX9Gg==,type:str]
kind: Secret
metadata:
    name: dawarich-authentik-oauth
    namespace: dawarich
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2N1pGaTdoYWFIQnRKOWwy
            cDQwYnZQeHFsVFdjTjQ4MzBzWTh6TktXc2lvCjhXbUhvQlAvTUhTTFJsMHEvbnI4
            RytLeWRweTNHc1lhUzk5ZDJubU9hL0kKLS0tIHE4UXFSbFpVcmlKeW5GQjF6ZkhJ
            VGdoVmZiV1NiVkJad1RlL1R1bkRBbTAKCzQM9MSbBOAMOiO0SV6kOmF1U4KQgi48
            LSDgTyRxsTABu2cINVbd2a993W0i/Wtux2qHCz0f5izIEUsPcQ3ABg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:53:13Z"
    mac: ENC[AES256_GCM,data:o7sc8l3RxN/TXXR2UDmbd+G0jEcjlcf8FpirOUAWY+OTETNc/C+2XfEEhNETz5Al6v1f0hZWCUpN5ecwFiaS6Bd0cCPUwnE4P1hY5AaKbjR4wMpo8GvG1AEt110DcWH4RRoA1RporQmE0MjFMi/tiEQorx731Vp1Mx+Nw/d8l0s=,iv:EVAhAWkNOy1PXJ+ugMvgPBvvr8Ph3Z93r/f/Ve04uMo=,tag:EHWbp9H7fZvHVH3zjwkeGw==,type:str]
    version: 3.13.1
