apiVersion: v1
data:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:L5U0Ruq3x+AWC8IqUkE8UUS9mLegflSrziFHihIKOTqcF5+L0bvEOyJikImPeWI91DFbeRJStJ11zMGUHJl5FGisbgwZNE7RmVbXxwxQakecZVe21ZOvzQnYXa6H3LJCBXXsLWUaFKf5Gq1CxWOImuot5jhCkYR2EyNNHX2j+3/zfXXvgt0NxPlbtcxreZrEYDIu1DdJwAFddcRAPxBDsqrG8hjy7rL61JGI9w==,iv:fcMWJKQfY535vJjRprnx0QzfGCv/WMxm68E4eRSjW6Q=,tag:9Eh0reM1QrHiM4ETrmbqcQ==,type:str]
kind: Secret
metadata:
    name: dawarich-app
    namespace: dawarich
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4cXpWb1BZUmNNSzBkOWhR
            ZkZGaDNjRWRZZ0Z0eEhLUTlPR2h1ZDRQSkNFCllxNDlJR1NRR1RLMGxQWVIwYlhu
            QVROYk9LUUxSMFU1R0RkWm1NU2RKcEkKLS0tIFc3SkU0cnRQU29NcVJqUTQxWVRZ
            c1RTbVovRFFLR3dXaG9FUkQ3MjhzeXcKOCfMgC1WyxsqWpWGRAChCMAscBK2ybd6
            LSRzsiGl7qJVwtF/etxvnl237BuSpX0zYE810lfhyYljvkC0ysXu9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-21T18:44:24Z"
    mac: ENC[AES256_GCM,data:pSJV2RWnO4twr4AbgPkAeCZQnedP9t5liEcYmbqHSC9AtkVMAjE+ZFYD+E0HU+7nzJLwUm9p5YHK/Qv1wcwOFZEKi/tC5IzKqeKa6AJKL1Y/Y6gqZ64F7yI2ueR6ifZoY9UctDQ6igCXNnAOGWRnN3s40j8Dkc6IHM8XFc0OdG0=,iv:NRrVV2L7FAiM1CvgGEFz4X4XxmHRxS5aKWroE8+AO1Y=,tag:yfFs6u55JKjRoj4ZGmCv7Q==,type:str]
    version: 3.13.1
