apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - nextcloud-exapps-namespace.yaml
  - nextcloud-admin.secret.yaml
  - nextcloud-authentik-oauth.secret.yaml
  - nextcloud-collab.secret.yaml
  - pvc.yaml
  - whiteboard-deployment.yaml
  - appapi-harp-rbac.yaml
  - appapi-harp-deployment.yaml
  - helmrelease.yaml
  - ingress.yaml
