apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:FpQ2zGf5tvf+udPv6dPhqYJyUdvG10rE,iv:j3dutqLNEoHwD7efK/aSTFzr5KDI/GvWCOyB7BrBe00=,tag:JbpjMXVjOEWNtmKByyWkHg==,type:str]
    client-secret: ENC[AES256_GCM,data:P8tTHOZ9zYMYFW4RM3YjOCYZAOVAgjvza4gGcdqD1ejuyJVZ9NTQAPYZ2Tx4XXhb/7ElSBheBtVM/axT,iv:rVuHds52ELIPN5UeIjLLS1Oyz1PqS9zgWd6v+6zptco=,tag:uyAuno2JT5ioLT287Jt2sg==,type:str]
kind: Secret
metadata:
    name: nextcloud-authentik-oauth
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoTHRBWlhDMHNlMTBOWGZC
            SWhUbW1qc3lnQUJTY3lTTGpRYXJya2YvaGhjCjVPNTlMU1J3NGgyN1NaNDJKYWhS
            OVlFZlFoRWxzMVZWUUdUUXRValM3WFEKLS0tIFpVelNJYUhmTmFNbzdIc1dHZVky
            T2FCY1VWbExVMDd3QW5FQVV4SHBlRDgK3mBVAxTaTjiF/nBXRyWtSupMBrhZgbFj
            Gx8EvI7bNr8idYOrgEbv1io/TQ9k2DqPQalTLFbWm7c3EgFW+ywofQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-29T14:37:25Z"
    mac: ENC[AES256_GCM,data:VqQoXJPx5oH0/7eJnWEfFD+lZYBrfA7ibsi3j7FKKuHfBXqXpg8fR95bRxfhv/5p5UxX/yzwFwA66ACKa4YyQ0tXCmm8snczDyHQUqIPjiteD4N7y481vKO/PiSpqyO2cdUsEtRu+CVwjqMNHXtcj0zJ44cCjexv5ZYbJj+Cp8g=,iv:XjC73Tq8spxI4KkCdek/fwVSeVX3Hks4a/afGTHD9SY=,tag:ELDwWQ1B3W0e28agQMnEsg==,type:str]
    version: 3.13.1
