apiVersion: v1
data:
    password: ENC[AES256_GCM,data:N0Y2TOQQrosaS2W4BIcLqngCgbq8tycTzBGYdxI4++LpSxHAd4eQmghWEN4=,iv:GqbWtWBwLf0L6PakLPwq2jzIlf1KojqNnKDPVKLS9Nk=,tag:RlKLQpYpob+S7Ztt9DJpww==,type:str]
    username: ENC[AES256_GCM,data:e1LwEAj2H54=,iv:yrbim4FYUWlY6h7/O8p+sYPOhQm+r5dhibYKZhU7RVY=,tag:UmM4C+OAkTXk5wAYoc+SUw==,type:str]
kind: Secret
metadata:
    name: nextcloud-admin
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbFZjZGZ0dkh2UTRiaHB6
            b283RVlDa3U5WEVvY1BlSGsydkk2VmV2UERnCm03WjdzZUJBU3ZxckpkODlnMlVr
            OEhHN2dDTC96TCtIZmJXK0xjdUdxWEEKLS0tIDY5ZWdETFVKcVhmak43TExvdDhh
            MENFZUZPSjNTYWdkdXZjM1N1T3ZQWlkKcQlo/NaL3WSMFe5owcUOkH83HBGcIanU
            R7+PgZwHHuNYZ28fUJhEizdxXo2xn7UsONZtFAGdY25nUTK7BzC0yg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T22:12:23Z"
    mac: ENC[AES256_GCM,data:KQmEU8ZrskQKAsUndew7TuHbijn3ENzT28i40NckUVaeA9LqQCs3P8obYuiIlrVOZ9RvTUxQhUo49itJUc+Ukcq/MvnrgJfA+uxiKGMxIsUH8YS71kXck0RBeHXNOZdfihzA69j97kCyv7GoY/qPxNuPxZ3ZUKPsYKU85VkWmTM=,iv:rZx8E32Nt3bHC8madLDxi6AYhKOMIAQBuwCmP5lFfBE=,tag:BGqAqVFyP+AOlrV+9GhO1Q==,type:str]
    version: 3.13.0
