apiVersion: v1
data:
    access-key: ENC[AES256_GCM,data:7V49XDc0E5z7lZaektzHcBVIsyFfrANhJhjJbrzJ1bU3ognx,iv:Pws1ClwrXi+eMSZ85E+GOS4I0dzefFWjR7sPJ+dFaM8=,tag:sRdKYlWAtoySRPrkYyaoYA==,type:str]
    secret-key: ENC[AES256_GCM,data:U7Xdxvs4ZeQ5UMzM18M6sNqgWopFXigQI2OF8o9vaOhHJfSl/LfKxrVNPquEWGnUlHDlj2QmjioI0cJTGl4UBOttNJpJpzVx0PLbYH+84wqmulGBu/Vaew==,iv:+PyWheiPBJtSKkSgMzc9ED8U+hxeEaLGmj6HS/q54D4=,tag:4bfRbT1yi4dtDjIV2kPBqQ==,type:str]
kind: Secret
metadata:
    name: nextcloud-s3-credentials
    namespace: nextcloud
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWVHQydWdyTmJZTlNWNkx6
            V1NZNjIyVi9MakNnZ0NHbDVLMmZLS3hiNkhBCkJDY1hNcThhMjYwMDI2Y0dMTXlX
            ejZjcU1TYklZanlFZDdCc3B4MTNGVlkKLS0tIFR1ZTBBRUtEeEdMY3BYcmtrLzBr
            ZVJoeG5PclEzR1hhcUJ3TGo3aWxScEkKwu98H3GOc0L/ll4MpPFFiTC+tgzbuQUJ
            Pd8wTQ5TOKEDsEKxeQEzkmWNdIGSpV3kJCA3lkYAVYw5bLr2MJ3UHg==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-06T08:39:55Z"
    mac: ENC[AES256_GCM,data:kOu80HxlNgkssXjRSElkehpcU+sRkZzOToP28t6dliiET3bLjnhjG3ehDJ61xnJnkwyETx/YKptgGUJ0Z2biI2dmHTyTktps0akfepCXryW21ue9RwGzjRqTcEE1wK8x/vERJfTeOsK8Y+SCz8oBjxvtaMq7eZAQrkdws1bpQ0k=,iv:jRkjn8P1eYJyajIGExFtft4lIrcjAFk10FUBOrjbn4A=,tag:uAIxA76qHtxFY+u2gMczcg==,type:str]
    version: 3.13.1
