apiVersion: v1
data:
    harp-shared-key: ENC[AES256_GCM,data:qP2slOuBI7PE8+rbJIdPo6vGK9zXMcsd4sl4+gXA4zw+2NkKKFHEgfx/hMxA2uf6qg4n6Mhu84Yas7Ld,iv:PISwe4HaT7DFfVyzsOlPj0OJCmecphFv+81vaJ2A4Rg=,tag:HI20Lb8wzI8iGq8k8wnuEA==,type:str]
    whiteboard-jwt-secret: ENC[AES256_GCM,data:IbwjFIrOH/GXKrEFOGsn9vrEl97SQ/R2iIL1yk15PCfeZwsiwupV4iJc+BohOWhaq+c1qMv6DsU=,iv:SOpAJ7iRc8pxeBjXV8qkkgLN6BD3fFr7yalKVsnggYs=,tag:xHslgXOPXQAnGC3AY84txA==,type:str]
kind: Secret
metadata:
    name: nextcloud-collab
    namespace: nextcloud
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTlFKZ1p4dENCNFgvdnAx
            ei9pTktlYTRLelQycVpZUVJSQ1Q0ZVI0aUYwClQzT21yOGk5czdZYThtdE5kbDJL
            ek1ZRlFRR2JDNzU5dnpVcnMzSnJQRFkKLS0tIFFyY1RPSUs5ZjV6MTFmN1V4bnNw
            eWdjSUVsMW00OXhOZEVWbks5WE5sTVUKKtCYsw7wWZ5HH+0xntOBtKhyJQ2rZ9jw
            yELvD8RkqgdO/f2/RvqkoYv8vhwMcPpWhQX5F3T2ciaPU7FD7pO6Fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-30T06:52:58Z"
    mac: ENC[AES256_GCM,data:LRZhudexEYOzjdDVLJ+VQtLa0rM3pCwXK9Gofbg0JuFBHSeFy1N1/EjrK+zpc22i/d2i/6p0Oncb7vY9cugbk3gZDmrEM4mE7i2CMEbqveAdsJlluCPRX/9JWSGRpbqAKFLyOPsaQtMSwbIAoTK5rTzrmmE505BSWZ62/CezSYA=,iv:aBOpPPtqRuHT8Rx+mouRKKXIuRBJ7CTI3IVpP9M00QA=,tag:iKi8blGHXAV8vxkzMt0OVg==,type:str]
    version: 3.13.1
