apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-app-iscsi
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi
