apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-data
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-nextcloud
  resources:
    requests:
      storage: 500Gi
