apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-whiteboard
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-whiteboard
    app.kubernetes.io/part-of: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud-whiteboard
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud-whiteboard
    spec:
      enableServiceLinks: false
      containers:
        - name: whiteboard
          # renovate: datasource=docker depName=ghcr.io/nextcloud-releases/whiteboard
          image: ghcr.io/nextcloud-releases/whiteboard:v1.5.9
          ports:
            - name: http
              containerPort: 3002
          env:
            - name: NEXTCLOUD_URL
              value: https://nc.f4mily.net
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: nextcloud-collab
                  key: whiteboard-jwt-secret
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
            limits:
              memory: 512Mi
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 15
            periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-whiteboard
  namespace: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud-whiteboard
    app.kubernetes.io/part-of: nextcloud
spec:
  selector:
    app.kubernetes.io/name: nextcloud-whiteboard
  ports:
    - name: http
      port: 3002
      targetPort: http
