apiVersion: v1
data:
    password: ENC[AES256_GCM,data:6yw83UcG67Y2LGHvMxOSKg==,iv:TWgCkC9RlZH0Q1FVKKWtahZ4b0khpB6aFBnWUzBHPJ4=,tag:/UGOv5XgntbPrbt0iuanTw==,type:str]
    username: ENC[AES256_GCM,data:O1eWAFqRJDzN6DlamhpVA6iedaw=,iv:uj7P++nDtzps+bS1l47j6HLwxuwLYM7PYucVyU3xJOU=,tag:YzZHC9dSDy5YStEVPt6www==,type:str]
kind: Secret
metadata:
    name: homepage-adguard
    namespace: homepage
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0S3J5ai9tYzFtV0w5eFU3
            bk01dlBNMEhKcnJhekhKKzV4VnpZSjJHV0Q4CjBkY0QxUEZPWjBtdE9BNHFObHBw
            MEJoOE82UTh0OUFqVGhjKzV6UTNvRFUKLS0tIGNxMzkrbi8wOWlWRm82aytWd3pY
            M2RKTkNRZGYwNWJ2TVJsbmhhTVZNSmMKtykvi9btz/f29ngLuXjHK8D1iw9zRy/T
            ZEUtZlX4DldGaDxelhmQhY/MvlLptekRAWvIMiWWiJyEup7kCmyDpQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-04T17:55:34Z"
    mac: ENC[AES256_GCM,data:w7J0GySsr75l2WrBfcXlJWrbkaY+T3qxAe5Jyc+bLdSwHq4dfD2+BHv0Ec8cyml8ANHn6LixoHEzF1YEqwFsOmf/TfLGS9WD/nY3K0/TcmaJ+2tm8BHN/ZwDX5cgu3E+ESqPmNL+kZrj63VufJRjL6iHBWm7wRxak8kGdetCpTU=,iv:KW69N7/kvHzmFsMThpavj7P5s5BE6OO37FrK/x36q5Q=,tag:O94Kz8KvPLLxsEqZoPp9hw==,type:str]
    version: 3.13.1
