apiVersion: v1
kind: Secret
metadata:
    name: spectrumknx-secret
    namespace: spectrumknx
type: Opaque
stringData:
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:41NN70iyTZouvzbPb6rRBE3ULi6tTV2oOvxWgX3gNw==,iv:pNy/X4coFh4HznuIA9R4ft/p5XAm65mUx2vfOjep9RQ=,tag:eyuSPLpgS2N1zr69AI1SEw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3OUk3dVNUdkVpejlPWmpj
            QlIzaEVCa1lhNkQ2Wm9waWNGbUtqbDQzY2dzCmx4U1hLazZKM0NjTXZzQVFsTXVS
            YlZnbVBadTRCeDlUNVg2VE5sMVpMd0UKLS0tIE1jMDZZaFNrWkRIUDRvaEtVWHNs
            Y3EwdGVlNkFaTHhLTDFGU3VUUDgxa3MKH6EbSIPmDwBY55ua7jKD4cVaRTkEjLtU
            O6ZTmdsrEvES7A9t+ulAXIQ+oDtw3EFcZWN4ZIueNJS66OnhAcieyg==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-18T20:42:44Z"
    mac: ENC[AES256_GCM,data:V0c1HaHy/r6/4598i9cRsZZ8U9Orj7oWoTGlEfrk/w8cZRNSW8bjGBa3ovpv8KMIjXnj3EYS3b22uw61jwr4HVL2d2Lnf8fSTyGauRIHS2NpbNYoZL2zoKIu/6SnMx+U4DLjj7zF1xaJm/6tDo/e5wBM9ynE5PCxZhTQbAUQr3k=,iv:FJJwMMZtuq17rHF5o+vWDpqQ//pUGvssSc8wwOxdb7M=,tag:/JS2IQDDWNrwSB/jt/k+Bg==,type:str]
    version: 3.13.1
