apiVersion: v1
kind: Secret
metadata:
    name: immich-power-tools-api-key
    namespace: immich
type: Opaque
stringData:
    IMMICH_API_KEY: ENC[AES256_GCM,data:aMBrWlWCahzvnvqo6WFLlUdxQLjxn1vR27p8W56BNAXCnnwx9bFPDEIozg==,iv:RH0WVpndceiXyVAjKBXkky+OvI/WiDgBt4CAQ/wwjpo=,tag:MYEZjkhS0J1n3iofDHNh7g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bHRnSitCUTN6enFXS0Zp
            MlYzdnIxTXZDeVBMcVNubUVML2k4SzFNc0RRCmgxU1dXbE9UeGlMMkhWcE02NzFH
            WWRlU01BWHR6UHd4QlIxYzBieFU0cUEKLS0tIGR0eG44UjUzOHJQc0gzdXhtYUhi
            eTJyS2dZb1dYNVMvN1lwd0h4SUxQbTQKm0RfKeuIHyuXTJ5afqUjMvIRDhzb+Dj3
            xlZEYV8jVuqM+OBcExBJozCB8lvGm/A9lJXK1GX6eJNQW2ZUJH/9hQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-27T21:23:46Z"
    mac: ENC[AES256_GCM,data:Y2xHc8aFoUHZygaYQhutPF7hSxh6B9l7Cd5ipATe37ZKxbbCegIItvWowyK1+5rF0S84M3s5iV2eUN+FZqih2rozNkqhqzFLD/qKSTXM3GEc10KVJ2x0PryfQu78vvNKb0TzRMHteQYcTCxDlf0LFyp8wZRV26n8hUVQNfQbcVQ=,iv:jcCMHo0YcZQtZ6BbmIziTWNZrHeuVExzapxGS9yYzDs=,tag:ryA9+3sok2Ar+tDlUl9fUw==,type:str]
    version: 3.13.3
