apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - renovate-config.configmap.yaml
  - renovate-cronjob.yaml
configMapGenerator:
  - name: renovate-config
    files:
      - renovate-config.js
commonLabels:
  app.kubernetes.io/name: forgejo-renovate
  app.kubernetes.io/part-of: forgejo