apiVersion: v1
kind: Secret
metadata:
    name: forgejo-runner-register
    namespace: forgejo
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:oUEbYtfDmpJpu0Vv9bKoPKzP6K/LihSpqo9vzWB+mT2kyMC3jl+FRw==,iv:Gg7BenXzhK54myzbqa2do2tY/WOjSAukhx3QkIABzyo=,tag:x79SmRWC8FSY4oB7MBOZ1g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGcUtZblJoQjlLVExPWmUx
            a3N4WldXVjVwT0M5Q21wRjhSdzNPNFRiMHlRCkp3RGY2RjNhaWVKdkt2ekpGMnJ6
            UzJneVljVUtXOXpqbk9ncFFlUmwzZVEKLS0tIFkxU2tZOUExUlJlQmo1YlU3TEJ5
            KzgwWnF4WjBhZmJmUmxQZFBhaFpUOWMKQwwMeL/qlVjaygYZjf1yTo4sjs974ytX
            jSwTfpfiO/dMCF1RgTcaSIrW8lwg4nRE76xRcCMCTsq2UkhvqEOilw==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-19T22:26:16Z"
    mac: ENC[AES256_GCM,data:8mPGh664DOpEjBSHX1oyoSoYHQawmf4nMT8xt8qsr/TMrOj9QiwE6DdrxrVcYE0dHi8L9txHf1pJT5DQ4xCMjQGtnFoH/xJRhFgCp0gRjWz0aoZB/l+wKsnjVfy9G6Y45W85dSIa+eyL2VzM8/B8lcV+lmfw0kERkT0DTuOnSro=,iv:h3C5adYuDiS3kHwy+udMGpRJ4tc4qTtl/7ThYQZtKrc=,tag:B/Gg1sv7WnWTf7Xg+ZaUng==,type:str]
    version: 3.13.1
