---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-media-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      storage.type: nfs-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: audiobookshelf-metadata-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi