apiVersion: v1
data:
    HISTER_ACCESS_TOKEN: ENC[AES256_GCM,data:Wp6FqUqxfVkxLFO88900cZw6pNjHODclGM3gT/e07AGjd7bTgRMF/LC9j+8G4qJCiVsFDtvcIPP8mooaTsgYEIdRuGCfc58PVVLhprBwNYaOKF8lfLUGEg==,iv:FoBL5y6zHOks3QtSKE3DmbJc8JdniiFRn+Lv8+hpj4k=,tag:vwT2GU1aKs6HXR7HOMa5BA==,type:str]
kind: Secret
metadata:
    name: hister-secret
    namespace: hister
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUWd1NDlFVTRQNlJnU2NL
            WWlIQnprRitEblU2SVdNNTlvRXdsdXhKcVE0CjBaWWZzR0ozcm4wOWYzeUNDYW5D
            Ry9mbXhjemsyb2l6K0RMRDU4QWJqaHMKLS0tIEExMFRZcjdYUzBBOVdobWRFMTB6
            VGROeVhiRVlwbmYrNlN5eE5HWHJkbzQKYIoKrkXh01149+AvLd+fXUklMZbdcS9Q
            8+hxEZne/clvAKKkGEQitmHctGZBQGUbd1ZjXoDAk0lRZ6jK4hwwWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T22:08:19Z"
    mac: ENC[AES256_GCM,data:xe71CKpKxsNoNwGUhGnEKXIeXf/2FKagZfdd4feh1iiVrfyqiyx5PgtHu+IvEMzYaQsANL+DqxknMKxt7yHVw5XpKlIYRVl9HrYxYXzh7vS5Axn1zbIyXvJBmVc3FqPOeQql9oVtVk9cT77wSbYghNdd3Ypi8sdXjQmmJDAoW2M=,iv:6Hl4eGzKdnQtlfTr73SF+cv/6qKGVQLPZxQzadaKlLk=,tag:eMRV+DMDyNv0AXTOYlM7sw==,type:str]
    version: 3.13.3
