apiVersion: v1
data:
    HISTER_ACCESS_TOKEN: ENC[AES256_GCM,data:Wp6FqUqxfVkxLFO88900cZw6pNjHODclGM3gT/e07AGjd7bTgRMF/LC9j+8G4qJCiVsFDtvcIPP8mooaTsgYEIdRuGCfc58PVVLhprBwNYaOKF8lfLUGEg==,iv:FoBL5y6zHOks3QtSKE3DmbJc8JdniiFRn+Lv8+hpj4k=,tag:vwT2GU1aKs6HXR7HOMa5BA==,type:str]
kind: Secret
metadata:
    name: hister-secret
    namespace: hister
stringData:
    HISTER_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:FI+VwkQei5uVQajrIX5oYlDGXVYYNquYIQFqgKQXOWNhRZ4nkn1+oleIOlY/gS5CiQLlLxsfA/KTEBSZ5KUmtg==,iv:4ywAm29pa/o2pZc97yWTfkM1O9pn6mghMri+az9+92U=,tag:oyfY/e8hg7vgCZlbmd3EIQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFUWd1NDlFVTRQNlJnU2NL
            WWlIQnprRitEblU2SVdNNTlvRXdsdXhKcVE0CjBaWWZzR0ozcm4wOWYzeUNDYW5D
            Ry9mbXhjemsyb2l6K0RMRDU4QWJqaHMKLS0tIEExMFRZcjdYUzBBOVdobWRFMTB6
            VGROeVhiRVlwbmYrNlN5eE5HWHJkbzQKYIoKrkXh01149+AvLd+fXUklMZbdcS9Q
            8+hxEZne/clvAKKkGEQitmHctGZBQGUbd1ZjXoDAk0lRZ6jK4hwwWA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-25T22:56:07Z"
    mac: ENC[AES256_GCM,data:ZK6hp817XCPAFreydyLERWTgGXvr0DuWmgB9JLEEW+couDm0vkEzj0XnlWRKonU2FRn/+TXxgzVIElpA4CPKIwXN4tlJ7LWIwJrhSu58MKeJMttICZ0GLTe+PFTCxNmebLbQ+7aVfDfqZbOe/o9/bMAhiMJ3c4WuMqQ1VmRqGRI=,iv:wRUYiaxjxwQ8uGJM5iu8KTk1pGyjUU9T/RGVNekKBSY=,tag:vTDOQ9np2Qs5T3qg/QD7JQ==,type:str]
    version: 3.13.3
