apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hister-data
  namespace: hister
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 20Gi
