apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: velero-metrics
  namespace: velero
  labels:
    release: victoriametrics
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
