apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudnative-pg
  namespace: monitoring
  labels:
    release: victoriametrics
  annotations:
    kustomize.toolkit.fluxcd.io/depends-on: helm.toolkit.fluxcd.io/HelmRelease/monitoring/prometheus-operator
spec:
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - cnpg-system
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
