apiVersion: v1
data:
    email: ENC[AES256_GCM,data:gSkCvUiem3gMk67CqbmhEqcEP7icWBLH6o4=,iv:aLnQlQ+dJTjIirLTUjlw2kXQD1E30Bt7f6/24uGbAtg=,tag:F/vntEkC90d5I79Qac/iAw==,type:str]
    password: ENC[AES256_GCM,data:rKWMA6HoM/irg/ARNcna5Q==,iv:r/Kjxx7r/JzylBqPbAJoaFloK9eGe9xUhq0LMeHFHmI=,tag:7bOVVnTdB1GID3gpsw1TvA==,type:str]
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: cnpg-system
sops:
    age:
        - recipient: REMOVED_BY_HISTORY_REWRITE
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVaXR2bmxYdVZxaENOQjZz
            STk5aDlOTkNyalBkdFAzaHM4bzFUVmpOTFNZCituOFFGSWxYbGVtL01qQVhXTlRr
            Y1BPUjdOZjhwdEFEVldTdk5JdHA1YjAKLS0tIHhlNzdWWkcxeUp0OEVuYU9HY3V1
            QTFTZWRlOGsrNlVadHcramhnYTY5R0UKjuMcM7NIwALS6T8MgLeBD20C3JpaatSd
            JDIQnbHOEK3ErGUgr00NPI3DeJ0HZhezaIWdqOrseV0F+vjF/sbvPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T20:07:36Z"
    mac: ENC[AES256_GCM,data:uvpMg6Goo9KRNa2CzEf9U14m/SG4sQHGOdGTsXSeiPuo83NV6vRUUJdXxuFnk2/fhj9woptxRcfFw3c4FSC3O+zgpjOVS9DsMQSxurTPimIOQYfOoh7g+f2Ka7ZAC19fCZLraXF9MsSFWl3NQ1092JAQOdsyWUskfkY08cuI9Vk=,iv:msCtNta4UivbS6LNtOWsEHKyoK0PEOq7JVmkr15TFMM=,tag:p9sMDKv73ozuFGg9ZHPs8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
