apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: cnpg-system
type: Opaque
data:
    email: ENC[AES256_GCM,data:Ck6pUed+NhrSpXeFr7KGJE2h0Eir/btyFvG5SZg6FnpvGoof,iv:PNjk7zyikCWRGMLJQZ20V2k9asR4IhK/wu91fM9Syos=,tag:kQ6Ut+SgAYw7bXdIv66Fbg==,type:str]
    password: ENC[AES256_GCM,data:eW3LKhFIIkS6SzPFq0b3f+4xi8h3CGLF,iv:TgBX5bmPWaoOnByHUnTmJURzDQAGsEHZF7duHal8tsM=,tag:KcTkXO0Q9saYPe/L6RNUgw==,type:str]
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuQnhUcm1tSUFEblVWbndP
            Q1FOWVlaUFR6MlZlcmJQc0NWQWtuVkdiQkJRCjBXWTVpbGNFR1dwVXg1YVFvRjB1
            WHRkWjlLTjFHZ2N1NTZpdHJZMk5jQTQKLS0tIEhSSCtlOGhFcWxOYWZIU3REUHRV
            Snl1dnRnc3lEWStEb09xaHgzNzRXS0UKQfQbzw8uR9TaKcH5ayTDANFKb3Pvmnqb
            QHnntYhOgtCqMVII8DRMariGuEZLkYetdVGUeCvsc9UVCPtQMbH3mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-18T21:22:06Z"
    mac: ENC[AES256_GCM,data:HpldjmFmnlHMI9yriRkaGbrtYhmqDMg2mMH+lnpCrLOjX8GJAtX/Vs74pm6Pp1Hqc4edypo94mktAnHlrgCPj51JzTOmvvFaXmxrh7fBunqSDaTurJlgxjD8qjO3aBT9n+clGPULJTj3GhR3RJzDSJv011U1uduDyYeMNPG1omE=,iv:WoKGJN8dQLbbGb2afqn3EQrt3EI+ohWMs+JP3t1IQuI=,tag:4AKyVKqD+CWY0R4M11woog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
