apiVersion: v1
data:
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:HydpsbzDsyt7Xocvk68Z5aqItDJebVgUj4pH5cLnza8=,iv:Sl8kgx0wdJvjAYP4N5Rb9w0+LhGUoNClmB+10rcn8jU=,tag:iwq3mvXDahulrk2vTxZ18g==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:8r4GsYY+Iie34r1Azykx9epPuBm/s3JIGvCd4ZLlSgHH4SSW0c0aPfknPLxrtc5v6ro+UnKdNowyQdzw,iv:/CDD6cEG1mxKXZWKbBcWE/+eDLodLpdausxhz5nR1Uo=,tag:i8OYp9ETgNx5kqjDGnEdSA==,type:str]
    MEILI_MASTER_KEY: ENC[AES256_GCM,data:ssMIIAobljV1n/A9SC4Zfgr6TGen3pp+DcX0czS0DANBeuP2Q6nvVSXEMXdUu0FZMRr5apAAg2aqel8W,iv:G7hdSLPpRADp01CZM1nCxVRDCpX34ecYuTQ/62GKXrU=,tag:kyGl937mrUkS4nZIzJp8Sg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:6VyLPtCiN53W3W7Oktbw85zEH4J41GbYVfjdnqWHU8mkpshFdal9o1e/jftIpI9O3isGtvPkmPGhFhiT,iv:pCf9iMTRIbhrAQp8ftiEptuZFwsQvPqVFw+TuKDQN54=,tag:Tb/cdokXpv46hyvae1tPiw==,type:str]
kind: Secret
metadata:
    name: linkwarden-app
    namespace: linkwarden
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFY1pIRzAyVmJRZlhhbnNk
            WFoxMzY5bTZueFdkeFpTNXUyZzVEKzMzS0ZBClM4b1dWdFNUd3daNk1IdXJxbGZP
            VnlibWttOHhvNWgzSGtDM3hUbjhoOU0KLS0tIHA4YVIzWDd3eGdQOFl2SE45RmhB
            Y0tLa2lHRy9mSEllK21MMlprY29DcjgKowOnolzIDdQgLZ+SXnSagEWMCi8y9sKy
            Qhk+Y2cnSlyCKBrtcvEoMuvuP6QKtSiDeKON2e9Ydj2iy6IqxXoOzA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T07:08:54Z"
    mac: ENC[AES256_GCM,data:0GCwbQar5p33MC6oUxvH8bbUfGt6OppeLfLXIMp2VBoxhzHQN75VuCTTpCf11hBwUqlgMU56wvAee6AhFU/mQs4rFzENtNiMyjwoT/B04a9DbsqPgg6HyTsa5yYUARoAHl05zbw6nq6HVYOqGxSQsWm9HI7ocKoHg4/hYGAI5Lg=,iv:uTa5RFAfCDyJ+NmBGmWyq2bWspMh+1dpc79dT3huB+k=,tag:VOZfvJFjfI/VspX+GmYK5A==,type:str]
    version: 3.13.1
