apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config-iscsi
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache-iscsi
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-jellyfin-media
  resources:
    requests:
      storage: 2Ti
