apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-jellyfin-config
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-cache
  namespace: jellyfin
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-jellyfin-cache
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: jellyfin
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: nfs-media-static
  volumeName: pv-nfs-jellyfin-media
  resources:
    requests:
      storage: 2Ti
