apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Medien & Dokumente
  - audiobookshelf
  - jellyfin
  - tandoor
  - paperless-ngx
  - immich
  # Infrastruktur & Tools
  - netbird
  - backrest
  - searxng
  - uptime-kuma
  - unifi-controller
  # Cloud & Management
  - nextcloud
  - linkwarden
  - authentik
  - homepage
  # Netzwerk-Monitoring
  - speedtest-tracker
  - watchyourlan
  # Development / Sonstiges
  - teslamate
  - goloom
  - pcm
  # Bereits deployte Workloads
  - homer
  - kite
  - sterling-pdf
  - monitoring/vm-k8s-stack
