apiVersion: v1
data:
    NB_API_KEY: ENC[AES256_GCM,data:vpMcLKPhM9bnVnnL+DTg+8I56knmZwN8ncgy/YHlJ+M=,iv:mKtBDBh9CvHfnXEU+uWNZaMQKxE3svnRsDT9rTYIJgg=,tag:g5+vafCDHGQVV887kQtMeQ==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbHZyaFlvZkF5bTAvcGFN
            VEtnNlU3MHB4dVJVQ0s2NGVheVcwaDJuTjJvCjJLQkt1bDltRFNQVWxqcEFDOTdH
            WHQ1bTZQMWhDM2ZucG92N3YzZVVJZlEKLS0tIEd0NEhud240WGNzUUR2aWVMeEtL
            NlJtRW5TdkhkeCttRFFNU2J1bFRXRVkK9CcIDaN7+QrxlO6tg9xJ6tio1CCe7FuK
            sImwAZFEDfS574nnaTLDj8Mo5lUuUacuVNL+jzXp0QdFxHh+0AcRrg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T07:43:00Z"
    mac: ENC[AES256_GCM,data:VwOsyDxEfhxQ9CWAxjce9YxWznlyEsKCHmvo/g+b5/S/W25nGwHf9Q5fhLGXjPfDplalDwV/J/I8dek3TAINVoSAkXLGfXR322pYY5EuX9awVxn4ecXKvC9UPLrbgxaIHuT7N+LrdxzIwz0KEfoSGRxcO0+lw/UoHOU4we3m57A=,iv:mLAQmJZl96vR+2ztXAyAliBgXK9h7VjWS1O94b65jXE=,tag:5YgIaxQtYQeqKW40qwbNjg==,type:str]
    version: 3.13.1
