apiVersion: v1
data:
    NB_API_KEY: ENC[AES256_GCM,data:J1shHT2GectCsdtLzpy4hRhS5ifNfbkPfw8eDSYn1J/rWWadzG9dWPtj/XC/vUuwHeunCIPx38k=,iv:+8XJECv4pKCNJiXxmXuxPHy8wWTdMNHc9nz0FZUv1/8=,tag:aGlLb7iF6QR8g7mpQDum3Q==,type:str]
kind: Secret
metadata:
    name: netbird-mgmt-api-key
    namespace: netbird
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQeUtIdjBxc1E3YThsSGp2
            Q2taQWZ3cmduYkZEbFhYVzFjemJzVDAvSGpBCmViVFFlTi9RS05MVkNsYjFZNEVp
            UEorb0QzWmhzL0pFYS9CS25vQmZaY1EKLS0tIE5RSENBcTQydVQxSkF5MkNHcENp
            T2xKRVQ5MTZvSkRzazZ2TUlqN1AzNk0KRYNlL2//j5rDRkjg9CduAaM/vnyi5QID
            GASuXdaWfGWdgeFQIOVe86a4guPqb0mj5EY245lOw53+q1BjZG+7SQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-09T07:53:45Z"
    mac: ENC[AES256_GCM,data:rDMUjpKGN6n7KEMVGK5zRwoZeRKEbqUYn98Di9kQu1dxM+cnGJr8viqy1oiz02P2qsibWGddqE2jF2ad+7E3t5ZCYX7hCMcoIkeUmvNttLsucD0ORkScUWbeBghwGxo5ssi61sxl1TM4LtKocrSFrgY/4iZVjCl0IrPROZ7uio4=,iv:dhidhKbIGxeEIr7eIw8oH9YDokbVJPtyIsjfFmuQy7A=,tag:1N9OmILb0EJ2H+biKpwUmQ==,type:str]
    version: 3.13.1
