apiVersion: v1
kind: Secret
metadata:
    name: paperless-gpt-secrets
    namespace: paperless-ngx
type: Opaque
stringData:
    PAPERLESS_API_TOKEN: ENC[AES256_GCM,data:1lnMuha9EOiHkpup3QMuE/DiPsX3EYi1r5wq1XacIQSmCQlT2cOOSA==,iv:cf24aq6XENFw5VMySyUbgR0nlpluBdI666p/GmENCXM=,tag:UX50tWV4arbVCVmvPxmsJg==,type:str]
    OPENAI_API_KEY: ENC[AES256_GCM,data:I2+KsQN0+nnmBrrs7Z8TxHR/mKKDi6hZJpHmHw7LhpGCnWOrjpjCga0jOvIcaVGL0ENFKVwvQUlLAfNXO1q1ADCaX8Ph/5qsrhIlZWIC2yX0D66lcT/TrT7MFIYxta60CG7WEnPe01I58J3bmITY9qB8s4qVN5Ev3OxjvntmWk+SlvuQZHg4gB9BSx8YMepMvRtlE5B45axoKcjJElyOh6e8sDQ=,iv:tLs7BrmkX0X4Egj0mM3fL/15hqbVymjl9aDy98Z5ZBE=,tag:Bdn6GmLeDrGCZDIbpPS77A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBySTdybmcrLzBTUmwweE5U
            TGZSZ1V1N1lNTUhBVGNUUVhnOGJNOUJtbHhvCjhxMjhuVjZDUFMwMkw3RHVjQWNq
            Z0JZODVHanRLYnlUQnIwVC8xclZPZVUKLS0tIGgwaUVhbFFKWHdOUU96NHZhV1k2
            aXlEeVVMKzJKMHVVckJKcFN4VmxKd0UKFO6fgPgxxfK4hCjxZ8uT7kbI7RHYp0sz
            +Hd6ZpnyJPsW1Y7Nworb/TFbscL1w6ACwKBCjej2qD1sGRgadhwyUQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-23T15:53:36Z"
    mac: ENC[AES256_GCM,data:VeglEz01BYOih/DhklFyCsME3n7Da9g8YClIddtbGzjAJtv9F+fvKWcyiUfxMHybmysdU0a0yzj+iL8ZBNVe1ijStzNYzGfkkn9hQ7JA83eZ2lJWea3iHKsvXJT4YqRvW0w4IG74kj7QGA8vG2cvCgHDwWwrHsBeRhdGTgVS+0w=,iv:P6FROm8n7JMMKrcxeJ38j70jW5Mn6ltBs7zkyBD+Odo=,tag:fOqEVWT/PURMNqA1vE0+Hg==,type:str]
    version: 3.13.2
