apiVersion: ENC[AES256_GCM,data:cI4=,iv:XY0T3vLwfhVAOwtr6BDgVUYfVTHbmd9vGQEFDn8X48E=,tag:J5xJT5p++gxK0ZJO7ZL5Gw==,type:str]
kind: ENC[AES256_GCM,data:ep3FYR1w,iv:NQ19xaYApgverJqEdNJxvtR8XujBOj/sdGCHsHaXF4A=,tag:iIpK7XhvKVEwHyoJUQGvgw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:moYj1e7E28CaQ7yvsYtiE6QwfGb5vs6vdg==,iv:eg1nADfhqrhHtX4CTy/9/JURN6e8fkDcAEFdXs6Lvq8=,tag:Ee3CeDFq13VFVKIZDQvnAA==,type:str]
    namespace: ENC[AES256_GCM,data:ICPmKhIveuprBg==,iv:4vgVkrnGX1ojUyIyUkuY+TwYBNNuPnsoLyG7xlDp9mQ=,tag:rLgVxt/H+dPXtlZAu4puIw==,type:str]
    labels:
        app: ENC[AES256_GCM,data:yttHAzk0Mg==,iv:pZsu4iEh6wSd73JYJxlJ+ZqvN3pJGI7Ge0DR7NKn0SE=,tag:lgK9mKONw0e93p9Di5eqNg==,type:str]
        app.kubernetes.io/name: ENC[AES256_GCM,data:e3qSW5CqsQ==,iv:2xoQqyrRFk7TdDueEOADWKO2rS3oJu0S271GnrL+NWE=,tag:ke8rO4erV7MuvnO9ResWyg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:aEEEoXMJ3GoBOjQ=,iv:hyLSIjsk92yKX4+9JNpbKzPSv4ieJm+Ye8pczz5u/mU=,tag:9GoIzmzjcE/uNsitAk0ZZQ==,type:str]
type: ENC[AES256_GCM,data:tEs/P1Al,iv:462hSCnOSa11S5h5qsf96kslVnjysVbwxCZR6JwAk8U=,tag:ToeJew9uofFzxrR8sm0mWQ==,type:str]
stringData:
    admin-username: ENC[AES256_GCM,data:G1tMihI=,iv:hEf1T/T/3aVZTwvPWAzG5ge+SDRgzJ+HFQ5yKSu+7uM=,tag:sToEmrQO0NgB1CsvaP986w==,type:str]
    admin-password: ENC[AES256_GCM,data:Nyt4zDJf4D93PDk=,iv:TNCZp6cF9kVmpFg+GYonOoMllPSRGtxwZcmu64si9Gk=,tag:Cxwd6bM6zrFoiHAyO/4JGg==,type:str]
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2ZTN0QnlrRFdOU3oyOGR1
            dVRPMVcwT043QUdVdzRwdnRhcXJQd0NhNDFZCnB4ZUExelBGd2hwZUlpNFprZEw2
            azZrR0ZkWFVHMWdLL3hGNG5lRVJqMkEKLS0tIHlaQlZkdVhkOTBSM2VlaHlUUFlV
            WG1vZHhySmRZNSsrSjA2dHl1amZJNkkKbC+joI2OZdS0igNuLn8Vt2HNllkjJ5Ca
            27ahm7RpgLWY+OFZBxXXsvpSF8lwM1/8il4ihyV+0Lzl8RijcHzP1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T21:54:28Z"
    mac: ENC[AES256_GCM,data:M8gpQHiJjwxXat8zdb3lpBrowPiecODyD1Q+MDTakDZlJZlDZ8kCFvk95WqiglJeRSaFz3fs7i/eyuTQjflqrHbpC+YNXosEQs4iz+Nmcj0L51bz2ti1lxwSfcAYt1n0m8PXeczp7/5TrV9OJZQJrAxCjoSkXVl2dDnA/pMCiSQ=,iv:mLcsgdjXEFo0y54L8C+Qt++hMrt6Ucq5wD/fPJa//BE=,tag:6q6Fo295b/RjxlaJqWJX5w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
