apiVersion: ENC[AES256_GCM,data:OHw=,iv:BdFrc9vsuRA1PGzunET8ZykDjfHWvGneg8hDNQCd8K0=,tag:hbgkC+xXUc9utlHDUlahhw==,type:str]
kind: ENC[AES256_GCM,data:lHNL1YBi,iv:FbLyYseAUgUVoIzNnipDUDF60yMTo5geStDf7hhaVIQ=,tag:E3j4hzloNkvWMjK2dmWlYA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:yS1Qu/TGN0Y007RHC04gNFxKeVY4NPBLHw==,iv:sDqmlq3MY1F1QQ28k/5VN6FjNmffTi7KHseJ7GRV9II=,tag:nRWq+bAAtmMWDkNh9Imb7Q==,type:str]
    namespace: ENC[AES256_GCM,data:7EVZmfqAJl5n6g==,iv:kXkmpgop7nx2iR2eBaCou6jFiR4qQe5YJ/aXnsjir0E=,tag:61m4tkGZ46tD88A/mCe2mA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:NOiBQG1hpQ==,iv:BYwZWSxIu14jT2mKw8q8gdeygwsziWeuATg60YSfMDk=,tag:VoZo8g9aDOfcq0DTOvbh7w==,type:str]
        app.kubernetes.io/name: ENC[AES256_GCM,data:X87aljaUrQ==,iv:xRR+C+m1n+F17HrvpPi9pjY3nQKF//UAfz91xpbAwls=,tag:m7w3EOXE8N1CNZJxiIe7ZQ==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:5DWlyNxUM6QNW1Q=,iv:5QtycSegKkE+oKUT9inz3sRTpeqnUiVClOdNGrwbUCo=,tag:PrZk3k17DMA7CNScQCx6Yw==,type:str]
type: ENC[AES256_GCM,data:ybChEGxP,iv:l3g1EDexlO9oyC1bRwyasqbYu33usttHLs1lPlYjQBo=,tag:bnt8dYMAD0kC6G9ovLAoBA==,type:str]
stringData:
    admin-username: ENC[AES256_GCM,data:F6JvRpg=,iv:pV4F2FWBkW6K7kfn11TNKyjjMHi0iihw4kE994rE774=,tag:aZUx/m88AewW96OlhVKEfg==,type:str]
    admin-password: ENC[AES256_GCM,data:gQTWkDl2XrxIRt8=,iv:gwde9zuw5pPk0AQokqRDetQTmdfz0G5Vf53S1K41XE4=,tag:vB7H0OuegEt8h5JMucBptA==,type:str]
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBud09YV2tiWDc3OGczZkJH
            dlplSm8vWVpiZldXWGIvbUVJbW5aYXpEQlFFCmdoRDNHUzEwTWR4endXZEJrL1Z0
            blg3VmExNzhLM3BzdG1XZE90UXBGbWsKLS0tIGVlQjRpK0tOc0xjOGZvYjZKcERV
            N0VzZDFWUmJ2K1RHT2J1MXR6anBKOEUKBx3aLhB5+L/hfY2ZoISevyEPhduBXaZ3
            mR9LdoYzv30YqgKyg9kpKrs8NXv+LSPlz78I7/7stDTFe9hgDdqtVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T21:49:08Z"
    mac: ENC[AES256_GCM,data:lxSwMgOt69E6i0I4E8c7KQW9RnSfoVRX7HIMVRgP5wmlYpi2MIXfcs0NaRjdRFWVcb1F0+TYYbnr6lmp8QOk9ijrrZfA8IfmGuUskN7WwRDv5qGz7JYI7LGWZMEEnsm5sM7kC9FPFJSGzum9B47/CNZgBERk+8IB6BWfMBxYRL4=,iv:NmrMaUzsix3esMv0f2MnzsDByA6FtTLD2dbjgtitL98=,tag:vmX6wEm9ImPmVNsg1GoZfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
