apiVersion: ENC[AES256_GCM,data:ipQ=,iv:tBhZkT7NmkphY6BBUK6RskOknDNblkhkv1Nm3Fg5Wpo=,tag:d8Fm1caelfaDi4XZ7Tvl+w==,type:str]
kind: ENC[AES256_GCM,data:e2vDj1Cy,iv:xpC43y7S02mzAtGpq+HE03THhyECF0B8h4vXDigT2Sg=,tag:fpSZeTXem0jUyuNb3aH5zQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:bKX9HdDIj64K3Lh9f9k7C0jPGZC4D1NuDQ==,iv:aicZPuMZZVBZAkhGDIhgYZgbdvqgdQOHFMtpU1aM2tg=,tag:sEjsRgXbXbxoShKS1gS2CA==,type:str]
    namespace: ENC[AES256_GCM,data:DNbACwBAjMZ+8w==,iv:bbnrXWcWUOU7VJKMuMlI/+ArldU6Ly8IArgMdQYVEuk=,tag:L4ouf7LkVxGT/KWOXWO2Fg==,type:str]
    labels:
        app: ENC[AES256_GCM,data:38feoAoMtA==,iv:LBQKEc2EzlyDAX5XIC+M+Zdmgb5dXTIW+N3Tj0SEb9o=,tag:QwAK0fiFUvIktXQS7UmfMg==,type:str]
        app.kubernetes.io/name: ENC[AES256_GCM,data:OwKfJsRRxg==,iv:TDOTo5uEu/cjPhgaNf2mDPRK1C17rz3rnbHXHWbYB8M=,tag:QgeF6m4RLfk5uMd9JquOdg==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:0vLMEg==,iv:N4/N7uiNMhRbD7DbFmbxJNZr6fV7sKPRnHkgvIXtjnI=,tag:kfByaSBkIw7kTzvnXFN9vg==,type:str]
type: ENC[AES256_GCM,data:IxQSqIkN,iv:BmPs3JQ72LDKIy7bSygvxku3OdH9JZSV9mO9UgB/c8M=,tag:J0fRp2csfBibLtzUHiOZRA==,type:str]
stringData:
    admin-username: ENC[AES256_GCM,data:xYZBHVA=,iv:+/eZjmH8sw4TLvw3CgsPQgeapdTVmx4VHYpD+1EwZ1U=,tag:6Jvmv4ClZlx1jrUjin1iOA==,type:str]
    admin-password: ENC[AES256_GCM,data:CEf1IXR3uwr6sQ==,iv:lwQR/NI4pH13Eejhg+HDDJr0m1a107Bw7KNhKmCIi9k=,tag:eA+G8OCOQtR0ugaM/c9zAw==,type:str]
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2UFdJZzRRampDdGhTM3hu
            amJ2K1pFVjYxV2MwUlMzR2RNcWUrVHBwTncwCkd4c1lFeC93d2xOS0d4N3lxZzdw
            Z2lHandCMElIUDVNUUw1ckNqc3VuaEkKLS0tIFRSVTJ2ejlkUjJmUTZ4YmkrbG9k
            S1FrNStNUlhtQmllKzRNMTJHdWVKc0EKsY2Z7Ip2hPpnqNJ7N8kzvnAgIlxXIvmA
            hEq/sAbrFxaLxeNeWK0QeRhqxMcRPdaQr3f7TTtgvwLuow3acd9EHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T21:42:39Z"
    mac: ENC[AES256_GCM,data:g6gULsj2p1TtoV6AiLLILcaeU7LjjMXXOL7jCAJ3TONbL6aBWx/fmnGs5q5CBindBT+4qHyN9LEL8w/lPL2Zd5iyH1UIRq+x80IKqHkRagIVfxmpuUv8kpYouEJe1uNQqCXKFn6hxyX7XGFzxW6pCpKwCH1h4c3/o9QoA9h1deE=,iv:5wmBwbhbsaoJf0Sj7cf42zpIMjixBQViqZbNEywUTFw=,tag:HqhS1hBnTv5KHpPGrUy4cQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
