apiVersion: v1
kind: Secret
metadata:
    name: truenas-iscsi-driver-config
    namespace: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:QjHzKRNJIGIYCXkJGVXl/FPJc7e2bhfKRtfnL5hdVqMMwjttquGCEjoyBQjwjXWLWrdEoWISr2v+yZMCOL1MID/lw3yV1OVbJKQCwV0ogC3GUiRY0YJpCmemwClWJ0S3GYVXIlHP7rLYg8rdZ/DthImm7aijjyq92KfB66HU0eHWoDYe/2EXYHB4QDCZ/XXItbNoYRUNIn4Qk+Zs/w428rNeGERLb+et/V/BErY6u7kP+Ezv2I9aqX3cOaEtiwoZaMgrbH32hoL0/9VsExt+bOVzew+NB5W0nd8qW+ctZGQvkPJcfxnoeh+EpmStte3rnW7arw8DXsqbJRQd2JgUSAxg2UGTYQtOc+LhkKpZV5i922NXVjuwYrycbNZ0n9jfNJlHKNUrrwLpNTm8bplDcPnwT7FhFVbtg6gGclFzc43eq+GhN3Yo2Z3vz6hjlIRfFmtfWCMweQVxyuooAJktnF/P/C6/3JXyh81rST6wsp8BHldiBhXE4CSbj8v6/oRQ/1hlVS5yO3PJg5ywtia+Fhybue7zzwnDHhB3DAv0sX8k4eRePX/6LCqXUb5eXovwkeYZbTgs+HHStfAPxga4EFBOxp9UHtjkfoTGVn+WkGe9lmjP+sJMTMEu7m/V5Slnyv7Fh7uwgZ/NV0FTLUFhCub/ciD6COKzcn+2NuqSZ8B4tl800Y0bc+mur+wWpyYiGyx93sL3mtCF/Zfgw6dCr62KJUUACxwvkkb3+uK+8uYwkU+z2kRzgvQsXIJXLosyCiBEYzRfYXmY9DIOeOAJr2dRH1r9jMX86WPLGfrG4gH+7MYiOLc01R1g1nuezliS1T74Eyj/+c77MwEmywZxaIjnZBAoHANeUzNf5/8Nxd46T/cn0uCCm5WTt20x3Gmo/sDqEccdXfStdoId3CgX/U0e6Yawuf9QLs8cd0zTPe3M8sfGt4fN7g4ZAUV+0d10tPwuExww3rmKJftXntxQaqmuZykiNeuR9BLW5ltoXSTROeQNUgnftExwFynWvXocEN38YuSo+ePByB2xPQpftAe1Wtc1KN4LMCE/JplC8Ml37idrJRWOCcKw5A40rL4b/a1zGrojbyzzvxD/EcGYmzq7INKY1q9SvJg5Nin5eIlD/wy9Bv2L0Bp+ITAKSR4LaYXqxnNUxUjWXKrt/kGF7SAdPHuO7pFiovK+/EU7b2K2PSenMR3exQpSeE9SswvGpNMaL1soprULqHc1HpWv6MSJMzD6DAlKpwRZpGIno41xWLDlPWRbjD+wLuXQUX/q8oxMgkBRVyk6ETqjP9Qf1PurrZENjz/SqFoJ/FA/zttTBbaFBEOP13UV4zllaz2fDIyOHXFetPWo0/u8Kkcl4RIx3Eiogpz2N5kHrowm3XPhnU1ALxDHpeTMumBylJMfxQKDUi03mmjobI6B8FA5Ha5xlUw9Xl5Es6A5xfTMgZk2jiuxHsJQMPGuVHxEUdVxOUdWXU4q2XBbRsncrm34YV+KlEQWjwUnpGzcDjMbtCLUF4BiLpXfDaA6TYF2E+PE4d2SS7oN7GPgub/5E7kzSAo+Yjpp7B2boFMG3OOeclT4UXHoBa4hWX/cGe7a9Rml+TC18Nshd+Uzdg==,iv:c1yu09mptox+3AUezqGS/BgCinIbi/11B3XcyFgqG1c=,tag:rHl0I6mXjp59yKt0GOVIeQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjTk9abzc0VVBacXppSnZL
            WiszcGZlbUtOZTB2dzVwd24rYUUreVBHWVgwCkhNYTBqRUI0alFuTEc3QVFJem8y
            TUhlVldNaXdvTGltVnhLT0RwZUhqL0kKLS0tIGdLalFDc0FGOGFmOVErbG5SMXFW
            eUtCeGU3MVkvUnF0SWExcFduMGRPK00KDoiSuSLwLzvUZatEKMevad7zBYgkDSk1
            63s9AzC4ltPje7BIjq+KhQ9zzDJdYK8kUEOqk5/DanG5WfEfDuTCTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-24T14:56:14Z"
    mac: ENC[AES256_GCM,data:xC4EBCONT+HVcTfiM9dbbIsM7VITILUTMuVU1bBnGqZjj3OyLn+gS2Ib2z7p+LngviVs2KAevnYd3QhFcUnKMxnkXVS9w1bpLZJfhpk1ohLtr1WYuf2D4qHHt+3ZmsKxYhok51PIGH4KnUU7xBm6Rys6z5LyRx5Ue3YeBZ8SFXM=,iv:32qJw6LDn7b5jiM3j8xW1D+kig+5yeqF9GHydFfvbnU=,tag:GWYGPDOEKiBBF3IxQONNiQ==,type:str]
    version: 3.13.1
