apiVersion: v1
kind: Secret
metadata:
    name: truenas-iscsi-driver-config
    namespace: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:gUcC9VjrB/n7U/xB5e4+upB0sMqad8TOnEhZr7zeVsZxInHZZpvf/Ki9aGlpTtDREg9qEb39CkshFn7gQ8qtB8NDU9qTdM+1NSDA8Sn+rnBocwM9ffom3bKcf8oDuccvtAmTFrkXEtj+NIffftcMT34wSS9tDp5ApA4G93n37VoEO7e8rYOrUdckp3sIJI5sfPFJ1ymynqesKX9ESC8T1VfjgnHl5JscyxIAlQtUi8IxKhzhgOWCFAsl5TM6ljqQBt4Z2gMk4MN6Y/yR/SBOtIkBN+59QFjd9zp6FKyV04m9NdpMDOHeztX3d7jk68R6ZHZDyCrL/X1zU3fbQKUWDj8EFOkDBnDjsr2AJC5DITqncXUhSVFtEfGJmkgqKry/jJH9eLsjhe17hXckoGvivwewJBb5alvG6vm2w6739Gu264OqlXljXUwbUhPjgnEp3v8c37vMh8HiKApOH1dqcj0EdqutY0I62W9JUXzZuiz/N+owAWnnL11ugi7p4T3bLPzUjwOKJbR0qo0b5l3kO3aDvgvWyv0vNybXPdikSCzyuRJ7iwQtChDpeu6qp6H/1Ha4fzwKYsnHMgVjW96uPl3pWMY7D94TZTXTLsicBzYgO04Y5azw5m8NswTCYr3SVNZ19hiwB+tWNwqI8P/flkZOk46iUAh7xikeuyACkq0+A9569nQ4P23pvET791IFjg+pUR9nt+uv92jNMwR3ek26TopCsYSCp3tDi3rs6/vhU2Hl/mdm2oVXYmEbIzNJ+hzhdv/YMZqlsW09iNYs2/h1Lgi7WvlzOc40JYjb8UgL4KmSbISrpPhkkeYDqNXBLTm7yYgWN4HND3BFr2SWXXcn4kloxUcSxG/6XcIbi3h/Z6xM3wr4Y338G9Uq9sjyUtt5prS4/CX/8pjjTimJhj9ednxw03L5Y6eg9Lc8f8kncCyAMJa7rRzCdYKsDhq+uRokwmgyg/N+EPmqgNPUd9gOIla5oHdJtcVosTrf0YVgW2z6+9/J7ode0k3MY4yinGQ4zN0LY36z8ATLQv7Q64xpuJk6TpsZNTGoXNqI9ELIeRrE/ZIL2c8du7CMtGZlD6kDtOn9M7jtAItlv6fOBie37BSSID1kKDJ5FXDe0wBhwLhvnQWP2Hp6REBRbogpceMfCW0vCWJSA1GUFMi8Q3QJAKRcDS2w0c1SamIAfzV4fBU843ZSmMBk3aZ27VZbHh1PVkMzgcriefNZkturBUlOPu6hajzixC90hImogzi6zScLUtkkhVc4KJxzWGB4gUuwp/wuNRf5pT6MAF22LP4y9FwVAVxzH/BwVvw3ubRvhWPXZi8CfGSBCSv7QWi/irGr0Qqyi33j/Fu7qNJrOwh0TGKHWWuKJvLFudIcdDG7M4j6o4N5/0vOY9MA3/t0CDSRUfPZNt+RfG4tF/Xbj0tRhQAZPgTdeq6MuNFXkResI4rgHzgZBaY++N8rVCqWI+7Nr1JZuRHU6aD6u4bpF0Pf3cQhBJ3J8DKoOkiRhQTWlHDU9y/kE2SnyuKglu/F0j/7F1t6dKZQjxYV8rdHLIR3FV1IkItI6W9h+luajt+KJea8FoZL8eEa1xUatd18p4aYgaAj2taxNSPK,iv:FNbjsL28DqbvM0kO+7ykd4LpmC1GQgYOway89LLEZ6Q=,tag:yBQBa6bUUFHH3c1c46A3Xw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMlYzVm9wWUNnMlZkajQz
            S0FYSitBQVM2S3FlVXJIM3VSMk9PUGpsL0hNCnJCVk5EajRpTXpIeWpKVDVTSEpD
            SWw4dE96NWFuYXRyQ2hMQWp3RTYwTXMKLS0tIEpWT1Z4RVR4TmZBS2RLZ210dktL
            cDVMZWh2eHB0VmhrN2x0N0RDMEhnZkkKSzLviqponRQCL71fYgSqn4E2L/WJIxOp
            jnTeWPngxzA97LkeKNCakt9vqmyZANbWCsAiSfEv5Gvt1tTe5Aj7Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T09:27:19Z"
    mac: ENC[AES256_GCM,data:qogn3gePW46TBRdG/xR0GfkPOIqgR5iYlkhqZOea0udTyDNA91zrPPrpnYeC0pDDLzpiMk7JfsnZ7s6Cr8jfpPzlfRhx8XJ3QJW/DDJ0y3u7VFUs9kOWOPT7D3+5n9GJxzTKEHj0wf3StCLARZbmNbJJwnKItYIB5lyevPYKE3k=,iv:xuLTj0Hrl409vsj2aY0aV/3ER8B//Bk/lJBECs8rl1U=,tag:diqmQ1Tc4jHwU/84Q5v2MQ==,type:str]
    version: 3.13.1
