apiVersion: v1
kind: Secret
metadata:
    name: truenas-iscsi-driver-config
    namespace: democratic-csi
type: Opaque
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:W9YNIrJ1x1a9lyMnq9P/4iO4Hh0X0oizJVfCyAiQgKwElS6rMh9Tm1HgTtkSDm+8i02GNpot+6WdhE4dIeStQiaqmTNPqIkugj50m23ewMX4/xbutbBqpdYcOX8ciDFrkSGPSHaMHe0duLMDhHSo08delpOmsbgKEAd3+f+74iCkVSw0f+0wfWVYQ097xY/ZxFaNLdu+zor8f7xSLnWpVtV4AlYEz9IIxZU6mV9QdJ7Kycb2LMEKslg0fA+ARl33sthGZ1GTGOyhmLDPgxLHHVuJXtHOcLrNwfCDLn721KQ5B1DMmFFIw3MAFUiAUbufw+gURJk654K62Wc5TzHr0sDx0LNqYHLBuBjMYdi9bOqL6harl+IX8EVy2wGfe9NUWUgT6w/9Kqe+NRcnQqbddptZjIf9QIFmg+bPtv9tFrF1EoJWsyVVN7l4d3bFaAN612ODm5PLd5gvlsyY4sVtR+wfYvMwx4pKJ2RcKJKclgh5DgOwlq6YxKWDPpsN2KQGLp/chBCS/YGHoyRpiQOmbw4hx9xV6URZhCc8LqoPcMAlQJCr4boAri7azmS5H08zVBxq4hSQbOOf2hngMl5YgqgI4SbZDRgVQyBJIJgDvB5vltsU1IjDsXOVMfVCZuDm3K65WB2Fjeu7RPn53Lv4xjx/MIyu5EYYmtDNhQVNPjJzSOOLUIiO0uQHYOc2Xb6T882znuTy+2iPupkkPJkYa+KaPFMqCZgJwHKT09WD2pZIutFxNv7YppFOKdLqHTJ8i2sTXZ/mKpXK5WuqwrB4XI8uze4k6mqVw6lc4aT/tCObtQ8XlY5zMof2GEDI7xgapHtHBEYBNohqtsQSQ1FAW7cL9s0GQfPCnoTrxpycofyMoEzaM86ZQtjellJmleHceKfnOwhL9NWLHfR6W8VQAX7bTEDNQrqmqCOKFFIid7f2PlIaTcRmyU5OCj77IeaSWWkuOnLu6IbhZF9CtdVSnvbe7UkrqfcZXMu76aHMs2F0vH3mWk9OEL1cRoJ1fNjihTZ4i9fgac53CmTqZ3CUApoFUsrvSHOCYlU14weR/p1jBjeg4GR0wjFYDNOBaB2KZRVERzgHqQ3XfTiV9Zwwxm1r54siUyqu5bcXq7G1Mfq1mb1oq6FziNLXZgXyzZDcCssfjuWlkbEUr1O1d9ZmgN2gjKhmleqRboVSxpJAhcnoUMluNvyY8Jc0Uu2MdV39mWcfZV2eGWtnRDthOOU93ytoHISHpH9gLc0uNTmdZJj2mn5/TQ2DsP6565f7kIBw1TDzKrL2mb2flJmuvT3z/41BBqbZU9DN1oA3mxtsM9u94m7Hx7NGa5uvzYJIKJIzaauWHXv0/+LgBf6tdO3R+dwgzH4yhn9AUWccoTwJHnTOCNrHmSSKnfeg5xW25AxRSeoA30dO9a+nGLSLnwVdtNVSlSjOVgYl7zKTEzGR96sBwmSKoVGb9my35sX3ApxHbZWNIEEcQ9yMigc8Pyh/d2Q7o7yneP7cnGVzimqQ31i7gt9hADZKJZMBmal6dgouM4gfQSIAS8X4/AOhKi4JhpOomENL3ZvH37hY0l/zqCXftuOdGIKP+Qe0ZkryQWw5BS3nPNR6a2pADg==,iv:xmAOBQkWx/fFEYIZHzRwT/pKDWQmgg0w/EgRNf3ggI8=,tag:DYGS7dXSRmkgH9BDOGVjvA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvMlYzVm9wWUNnMlZkajQz
            S0FYSitBQVM2S3FlVXJIM3VSMk9PUGpsL0hNCnJCVk5EajRpTXpIeWpKVDVTSEpD
            SWw4dE96NWFuYXRyQ2hMQWp3RTYwTXMKLS0tIEpWT1Z4RVR4TmZBS2RLZ210dktL
            cDVMZWh2eHB0VmhrN2x0N0RDMEhnZkkKSzLviqponRQCL71fYgSqn4E2L/WJIxOp
            jnTeWPngxzA97LkeKNCakt9vqmyZANbWCsAiSfEv5Gvt1tTe5Aj7Kw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-23T20:42:04Z"
    mac: ENC[AES256_GCM,data:5hgDc4EUEA5KVfK42Ycrm5ncpN6HIdVcFsuE5kLyYK950tlKLOSq8x0I/A0nYsJ23l4dPWTp9+I/Zev683PHLdtItwb0daY78R+qtArq7vybQ1yNdV7ye4czuTOrJJfpyN3YAEZnBIuWtnfI6jYmxTzETGTM4dfNCFEMAk/5BkA=,iv:sIbcmrPlikDJjD1ziQ9am6TUinAng2uO7x643iEbmnY=,tag:ezWBf8My+1DKq3BEyKdqdQ==,type:str]
    version: 3.13.1
