apiVersion: v1
kind: Secret
metadata:
    name: paperless-ngx-integrations
    namespace: paperless-ngx
stringData:
    PAPERLESS_SOCIALACCOUNT_PROVIDERS: ENC[AES256_GCM,data:ocmCajAS6+99XdQNmWq0x8zeiiwq2QSEIZtCJzyeBd9GvzecShaO6j2+SMpUwGb+PwukzJGTf+TC5/D4RBHuXbKWEVwRhViWQoA4A61OzytA9bVcWx1NO+KAKCF+MPj8B6P15RYegX9sgrkcNwp9/dMMFB4UTINBopF8JU7owWCVPu/NaJUgpnLlFB4mYm24WWIS7KniMSFObQx0jRlBnYLOgEyuxqgAhqQKvpAQCtnuaqE7zVU5YWTw48i9uRjWUQ7aAnsPNbPFYP4uu+NsNHCkddkeXwOfPnar0mA+mFCwmgbmRueIrk+oq4Jl2lEBLMfpP6guSMNXX9YQnac0HlODF8UrBCHXXb7UGNo6Auduaoh6uZTXd535srrztNLjCWNzjoI2EuzY7Ad2JEXrWIenZPv7xiiQP4NrVrUz/qH4wON/ksGntrEzbjIH8ckLHY8aR671XKAHNEG05+3H1Be2m7E5e4xwJL7NMYIYBL7wjKAc9YdtGyutK3uWBxIsH3FpZPSu9fA71ZfDJ7CRc+a7BFqUSuwrx7PfhYY5AM0L5jYCun4MX7/ZjCAHy3q9FUmAAk8EyfxJ7JydLIvTwOGAhKlUqbrIoJkES6dY0Hu3uJ1S,iv:I8JJiXkEMmayRxc54OijArj5MOUyEgTPWTtE/ci08Ao=,tag:9wwLitdBEyWlXFvn3LyS7g==,type:str]
    SMB_USER: ENC[AES256_GCM,data:bOjsxrFFT4ML,iv:eKygXFNCLjYkAnPB1TmlAPZY5anEy34NK2Rts2RwZPE=,tag:q5jiYNCXuMz70qHIKuuFqQ==,type:str]
    SMB_PASSWORD: ENC[AES256_GCM,data:/2dYd6vLYEDJ,iv:LWzuhJfkujeGKn/YQurbgaKg4aCq8SCMnZA88guNbdY=,tag:YJXtYzvpaWq4RMRw5pMoxA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqRXFsTkdxUW1vSjhzMjJC
            SjZ1U3Qwa05oaHRtRHFxWDhmTTVLc2xpMUh3CnlTa21sbGFaTWpxMWRyT1RHM3N3
            YXhVL1Yzejc4bXRteDdDY3psTHpMa28KLS0tIG5lcFdGNE94ZUlvZWxPL2t0c244
            WDdrSFFVWHBEbXFOSmNkWnZ2VS9OV0kKdqALRXD1pfz5lGiRDTiNfbbjQpglnxZC
            lL+c+/U0iyFIxNgU2UD6WlzZojbiZ7xJfOS4oZr4gS9istGaS5Tgtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-02T14:06:50Z"
    mac: ENC[AES256_GCM,data:zbLmbPSGkZHWRbc+3iNJei3jAQE5gDUIsQzzlRrQeh1c95HbUsiSW4ngIZ0GKJsgL1DLp9p978ANC2uezfsqkg6Y+csX69JkOuS+LJ9/EiiMY6akn+DLYdHnLGEIQU2VQ6jrB5AcFl9eiwOHdEpCM2/zvqX8vO53l/t+h9ZqISs=,iv:v+dkpbeVh8Nf9jr7Q8OQgH8Z1kwG9yJzIdkNTrPGX6A=,tag:eorHPiNHdR4jHcaBdE2M3g==,type:str]
    version: 3.13.1
