apiVersion: v1
data:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:vEFt+PzWTBSb2Beh7gbm8bA5BLxIXiI2Mict0c1NY8/u96kOxX5AThDVNBIHt9TuBESKzO0bpeKEGLmC6766lWzjHS1VWnd5ZxAjo+6Ix9iLfsdAq0aATA==,iv:RFz2dYJ0pGMHPhtHz8TprOdnFp3zhaXcnwQTcQ4uzOk=,tag:Yy4hT+/E3V+u9FzCtoZrFA==,type:str]
    PAPERLESS_URL: ENC[AES256_GCM,data:Iyp9QatswinwsmNJ6Rd/qhIg+kBwodwpzqv0TBf8lMjoZ4bt543c1Q==,iv:A9VIJ/ziI2hUBVcuSq6VQEA+8zppeOoyWHFu5o5rPrg=,tag:yLYV4EMQsreynmrZf6Ymqw==,type:str]
kind: Secret
metadata:
    name: paperless-ngx
    namespace: paperless-ngx
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzaUVZRklVN3A2YXBTSHZS
            QUJsc1BFSkJzQ1kwV2J3a0wwSk5Xc3U2alJVCnVZcS9hNExYNU5kOVBOblBMNzBw
            RlE4a3gvZUxkZU4wTUdGbzgvN0dzMHcKLS0tIFBnMkMyS3kyTkZXMFpwc0VKckd1
            VDlyZjcxRlFlSkVYMWN0RWNHakt1ejAKqAantjNLJwqRrlM108BfiSgDD5I9PpLo
            UeSrRoIXGF10GqjIUN+gwlhdU2yC+MbH7/VE5cOZQ4A/BF1g+0h1oQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-22T14:25:51Z"
    mac: ENC[AES256_GCM,data:q+4HKNleLqRYU620xPA2O7+UydVTllL+iEnXt6C/ud52RPCqECA94q+AoAo8PDJQnjd6XOe40MdYiQ6CrzOQHFeE8CMJN/XaXkhO3Xjg5txsaU/6RO4AF5Pf/NpGQjf8z31TaSk0eSdex/ZONzdDg2SEwC81rzjZShlpJFt2BU8=,iv:HsA+YtKR5fF82IvTLt0ZMQ50PhWhMEHiGyk+a5O6fTA=,tag:I4DI0P9agbOyCIP6rg06Pw==,type:str]
    version: 3.13.0
