apiVersion: v1
data:
    PVE_TOKEN_NAME: ENC[AES256_GCM,data:w/slAqjEWSiewAYK9lX7aw==,iv:r98+UEZpRESMMLH6yiP5W2kFlCj0HdVIJAxvsQ4/Rv4=,tag:E7mv4O9Z6xSx3t92KyRVVQ==,type:str]
    PVE_TOKEN_VALUE: ENC[AES256_GCM,data:RcgRPWtGrL/255tpC5rVR1Vg/ctad4AFmQuIsOINMny9LvPddNhkgBCCTQg=,iv:t+T9PtuFrMbbn4Xa99++aN8rDmVQCBhFx3HrXR0jbA8=,tag:nztmiqxZYWOYC5hBLKlOnA==,type:str]
    PVE_USER: ENC[AES256_GCM,data:Jq7sp59F3tNI6TuRJhmp06KY9cY=,iv:VmYIOeSzZG3r2zTkd90YUjSb7Gvf3BW28+w7gbz217k=,tag:C2tKg51orAn0gI28n120Aw==,type:str]
kind: Secret
metadata:
    name: proxmox-exporter-credentials
    namespace: monitoring
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUSmlBQUZENUFxcjE5dDlh
            Uldjak5MOWlkdmdtY0s0OXg3WmtKZjlNdFNRClZabWtnWW5SRGZvVENEODZFL0hK
            bzk3Vk91Nmw5dU9hUk1oRWdDTFh3WlEKLS0tIFRrSk9UWjZFbTIzOWxVWFRtdzV1
            TGNIZjZ6Z0VRNTE4ajlNdWFyaXhYbUEKr8ro9HRhxgMBGK6ki0VjPEMXuHLDMh0R
            ENFTJKTBmNYl8kAfFmLZGuwo14xiWbHbxRKw2nhB0/sUxriVl380qQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-07T10:06:00Z"
    mac: ENC[AES256_GCM,data:CqefODYKekrQXg1s8sZq+P1X0nC2rJjxfTZ2i6Q0tetm5AGy+1dlCh7C1fGvtJQ60VZ7UdaX94qiLAZ179InbSM8Z4dw2IK3JJsgjKQpyNg3wT/Qa1HjMxF9em1xKoGIu3Ja31f8gMs9eY+3vP3OOz5YyVUivYgO2aC1DttK3Zw=,iv:cRHNlv8p51YqhniHpPqG+7swWY7WL9TzKei9TIZ9Jig=,tag:2230EfLaUfAuLZ+p1hsI4w==,type:str]
    version: 3.13.3
