apiVersion: v1
kind: Secret
metadata:
    name: truenas-exporter-credentials
    namespace: monitoring
type: Opaque
stringData:
    TRUENAS_URL: ENC[AES256_GCM,data:1HLROWVj57+sdbHYEI45aIV4fx8=,iv:zm/nZOzsq9ibPgcq+KyRWLeS+d8qLe5+S1+l0lkziXg=,tag:9NleVfpHO4sFGj3khaSsqw==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:00Q9clGs/wII8avBEuw2PI7y4oT6iY11U8FWhJaNSFdxgp9DUWf4M6s3eNeerKCh9saM5fJhaNhYsUrDD2OOGILQ,iv:Jp02y7GcGDriRUQ1geZ663bz6DycYlfPmPneA2NonG8=,tag:5JUr+b1IgWGjEFLLBQqsQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUktXbzVZWWZyNWFkbytN
            bHZFa3NMZHppeEdBNVdTZjZqVlJUaTZNNzJNCjk1d29BRE4xUUhSMS9oM0w0aHhU
            K3JKV1NDVUJJVG5uVmc2SENocitqd0kKLS0tIHdmYmVIYnhQQ1FJSWhTQ1hFTzkw
            NVp5R0lodno4ZnA5Q2g2MGx1OWJlWkkKZLvwsuFm78CK2r55xmc9Al0qUy7pRH33
            yjHU+wMB/ucczHGSSgkTF46e25wqJiaJ5rv67AmajEReZkr3ajJeTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-24T13:33:52Z"
    mac: ENC[AES256_GCM,data:cO/dYU3PKnPINOBlSnAnguiihcSSup+G5Ijwz8LdTrsZ1TSLQ/6Da11oYeTa9Uq9QYndBDn4RYOyP0/5Hjze08oaFeS4MTlTnTTXvz6aNgH3Lst1Jh0C9jUee1CBZWPO3fY3HilbyGemiJfqt/Tad5RSeuu6VeHsqvRLbkPzAnM=,iv:aVKj9xOJzkLjMzp0orMw3Hb2mMSBF5fBUGjuEC/kCGs=,tag:LYulr5NXF1atR6oHTg33Sw==,type:str]
    version: 3.13.1
