apiVersion: v1
kind: Secret
metadata:
    name: truenas-exporter-credentials
    namespace: monitoring
type: Opaque
stringData:
    TRUENAS_URL: ENC[AES256_GCM,data:6FjZbP4+3dGWtrAfBxQWeFGJ3+jX8RSx9g==,iv:JMTp5k/LeABEz89Zuaes9E5g/aGwaeDXF5vpiU1yo9M=,tag:K1yUt9intC0Gpq9CogCN9w==,type:str]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:00Q9clGs/wII8avBEuw2PI7y4oT6iY11U8FWhJaNSFdxgp9DUWf4M6s3eNeerKCh9saM5fJhaNhYsUrDD2OOGILQ,iv:Jp02y7GcGDriRUQ1geZ663bz6DycYlfPmPneA2NonG8=,tag:5JUr+b1IgWGjEFLLBQqsQg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxUktXbzVZWWZyNWFkbytN
            bHZFa3NMZHppeEdBNVdTZjZqVlJUaTZNNzJNCjk1d29BRE4xUUhSMS9oM0w0aHhU
            K3JKV1NDVUJJVG5uVmc2SENocitqd0kKLS0tIHdmYmVIYnhQQ1FJSWhTQ1hFTzkw
            NVp5R0lodno4ZnA5Q2g2MGx1OWJlWkkKZLvwsuFm78CK2r55xmc9Al0qUy7pRH33
            yjHU+wMB/ucczHGSSgkTF46e25wqJiaJ5rv67AmajEReZkr3ajJeTQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-21T09:26:16Z"
    mac: ENC[AES256_GCM,data:DLC7B+98LK6kcpsGB137qZFohmdVLGLl7l66fQkZZOz0XjMv1byNrZCg7QlX4lKd9FKXgg3W5QsGbreQpY4hxyi57BXSCUIx1A3ufYrLZb8jhh6e+4oL2z4bWnx1mvlbGl+gvmW01z4hT3thTUJqXXyPtJUJqQsFOElIVgdF8L4=,iv:mlSI1UU065iO1v6Rn138RGnCC3tNKcEH3a5oIdvbyik=,tag:nQq2iF3lewslGP8CNs8fpA==,type:str]
    version: 3.13.1
