apiVersion: ENC[AES256_GCM,data:HK8=,iv:MIGr+BsSSLhhLnvUhtMjezAu/NYEuTH08zchhiZuiUU=,tag:5ODbBtQ/c0dDevm5HGW3ig==,type:str]
kind: ENC[AES256_GCM,data:cKgGL9D9,iv:m0WH7Z2Wf7JwYqvPa+sjzVJXSFVoRGMCtXu7RoUUopM=,tag:w7eRhundPaFuie6AXum2fw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:3sCuZO3M6puvgEIKXJoZHfp1Q4xlb5Jbxg==,iv:PazLcTjcXSxhoxTQmfsnHssFIJZlRwFGSXuFUSXq7ZE=,tag:QZJXNUxYtZTnYf/QACyy7w==,type:str]
    namespace: ENC[AES256_GCM,data:NugP0Eau+QbyqQ==,iv:G56Q2+tu9RI0s+qO1SpRpJCjUf8U9hOCDABykKNNQaI=,tag:CWuEJ+93sWutn2jl8lfqJA==,type:str]
    labels:
        app: ENC[AES256_GCM,data:dUT2qfFn9Q==,iv:lLhiJG7LNKN3vij4J1+30ujroTQUqaF78gsq0YGF8Mw=,tag:41XtK3+dvtg3l4uLVWKa8g==,type:str]
        app.kubernetes.io/name: ENC[AES256_GCM,data:BCsQ68yFGg==,iv:F9IaszOXCSIIl9MYG039UzTQA5GeEyBt7OGuAOrbbS0=,tag:VMZTbd5ZYu5NA3jhuLdCGw==,type:str]
        app.kubernetes.io/component: ENC[AES256_GCM,data:r+heQnJnhyRNiJc=,iv:1z2mtfaJD1XUmwDjKPJIo6CEn/rJdIFfXwholajSAW4=,tag:YrZRbyETBn0Jd8hvjqpjCA==,type:str]
type: ENC[AES256_GCM,data:Zuf8lN8F,iv:uSx/IuPzLmaoF1gTQr6htnBc5z1jAGWPacZ1MFjfB1U=,tag:vVpxcTWYmf8ato3ehEO1TA==,type:str]
stringData:
    admin-username: ENC[AES256_GCM,data:71dkxG0=,iv:U49m0MjtpXC5l/pOx1HdNJqfJKX6mJtHAllPn3bwQmA=,tag:S9KOxM1c0JccMbFl0xDRyw==,type:str]
    admin-password: ENC[AES256_GCM,data:XdN5C4E5ixL7DKE=,iv:Qq9LEmtYitzeYu8vy0JgTq6GGviBC1A9/inwn3HrhLw=,tag:NRtTv8/cPT9Irb9DvD0k6A==,type:str]
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZTM1QXVZTTZTMlQrSDNx
            K2dzU0RIbmhYVk5IcUErRmJGOXpwSWRYcFc0CkFYMFZ0RU9aMEREdTF0YXl1blZL
            VEtVcFozMGJQdUJaa0lXZnlXbTVjRW8KLS0tIGNhZ25jM24rOEJ4VXJCaEJHMFRY
            My84UWhtZ0xjak9Jem9JVUhRTkJCcFkKj82ZFqU2qGcAobkPI2T3ZcpuLvq20tdQ
            ONiyuAEHyYd7DMDx1oJXebKPMlFhQzHyG9RnU91BToblfhV+nbz1bQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T21:59:52Z"
    mac: ENC[AES256_GCM,data:xrHGvfAZ3jollz+Os+M+fDpT2o4Rqfd2FhlnlXTHLPKlchVBnGI+70LBhjtbTvrdZtCRWDvyQki34qxlg7RRsbZmhhw/PO0dWz3lTpHXOyH9o3GJJDo/UDQDFwM9WxmvPDcc3xZpoUsvIqo9cq4fQlapDbwcKMGEt9z3tby6iIA=,iv:0drnON0+FbwEGM6/KyjFqA+hh+uk1wPiq/fc8cUunoE=,tag:jIloAURapvQKFagGCz6MTg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
