apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc.yaml
  - configmap.yaml
  - searxng-secret.secret.yaml
  - valkey-deployment.yaml
  - valkey-service.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
