apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: searxng-config
  namespace: searxng
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: truenas-iscsi
  resources:
    requests:
      storage: 100Mi
