apiVersion: v1
kind: Secret
metadata:
    name: searxng-secret-key
    namespace: searxng
type: Opaque
stringData:
    secret-key: ENC[AES256_GCM,data:+eweu8ryWJ1MFx3nHkIwUBIanONmMEuT29omCe+hcd3Y+OUqrwhCq72VqKffmolX64HOTO92iajdv4E9jInuNA==,iv:fEnjQBOPFi1H3pwf2BeVj/M9qJqMscfqbpiWO5lX8mM=,tag:k5rYy/MPzVqKCBDzLCXVMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSemtIMWthRzJIZWtQR0Ns
            cnBPcGdoMldwSzhvOThJOEppdWptQ29EVGtvCkRmNjNzdGZvNFVwczE2bFVjSHNa
            NHlnTituWEZEK0hRbHkyZlJtY1owdFkKLS0tIGxpWDZvaDV4RmNKS3lZZ0todXhI
            RlpqNTUwMVk3N0dENVkzd1pLek9ucTQKZkVuG95FO5abPBcGUVHqUQBDFRjRl3BF
            N4s4P4cUUfucAarYN3eFfRCd8LdBvb1aTfQ8an/2r/skHW3S02KW1A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T21:51:35Z"
    mac: ENC[AES256_GCM,data:jadcb/ZAhSznTele9jak/HxhnBAh8JSP2lulh3MrCHAqcMBy1wvdRHT7bX23HG5aAdeyt4YALZE3YuA1CmhO39yfuKiI1Z6gNof38IzoQB4o94jFccFAnUxpDFoKFmMVp9MHy/v2i7CyWqQdpxebV87ciYM2NSHt4G20JAtNhdU=,iv:x8+EdmsJwzlnKNPtKYjhcR7PnI8xpZoXdBHyVHEdSsQ=,tag:S0ykLFFCp2fd7fio4WSqwQ==,type:str]
    version: 3.13.0
