apiVersion: v1
data:
    SEARXNG_SECRET: ENC[AES256_GCM,data:0wwyNK2rh2/1spe0OKn8nBO+RFgSbEwVsUayZM8PUC8MyPz6GeJgLxqABbLLCCjPxQ1E/0kBsjkN8XfV8Mx16UdEmHErcKdLWmspTW4o/3yAZhGo1ks8FQ==,iv:2U4iUtIetua+2DwZQrLwfgd0TFk5q9Bj13aq8s1ad5w=,tag:CSmfm/ZRbpxpinp0YNmWMg==,type:str]
kind: Secret
metadata:
    name: searxng-secret
    namespace: searxng
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByNVA3U0N3YVNKYm1kYVp0
            ZG94WTcrK0ZNcjZWa0huL2U3SG1SbmtZLzNzCkVuQzVjZ2pINXNBd1RpKzlRbGRz
            UWZ3TWk1ZW1nNXBRT3BMcGo3RWxHczgKLS0tIDdoS21GT2NDenR1dW1RUUFjNkM0
            S1Y3UXUrd2pxa1lkOVd2c3gwTWVoOGcKvtJW0blQwlYb3qG+QK3SdqHrYeRuT9gq
            mfkLMmsvtAWXsEj4lJBzwYF67S1pCTeU+Oq33yWAlYhmJABGAE5BPQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-20T09:58:35Z"
    mac: ENC[AES256_GCM,data:NHCqy0VAoAUok5mM3GpxfndeoJRdRgbaYcJNd9fDYpTLjRZn9CVAUdNpPSv4MT1kAFA1jb2fXV37b+apFq6BjSu8zVkz8dp/aACiVlh66bujINY+04yUiKiU7cUdzUoVIHw5llc8v4fw50mgLYD0hzaLAOma5EPpMYAQw6JwSao=,iv:Ho5mCTe9M6FGAwlhqTb50zt/rHGspM9HCEYULH8LlA8=,tag:vY9c3qt0W1bPaxFt0pH8pA==,type:str]
    version: 3.13.0
