# apps/monitoring/victoria-metrics/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: victoria-metrics
  namespace: monitoring
  labels:
    app: victoria-metrics
    app.kubernetes.io/name: victoria-metrics
    app.kubernetes.io/component: monitoring
    release: victoriametrics
spec:
  selector:
    matchLabels:
      app: victoria-metrics
      app.kubernetes.io/name: victoria-metrics
      app.kubernetes.io/component: server
  endpoints:
    - port: http
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - monitoring
