apiVersion: v1
data:
    client-id: ENC[AES256_GCM,data:T4N6+zR5IOe417NFGQhD054MXA+Sw1Ns,iv:75zf0pA1x6ZyD/oP60gfZfLZbLoYc2oTuA7n3lHWX9o=,tag:9uu4RF/BpyW3QY8NKzR+aw==,type:str]
    client-secret: ENC[AES256_GCM,data:6vpLU9BxzhOHee5+oJIMSNnQo0d9U8Uy70cZJVmaCn/fRwtu1Q3ku/35/tJntjczbmCjJXA3YoH6T06+,iv:OKY788WRlEJt8YjZd2I9hBtLKjXLwdCgGY5PIBih9T0=,tag:0SpNisT5wfnanBucHuFbBA==,type:str]
kind: Secret
metadata:
    name: linkding-authentik-oauth
    namespace: linkding
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdy9XY01xV3poTEJQNGUz
            THkvY2I2V0RkTjg1alZqUVJyY0ZKUCt3ZlNjCjhBRDdvWUNocTE3eGdHTzZmVDBt
            c045OUdkdXY1ajJ5Y2J5SWVrM3d3SUkKLS0tIDJzc2pKL3B4bitQdnAzWlBMYk5z
            NWViVnRRYkZTeVNQaWhZenhUWUs5NzAKrEwAhwkXE6+OqgxHMnv0wINiwcs6ClTS
            XLOH8Nadh4loxBMcjWP805zj6ymX4RWfbllICp8tgZyJOOFwZI6asw==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-03T17:58:57Z"
    mac: ENC[AES256_GCM,data:0QhVtuFR2DekzG2+MNR1XUi03wBHVY5l29dPMU60tC+7zZTRY/+OY0AcUq0ETY0dUIrKD41mpytZAa94t2H8CWJwmtX6pjgRXaOnLVMG/QLhcGdyX3GwladnG7YKaE18uJNvlMzoezH+XEJDhdt76BgZGfatnHZy56FLCCanmpg=,iv:ya+/1NdUHgNRdnsMhE+ewPPqtLGTWJY/CeIZDEFkqwk=,tag:eR+IUrN8SP1gyh4TMDtjnw==,type:str]
    version: 3.13.1
