apiVersion: v1
kind: Service
metadata:
  name: sterling-pdf
  namespace: sterling-pdf
spec:
  selector:
    app: sterling-pdf
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
