apiVersion: ENC[AES256_GCM,data:5NI=,iv:3saFr5pRvMcRTPqZI5Nh91x920VNNRp0Pc3y0pA2JLw=,tag:F8OCdLyA5dqGVTI5DFzWbA==,type:str]
kind: ENC[AES256_GCM,data:PDjrJOIw,iv:eS0NI3xkq/fEdTgB275lwWBiTrXjzBmWgfAREFGwhyQ=,tag:6DY4N0FQ9IsTDRURGv6inQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:VwicMAkdJn+Ad0PEi5IiscelH8IqTKU6,iv:z/OUbtSX8QLXAmy/6/pKaUzxnsTpQrscNwNBdiiQyig=,tag:OIXAgIdVb4BwiKpfYwLCzw==,type:str]
    namespace: ENC[AES256_GCM,data:38acpSW4nYFtDhZ/,iv:yYey8P5GhLpsgghNfM0Y/BbCt3DzLsrPtzL9Gi6eo8g=,tag:M4sHMGa6Q7j1urALW+FgHQ==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:JI/x6FNttI99LCwwjWav5XO8ygMA9LeIhxn55fqTAe5v8zkf7aGnyyJPn0kAvBc9WpgZUdFapzpw0Mop+yBbhA==,iv:mWX/UlCyDdJwBCAz3DIjYxq8OtkOecKJEps9WbvWeXM=,tag:JOSZoL6f07/jxX3hVhK/4A==,type:str]
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcjRock5mVzVOUkhYR3Y3
            ZEdHZDZxNHVRM2dJbmxJcEdEclRabzRXSUFVCmZiOVpQV3drQ2Rad0tBWEFlc2Zr
            VFNYOUw1SlJpNExrMVhaOHE5QXR6QzAKLS0tIHNZZFdaNzZEV3NuRlBjYkZBVnF2
            SWNqdWVFK01Ta2tRS1JxSVVZVGJiaEUKwZZKDjIlyRffietxckt9+Unruu7oCtyQ
            7DeOnPsn1cJH9QRNVrtLeLZ6LCWCoxFSSuJ0nAUyxZgV4UnDsCNKOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T19:01:56Z"
    mac: ENC[AES256_GCM,data:b3bUXGEq25ZcV28vThrSgEEJIHpc6Pv8zgsK09BNOqOnyWG3O21ns27QPXLGgKLXwcFXQP1zkVe7NR2JC2ErZTUPDy54tuisxKW0UnljDSelxAPrzP8LqWLDXi36SxfEkzahFWwL316ZwZHMCl5i+GyuyK7HAKNJHWaGAfQWUUY=,iv:ctWUWZmqCqnGpKf6TwavJdr4C2krJnsQbDX2dZ5duS0=,tag:NUjRYq0+cFMXIw00CuxnfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
---
apiVersion: ENC[AES256_GCM,data:5NI=,iv:3saFr5pRvMcRTPqZI5Nh91x920VNNRp0Pc3y0pA2JLw=,tag:F8OCdLyA5dqGVTI5DFzWbA==,type:str]
kind: ENC[AES256_GCM,data:PDjrJOIw,iv:eS0NI3xkq/fEdTgB275lwWBiTrXjzBmWgfAREFGwhyQ=,tag:6DY4N0FQ9IsTDRURGv6inQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:9F5YTv0+g4ypLwmFPZAcaQI=,iv:epFeUU4RzMxaG3oKnTKErMBkmmqSZbAfoEF2GCl67d0=,tag:gTZm05atneqQaJsmVQZuEg==,type:str]
    namespace: ENC[AES256_GCM,data:wC9JSBX2KSX7fdqU,iv:7JBUFlh8o9pO4EQTvu0N2B5wMazZOR2QT5sAKu9TaOQ=,tag:AGgEqiZctRux9R95xe9O3A==,type:str]
stringData:
    api-token: ENC[AES256_GCM,data:JI/x6FNttI99LCwwjWav5XO8ygMA9LeIhxn55fqTAe5v8zkf7aGnyyJPn0kAvBc9WpgZUdFapzpw0Mop+yBbhA==,iv:mWX/UlCyDdJwBCAz3DIjYxq8OtkOecKJEps9WbvWeXM=,tag:JOSZoL6f07/jxX3hVhK/4A==,type:str]
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcjRock5mVzVOUkhYR3Y3
            ZEdHZDZxNHVRM2dJbmxJcEdEclRabzRXSUFVCmZiOVpQV3drQ2Rad0tBWEFlc2Zr
            VFNYOUw1SlJpNExrMVhaOHE5QXR6QzAKLS0tIHNZZFdaNzZEV3NuRlBjYkZBVnF2
            SWNqdWVFK01Ta2tRS1JxSVVZVGJiaEUKwZZKDjIlyRffietxckt9+Unruu7oCtyQ
            7DeOnPsn1cJH9QRNVrtLeLZ6LCWCoxFSSuJ0nAUyxZgV4UnDsCNKOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-16T19:01:56Z"
    mac: ENC[AES256_GCM,data:b3bUXGEq25ZcV28vThrSgEEJIHpc6Pv8zgsK09BNOqOnyWG3O21ns27QPXLGgKLXwcFXQP1zkVe7NR2JC2ErZTUPDy54tuisxKW0UnljDSelxAPrzP8LqWLDXi36SxfEkzahFWwL316ZwZHMCl5i+GyuyK7HAKNJHWaGAfQWUUY=,iv:ctWUWZmqCqnGpKf6TwavJdr4C2krJnsQbDX2dZ5duS0=,tag:NUjRYq0+cFMXIw00CuxnfQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
