apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingressclass.yaml
  - clusterissuer.yaml
  - hetzner.secret.yaml
  - wildcard-certificate.yaml
  # TODO: Add after SOPS encryption:
  # - hetzner-external-dns.secret.yaml
