apiVersion: v1
data:
    aws-access-key-id: ENC[AES256_GCM,data:7dXxIzYFbNHQi7x/VCPoyfNwrIF4yP+r0QvZyMs2QAJo+JV1,iv:mXtJrVxoIM+3AHu6bTdGsoKG7iH/jTah06YzJky0R18=,tag:PmCYDilP2ZOQ+Y+W8Mgu2Q==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:ipkBn49VTY7/YtK0A2J4QMVwcz85dOAGMmBDh2Lf4Z8kGpomf53gOeMNmZ9cR2taxIxkcZqqUm2OydVJwQCpC/jUOTcIqakz525QRItjEtLfX54FpZ82tg==,iv:R2O0xMiU6U0IEN9ecAFFTcHvEbHwWC9bhXsHxwizqbg=,tag:vHKLM1zw/myvL92d6eDwfA==,type:str]
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6QVNaNlFIUWZBOWphNGt2
            enBjQ0JpLzVxUlY2UGxIZDNEWVVVVzVxV21VCitCeFVta3RKNVc4bEFLcWZJV0FE
            bzQyeWNwbmRqaVBpSW9YcmpobzAvSmMKLS0tIGJtQzNhSXplbE9BNGJ1WSthdEJr
            SkVybnNzVm9QT29wZXBpNGhHQ25mUDQK0/KL4si90cv6tfdm66zQ7aHOJp+rGx+7
            qEhMyxMETFkAuaLKu+QPkDVdSP3x3I4mvCpubW2RnNuzzj93ztph1w==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T23:13:38Z"
    mac: ENC[AES256_GCM,data:+eF1Z4wyUQVTAueKN9XAwRzupNJjtu68cI8s6FqJR07WGk65Xxu5PsUKJk4tb+wuFRob6r4DJ/ylq2NAVH5quCI6JHfsTH2F6HxbzB2rbYfPXoFIiOh4HmTtuBgS1TovMvbLmM/Q8YqVj6pNzA0IY8A3FojgG6SMmQ22oY2O5nk=,iv:CCbu2W4rNbPWf7r0K3+afWxA+gKyRrghW3Ob+V1GEPg=,tag:I+YGIAiDoufFPIXyziNUhg==,type:str]
    version: 3.13.0
