apiVersion: ENC[AES256_GCM,data:VHs=,iv:+F4Qgf9a/Qk5Qk7ei/ZFGILoHgHBcQAN6xAI8jPrUSk=,tag:u4HHYq3e82+RpbMr8T+9Ew==,type:str]
kind: ENC[AES256_GCM,data:I5IZWiRq,iv:O+cA8YOGsnRSU3gfc9tHwni2ZbRwKXQIw03GARG7QM8=,tag:0XpVMKvEyyNBrSyNrH2gpg==,type:str]
metadata:
    name: ENC[AES256_GCM,data:KO0qXEReUbXU1+LoBgfBIxf1,iv:P/NTrq3Vezjwq/T6aZNVZvGUxLK4z5I0ibwXN4SHRRA=,tag:pQmxeVDAjxXYgkNRKIaGgA==,type:str]
    namespace: ENC[AES256_GCM,data:eDNQ7lpB,iv:QFy92lrssAiGhjAyh/olxLqeTGzFkUfiuNjR19PXIn0=,tag:5Xnmyp2zlXPB/0o0GhAuFg==,type:str]
type: ENC[AES256_GCM,data:pyL7740K,iv:GefYfZEwyZla1rEXJRDO2uE+MvwOJbZwY5Rro00+lm0=,tag:U0RtrkDyYPmOtuTGJ7RUlg==,type:str]
stringData:
    aws-access-key-id: ENC[AES256_GCM,data:Tuy04c6Km89pzMudYeJS0gAThb8=,iv:IGEkrT5gKAUUC9J2NQfK5SBBB7lm9H0PUy9bHr4Wdd4=,tag:Xh8HfT7bI/0wV7vlk767SQ==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:RcWD0wws5PlRpDYAX/93gvpG2Vzd+HC8yYjH9pblonHQGON0wn/IgA==,iv:yFAVC4shzNDGP1H5p5wNjbV/RXHpZT11Dr5Tu1cW8Lc=,tag:RRnuFx8WaSg/Q5XKI5CJ3A==,type:str]
sops:
    age:
        - recipient: age1u5lcvuuwd4lk7f3xewjk70j75yuh68myr89qkd0e8d44zgyjleeqw03vqs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArQXBUYXdFeWF4ekk5YmNq
            YTlHVDZ2YkVFYnRtM1prTmVzMEF3bFl5bXkwCnZlYmxWNklKVWJJaHhEeEs5ZFV2
            TEVSK3graTRjelNSS3RUdnNqdkpCREUKLS0tIEh4NmNLbnBwY0FjWS9jcUJ2bkxU
            ZDBSd0lISEZabytuWlQ1Y1VKYWpsQTAKhotUTdSC/8g5/Q1+QQE0AhEFs5MF49ra
            V3qtmGetSGpOXjqjpbZWdHNAcywMuegZ1zPR5vOXBwEHjyDsMQTyVQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-19T15:02:27Z"
    mac: ENC[AES256_GCM,data:640QIO7xuupD4ZqUObxrGfn+bLPLcTy5KVE5mdROFmT+Rsw22LhI4QgdRRtmY1sFwuUnAE5gdumTQz5AuDKLypGmdTp3On2hv8yBACRSUyrlwmE1HPgE3U0/749AAtAYBW3fs3ZQQ43Wv37LnV4/LrWm6VAiI1+MIv2oq1KWK6Y=,iv:UOh9AW+DZR07kefzJGwpYUHFGVa6ZJOZYEoNe5+i72A=,tag:2geM8mmIcG1lBVrwFpWWIA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
