apiVersion: v1
data:
    cloud: ENC[AES256_GCM,data:aFuvsA0s9eSgNSoBYJvpYqGAlCn+ljnAOuMgsT4amCGEdGiEkm1ixuuwsuBAgtsfqOPO99HeU/hHxgfX04wfvNFPBMgf20OoghuhBuEnAd+OoWIek6tKTMoooUyvqCL2HAC2fKc6wbxOewXEtAJ1P1azPUQl95/1U1/axrjtPGELKn7MaySQvF9CX4yAkSerilp/JpIUaXspAa2S2lWPZWyZl1lDn2wKq2A0nL8TqmWm5Fwvuse888bWerINhA4q,iv:wS9B1+ETdamc2RSRq6QLkkb4X/w/fTzq87Y926+gXDs=,tag:xop5uFAwUEtYO7BAD9mKdg==,type:str]
kind: Secret
metadata:
    name: velero-credentials
    namespace: velero
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdG96bU1NL3V0NURTZElD
            NkJ4NWxLNFpoUjdjaEF2a2gwU2k0Q2VEWFVjCjVzMkQxcUdQSE52TUV1TXdwUDll
            YzMxUmRkSy84T2hTTUp2OEpXTStrR00KLS0tIGp5VlhmODUwZVJ4NVl5WU5yMVIy
            OHFOTXExTXlvR3hmYnVCWDl6YVZtekEKSQ1o7n3lTzoWWW4w7MB43Pu+Za+V24Gh
            eXQO12QDfhePGvjXGpg/wJHrgBNQaU+gMbT7XLlNiHasuh/5nAmX8w==
            -----END AGE ENCRYPTED FILE-----
          recipient: REMOVED_BY_HISTORY_REWRITE
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-19T23:37:47Z"
    mac: ENC[AES256_GCM,data:x81uyFH2zKKQJJ4e1zMp0ZJ+UMfXyvu+GHGCQ6snryY7PhEjztuHOcJeVnzFneXMgyLg+M9UJaZuShT+lwPYnWXhkO4jk/DLbrJUzhV+Cwp2ZJUJeztahplOiCHfb1DoGRQN39JfQJGAkEMMBL4Q09ZLTHBwWrfaZDMX6Pk+Cog=,iv:hDzEylK96+jA8gJsSlBR5AflQHzsOL9hjBhbkUztyRQ=,tag:zKvA0C2SZ533boMKXUpuaA==,type:str]
    version: 3.13.0
