apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-ingress-nginx
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    # Public/Internal traffic enters via the NGINX ingress controller.
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
